Repository Netflix/dispatch, pull requests merged in 2020-04, with the labels that each got.

#197 Adds columns visibility, service, and document to the incident type table Web view
  src/dispatch/static/dispatch/src/incident_type/Table.vue
Labels: enhancement

#219 Ensuring we are enforcing require fields.
  src/dispatch/static/dispatch/src/definition/NewEditSheet.vue
  src/dispatch/static/dispatch/src/document/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident/ReportForm.vue
  src/dispatch/static/dispatch/src/incident_priority/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident_type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/individual/NewEditSheet.vue
  src/dispatch/static/dispatch/src/service/NewEditSheet.vue
  src/dispatch/static/dispatch/src/tag/NewEditSheet.vue
  src/dispatch/static/dispatch/src/task/NewEditSheet.vue
  src/dispatch/static/dispatch/src/team/NewEditSheet.vue
  src/dispatch/static/dispatch/src/term/NewEditSheet.vue
Labels: bug

#234 Updates Slack configuration documents
  docs/.gitbook/assets/admin-ui-incident-types (1).png
  docs/.gitbook/assets/slack-conversations-incident-notification (1).png
  docs/.gitbook/assets/slack-setup-commands-0.png
  docs/.gitbook/assets/slack-setup-events.png
  docs/configuration/plugins/configuring-slack.md
Labels: documentation
