Repository Netflix/dispatch, pull requests merged in 2020-03, with the labels that each got.

#67 Tests, refactoring, and bugfixes
  .github/workflows/list_and_test.yml
  src/dispatch/database.py
  src/dispatch/group/models.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/messaging.py
  src/dispatch/incident/service.py
  src/dispatch/participant/flows.py
  src/dispatch/participant/models.py
  src/dispatch/participant/service.py
  src/dispatch/participant_role/flows.py
  src/dispatch/participant_role/models.py
  src/dispatch/participant_role/service.py
  src/dispatch/plugins/dispatch_slack/views.py
  tests/conftest.py
  tests/conversation/test_conversation_service.py
  tests/factories.py
  tests/group/test_group_service.py
  tests/incident_priority/test_incident_priority_service.py
  tests/incident_type/test_incident_type_service.py
  tests/individual/test_individual_service.py
  tests/participant/test_participant_service.py
  tests/participant_role/test_participant_role_service.py
  tests/service/test_service_service.py
  tests/ticket/test_ticket_service.py
Labels: bug, enhancement, tests

#72 Improves participant role flows
  src/dispatch/incident/flows.py
  src/dispatch/incident/service.py
  src/dispatch/participant/service.py
  src/dispatch/participant_role/flows.py
  src/dispatch/participant_role/service.py
  tests/factories.py
  tests/participant_role/test_participant_role_service.py
Labels: bug, enhancement, tests

#73 [WIP] Adds new env vars for the JIRA plugin and refactors plugin code
  docker/.env.example
  docs/configuration/plugins/jira.md
  src/dispatch/plugins/dispatch_jira/config.py
  src/dispatch/plugins/dispatch_jira/plugin.py
Labels: bug, documentation, enhancement

#82 fix env key in doc
  docs/configuration/configuration.md
Labels: documentation

#103 Adds messaging for ChatOps commands
  docs/configuration/configuration.md
  src/dispatch/cli.py
  src/dispatch/config.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/messaging.py
  src/dispatch/main.py
  src/dispatch/messaging.py
  tests/conftest.py
Labels: documentation, enhancement

#96 Fixing issue where stable time would always be overwritten with utcnow()
  .gitignore
  src/dispatch/cli.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/models.py
  src/dispatch/incident/service.py
  src/dispatch/incident/views.py
  src/dispatch/plugins/dispatch_jira/plugin.py
  src/dispatch/plugins/dispatch_slack/config.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/views.py
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/store.js
Labels: bug

#115 Adds visibility column to the incident type model
  src/dispatch/alembic/versions/50d0688878ae_.py
  src/dispatch/enums.py
  src/dispatch/incident/enums.py
  src/dispatch/incident/models.py
  src/dispatch/incident_type/models.py
  src/dispatch/plugins/dispatch_slack/views.py
  src/dispatch/static/dispatch/src/incident_type/NewEditSheet.vue
Labels: enhancement

#127 Feature/incident visibility (part deux)
  src/dispatch/incident/flows.py
  src/dispatch/incident/messaging.py
  src/dispatch/incident/scheduled.py
  src/dispatch/incident/service.py
  src/dispatch/plugins/dispatch_google/drive/plugin.py
Labels: enhancement

#131 Fixes typo in env var
  src/dispatch/config.py
Labels: bug

#150 Fixes an issue where document dropdowns weren't populated.
  src/dispatch/document/models.py
  src/dispatch/static/dispatch/src/document/DocumentSelect.vue
  src/dispatch/static/dispatch/src/service/ServiceSelect.vue
Labels: bug

#164 Adds ability to restrict access to and sharing of content in the incident drive
  docs/configuration/configuration.md
  src/dispatch/config.py
  src/dispatch/incident/flows.py
  src/dispatch/plugins/dispatch_google/drive/drive.py
  src/dispatch/plugins/dispatch_google/drive/plugin.py
Labels: enhancement

#174 Updates docs
  docs/configuration/plugins/configuring-jira.md
Labels: documentation

#176 Updates more docs
  docs/configuration/app.md
  docs/configuration/plugins/configuring-g-suite.md
  docs/configuration/plugins/configuring-pagerduty.md
  docs/installation.md
Labels: documentation
