Repository Netflix/dispatch, pull requests merged in 2021-08, with the labels that each got.

#1522 Adds label action
  .github/workflows/enforce-labels.yml
Labels: enhancement

#1499 Make PD plugin aware of escalation policy rule types
  src/dispatch/plugins/dispatch_pagerduty/service.py
Labels: enhancement

#1528 Fixes an issue with term filters
  src/dispatch/database/service.py
  src/dispatch/incident/models.py
  src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue
Labels: bug

#1530 Bugfix/sample data columns
  data/dispatch-sample-data.dump
  src/dispatch/database/revisions/core/versions/2021-07-22_8f364cf49a23.py
Labels: bug

#1526 Syncing document terms was accessing the wrong attribute
  src/dispatch/document/scheduled.py
Labels: bug

#1533 Allow build time VUE_APP variables
  docker/Dockerfile
Labels: enhancement

#1532 Fixes issues with the way that the plugin instance combo box was being used
  src/dispatch/static/dispatch/src/plugin/PluginInstanceCombobox.vue
  src/dispatch/static/dispatch/src/plugin/store.js
  src/dispatch/static/dispatch/src/workflow/store.js
Labels: bug

#1531 Speeds up the responsiveness of cli commands
  src/dispatch/cli.py
Labels: enhancement

#1534 Ensures that the update button is correctly aligned
  src/dispatch/static/dispatch/src/App.vue
Labels: enhancement

#1537 Fixes issue with submitting an incident with a visibility
  src/dispatch/incident/service.py
Labels: bug

#1541 Queries Project API if project parameter is included in URL
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
Labels: bug

#1542 Revert "Queries Project API if project parameter is included in URL"
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
Labels: bug

#1543 Makes id in ProjectRead optional
  src/dispatch/incident/models.py
Labels: bug

#1544 Installs the plugins before running scheduled tasks
  src/dispatch/cli.py
  src/dispatch/decorators.py
Labels: bug

#1546 Fixes issue with the wrong description being saved for tasks.
  src/dispatch/plugins/dispatch_google/drive/task.py
Labels: bug

#1552 Fixes issue where 'stable_at' wasn't being set from the UI.
  src/dispatch/incident/flows.py
Labels: bug

#1553 Removing un-needed lens
  src/dispatch/plugins/dispatch_pagerduty/service.py
  src/dispatch/plugins/dispatch_slack/menus.py
  tests/conference/test_conference_service.py
  tests/conversation/test_conversation_service.py
  tests/document/test_document_service.py
  tests/event/test_event_service.py
  tests/feedback/test_feedback_service.py
  tests/group/test_group_service.py
  tests/incident_cost/test_incident_cost_service.py
  tests/incident_cost_type/test_incident_cost_type_service.py
  tests/incident_priority/test_incident_priority_service.py
  tests/incident_type/test_incident_type_service.py
  tests/notification/test_notification_service.py
  tests/organization/test_organization_service.py
  tests/report/test_report_service.py
  tests/storage/test_storage_service.py
  tests/ticket/test_ticket_service.py
Labels: enhancement

#1551 Ensuring that commands issued from outside of incident channels specify organization
  src/dispatch/incident_cost/models.py
  src/dispatch/plugins/dispatch_slack/actions.py
  src/dispatch/plugins/dispatch_slack/commands.py
  src/dispatch/plugins/dispatch_slack/decorators.py
  src/dispatch/plugins/dispatch_slack/events.py
  src/dispatch/plugins/dispatch_slack/menus.py
  src/dispatch/plugins/dispatch_slack/modals/feedback/handlers.py
  src/dispatch/plugins/dispatch_slack/modals/feedback/views.py
  src/dispatch/plugins/dispatch_slack/modals/incident/handlers.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/plugins/dispatch_slack/socket_mode.py
Labels: bug

#1560 Update "First User" instructions in documentation
  docs/installation.md
Labels: documentation

#1562 Renames label doc to documentation
  .github/workflows/enforce-labels.yml
Labels: bug

#1565 Fixes OrganizationSlug regex
  src/dispatch/models.py
Labels: bug

#1568 Uses correct enum when setting resource type for executive report documents
  src/dispatch/messaging/strings.py
  src/dispatch/report/flows.py
  src/dispatch/report/scheduled.py
Labels: bug

#1558 Fixes issue with global search
  src/dispatch/search/views.py
  src/dispatch/static/dispatch/src/search/api.js
  src/dispatch/static/dispatch/src/search/store.js
Labels: bug

#1571 Adds parameters command documentation
  docs/admin-guide/administration/incident/plugins/configuring-slack.md
Labels: documentation

#1567 Fixes issue with trigger function on organization creation
  src/dispatch/database/manage.py
  src/dispatch/search/fulltext/__init__.py
Labels: bug

#1535 Addresses some sticky circular imports with our pydantic models
  src/dispatch/database/manage.py
  src/dispatch/definition/models.py
  src/dispatch/incident/models.py
  src/dispatch/incident/views.py
  src/dispatch/models.py
  src/dispatch/participant/models.py
  src/dispatch/plugins/dispatch_slack/modals/workflow/handlers.py
  src/dispatch/search/fulltext/__init__.py
  src/dispatch/search/views.py
  src/dispatch/static/dispatch/src/search/store.js
  src/dispatch/term/models.py
  src/dispatch/workflow/models.py
  src/dispatch/workflow/service.py
  tests/conftest.py
  tests/workflow/test_workflow_service.py
Labels: enhancement

#1575 Adds some UI documentation and tightens up table interface
  src/dispatch/static/dispatch/src/auth/OrganizationMemberTable.vue
  src/dispatch/static/dispatch/src/definition/Table.vue
  src/dispatch/static/dispatch/src/document/reference/ReferenceTable.vue
  src/dispatch/static/dispatch/src/document/runbook/RunbookTable.vue
  src/dispatch/static/dispatch/src/document/template/TemplateTable.vue
  src/dispatch/static/dispatch/src/feedback/Table.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident_cost_type/Table.vue
  src/dispatch/static/dispatch/src/incident_priority/Table.vue
  src/dispatch/static/dispatch/src/incident_type/Table.vue
  src/dispatch/static/dispatch/src/individual/Table.vue
  src/dispatch/static/dispatch/src/notification/Table.vue
  src/dispatch/static/dispatch/src/plugin/Table.vue
  src/dispatch/static/dispatch/src/project/Table.vue
  src/dispatch/static/dispatch/src/service/Table.vue
  src/dispatch/static/dispatch/src/tag/Table.vue
  src/dispatch/static/dispatch/src/tag_type/Table.vue
  src/dispatch/static/dispatch/src/task/Table.vue
  src/dispatch/static/dispatch/src/team/Table.vue
  src/dispatch/static/dispatch/src/term/Table.vue
  src/dispatch/static/dispatch/src/workflow/Table.vue
Labels: documentation, enhancement

#1587 Adding tagging via slack message events
  src/dispatch/plugins/dispatch_slack/events.py
Labels: enhancement
