Repository Netflix/dispatch, pull requests merged in 2021-09, with the labels that each got.

#1596 Fixing issue where FAQ wouldn't populate on pre-filled projects
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
Labels: bug

#1584 Enhancement/evergreen
  src/dispatch/cli.py
  src/dispatch/database/revisions/tenant/versions/2021-08-26_3820fb661728.py
  src/dispatch/document/models.py
  src/dispatch/document/scheduled.py
  src/dispatch/document/service.py
  src/dispatch/evergreen/scheduled.py
  src/dispatch/messaging/email/utils.py
  src/dispatch/messaging/strings.py
  src/dispatch/models.py
  src/dispatch/notification/models.py
  src/dispatch/notification/service.py
  src/dispatch/plugins/dispatch_google/gmail/plugin.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/service/models.py
  src/dispatch/service/service.py
  src/dispatch/static/dispatch/src/document/reference/ReferenceNewEditSheet.vue
  src/dispatch/static/dispatch/src/document/runbook/RunbookNewEditSheet.vue
  src/dispatch/static/dispatch/src/document/template/TemplateNewEditSheet.vue
  src/dispatch/static/dispatch/src/notification/NewEditSheet.vue
  src/dispatch/static/dispatch/src/notification/store.js
  src/dispatch/static/dispatch/src/search/SearchFilterCombobox.vue
  src/dispatch/static/dispatch/src/service/NewEditSheet.vue
  src/dispatch/static/dispatch/src/service/store.js
  src/dispatch/static/dispatch/src/team/NewEditSheet.vue
  src/dispatch/static/dispatch/src/team/store.js
  src/dispatch/team/models.py
  src/dispatch/team/service.py
Labels: enhancement

#1599 Allowing the default incident type and priorities to be used
  src/dispatch/incident/service.py
  src/dispatch/incident_priority/service.py
  src/dispatch/incident_type/service.py
  src/dispatch/individual/models.py
  src/dispatch/main.py
Labels: bug

#1603 fix formatting typos
  docs/admin-guide/administration/incident/plugins/configuring-slack.md
Labels: documentation

#1604 Fixes bug in how tactical reports are created via the UI.
  requirements-dev.txt
  src/dispatch/report/flows.py
Labels: bug

#1606 Fixing an issue were multiple transactions could happen in the same session
  src/dispatch/main.py
Labels: bug

#1608 Removes tracking-only checkbox from incident reporting form
  src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/incident/store.js
Labels: enhancement

#1609 Making primary properties optional
  src/dispatch/incident/models.py
Labels: bug

#1610 We do not resolve incident roles and page the commander for incidents opened as closed
  src/dispatch/incident/service.py
Labels: enhancement

#1611 Adds functionality to group release notes by label
  utils/release_notes.py
Labels: enhancement

#1612 Fixes an issue where incident tags could not be updated.
  src/dispatch/incident/service.py
  src/dispatch/plugins/dispatch_slack/modals/incident/handlers.py
Labels: bug

#1613 Fixes issue when setting the incident cost in the ticket
  package-lock.json
  package.json
  src/dispatch/incident/flows.py
  src/dispatch/incident/service.py
  src/dispatch/plugins/dispatch_jira/plugin.py
Labels: bug

#1614 Adds better repr for our sqlalchemy objects
  src/dispatch/database/core.py
Labels: enhancement

#1616 Ensures new incident roles match all priorities
  src/dispatch/database/revisions/tenant/versions/2021-08-09_b73416df5744.py
Labels: bug

#1617 Fixes an issue with service id confusion and tagging incident creation
  src/dispatch/incident/service.py
Labels: bug

#1618 Fixing incident tag creation
  src/dispatch/incident/service.py
Labels: bug

#1628 Fixes build errors induced by move to slim base image
  docker/Dockerfile
Labels: bug, dependencies

#1598 Enhancement/monitors
  setup.py
  src/dispatch/__init__.py
  src/dispatch/cli.py
  src/dispatch/conversation/enums.py
  src/dispatch/database/revisions/tenant/versions/2021-09-03_ebe0cb6528ba.py
  src/dispatch/messaging/strings.py
  src/dispatch/monitor/flows.py
  src/dispatch/monitor/models.py
  src/dispatch/monitor/scheduled.py
  src/dispatch/monitor/service.py
  src/dispatch/plugin/service.py
  src/dispatch/plugins/bases/__init__.py
  src/dispatch/plugins/bases/monitor.py
  src/dispatch/plugins/dispatch_github/__init__.py
  src/dispatch/plugins/dispatch_github/_version.py
  src/dispatch/plugins/dispatch_github/plugin.py
  src/dispatch/plugins/dispatch_slack/actions.py
  src/dispatch/plugins/dispatch_slack/events.py
  src/dispatch/plugins/dispatch_slack/models.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/plugins/dispatch_slack/socket_mode.py
Labels: enhancement

#1629 Update setup.py
  setup.py
Labels: enhancement

#1639 Fix table name for incident_role_incident_priority in db migration
  src/dispatch/database/revisions/tenant/versions/2021-08-09_b73416df5744.py
Labels: bug

#1638 Support windows file path & env vars for CLI serve command
  src/dispatch/cli.py
  src/dispatch/config.py
  src/dispatch/main.py
  src/dispatch/static/dispatch/package.json
Labels: enhancement

#1640 Fixing template creation within incident types
  src/dispatch/static/dispatch/src/document/template/TemplateNewEditSheet.vue
  src/dispatch/static/dispatch/src/document/template/TemplateSelect.vue
Labels: bug

#1642 Bugfix/forecast filter
  src/dispatch/incident/metrics.py
  src/dispatch/incident/views.py
  src/dispatch/static/dispatch/src/dashboard/IncidentOverview.vue
  src/dispatch/static/dispatch/src/incident/IncidentForecastCard.vue
Labels: bug

#1644 Fixes incident date filtering
  src/dispatch/static/dispatch/src/incident/IncidentWindowInput.vue
Labels: bug

#1645 Allows all roles except member to see restricted incidents
  src/dispatch/database/service.py
  src/dispatch/static/dispatch/src/dashboard/IncidentOverview.vue
Labels: bug

#1648 Fixes organization admin and manager permissions
  src/dispatch/auth/permissions.py
Labels: bug

#1643 Fixes incident type plugin metadata UI
  src/dispatch/static/dispatch/src/incident_type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/plugin/PluginInstanceCombobox.vue
  src/dispatch/static/dispatch/src/plugin/PluginMetadataInput.vue
  src/dispatch/static/dispatch/src/plugin/store.js
Labels: bug

#1656 Updates description for incident visibility
  docs/admin-guide/administration/incident/incident-type.md
Labels: documentation

#1657 Fixing jira plugin field
  src/dispatch/plugins/dispatch_jira/plugin.py
Labels: bug

#1658 Bugfix/jira configuration
  src/dispatch/database/revisions/tenant/versions/2021-09-16_3820a792d88a.py
Labels: bug

#1661 Adjusting task lookback
  src/dispatch/task/scheduled.py
Labels: bug

#1662 Re-adding plugin combobox
  src/dispatch/plugin/service.py
  src/dispatch/static/dispatch/src/plugin/NewEditSheet.vue
Labels: bug
