Repository Netflix/dispatch, pull requests merged in 2021-11, with the labels that each got.

#1779 Making socket mode optional in UI
  src/dispatch/plugins/dispatch_slack/config.py
Labels: bug

#1773 Moves more settings to projects and deprecates unneeded settings
  docker/.env.example
  docs/admin-guide/administration/incident/incident-cost-type.md
  docs/admin-guide/administration/server.md
  src/dispatch/config.py
  src/dispatch/database/revisions/tenant/versions/2021-10-28_f95247c63eda.py
  src/dispatch/evergreen/scheduled.py
  src/dispatch/feedback/messaging.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/models.py
  src/dispatch/incident/scheduled.py
  src/dispatch/incident_cost/service.py
  src/dispatch/plugins/generic_workflow/plugin.py
  src/dispatch/project/models.py
  src/dispatch/task/flows.py
  src/dispatch/task/models.py
  src/dispatch/task/scheduled.py
  tests/conftest.py
Labels: enhancement

#1780 Adds ability to mark incidents readonly on incident close
  src/dispatch/incident/flows.py
  src/dispatch/plugins/bases/storage.py
  src/dispatch/plugins/dispatch_google/drive/drive.py
  src/dispatch/plugins/dispatch_google/drive/plugin.py
Labels: enhancement

#1781 First user should be owner not admin
  docs/installation.md
Labels: documentation

#1782 Enhancement/tag exclusivity
  src/dispatch/database/revisions/tenant/versions/2021-11-01_ecabe49272c8.py
  src/dispatch/incident/models.py
  src/dispatch/project/models.py
  src/dispatch/static/dispatch/src/tag_type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/tag_type/store.js
  src/dispatch/tag_type/models.py
  src/dispatch/task/flows.py
Labels: enhancement

#1783 Enhancement/participant message counter
  src/dispatch/database/revisions/tenant/versions/2021-11-01_5f96c909a3c0.py
  src/dispatch/incident_cost/service.py
  src/dispatch/participant/models.py
  src/dispatch/plugins/dispatch_slack/events.py
Labels: enhancement

#1788 Fixing reference
  src/dispatch/incident/flows.py
Labels: bug

#1791 Fixes issue creating organizations
  src/dispatch/database/manage.py
  src/dispatch/organization/service.py
Labels: bug

#1792 Adds UI elements for project settings
  src/dispatch/static/dispatch/src/project/NewEditSheet.vue
  src/dispatch/static/dispatch/src/project/store.js
Labels: enhancement

#1793 Adds a subscribe button to incident notifications
  docs/user-guide/incident-participant.md
  src/dispatch/conversation/enums.py
  src/dispatch/incident/scheduled.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/actions.py
  src/dispatch/static/dispatch/src/incident/IncidentStatus.vue
Labels: enhancement

#1794 Removes some google drive specific options to the plugin instance
  src/dispatch/plugins/dispatch_google/drive/plugin.py
Labels: enhancement

#1795 Fixing button rendering
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/messaging.py
Labels: bug

#1796 Fixing button rendering
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/events.py
  src/dispatch/plugins/dispatch_slack/messaging.py
Labels: bug

#1797 Fixing linting
  src/dispatch/plugins/dispatch_google/drive/plugin.py
Labels: enhancement

#1798 Fixing button ref
  src/dispatch/plugins/dispatch_slack/messaging.py
Labels: bug

#1804 Fixing bug with incident cost calculation
  src/dispatch/incident_cost/service.py
Labels: bug

#1805 allowing for multiple action buttons
  src/dispatch/incident/flows.py
  src/dispatch/incident/scheduled.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/actions.py
  src/dispatch/plugins/dispatch_slack/events.py
  src/dispatch/plugins/dispatch_slack/messaging.py
Labels: bug

#1806 Fixes issues with slack tagging and socket mode
  src/dispatch/monitor/service.py
  src/dispatch/plugins/bases/storage.py
  src/dispatch/plugins/dispatch_slack/actions.py
  src/dispatch/plugins/dispatch_slack/events.py
  src/dispatch/plugins/dispatch_slack/menus.py
  src/dispatch/plugins/dispatch_slack/modals/incident/handlers.py
  src/dispatch/plugins/dispatch_slack/socket_mode.py
  src/dispatch/plugins/dispatch_slack/views.py
Labels: bug

#1807 Fixes the subscribe to incident ui button
  src/dispatch/incident/flows.py
  src/dispatch/incident/views.py
  src/dispatch/plugins/dispatch_slack/actions.py
  src/dispatch/static/dispatch/src/incident/IncidentStatus.vue
  src/dispatch/static/dispatch/src/incident/api.js
  src/dispatch/static/dispatch/src/incident/store.js
Labels: bug

#1808 Fixes our ability to disabling downloading of incident document
  src/dispatch/incident/flows.py
  src/dispatch/plugins/dispatch_google/drive/plugin.py
Labels: bug

#1811 Allows for plugin secrets to be updated
  src/dispatch/models.py
  src/dispatch/plugin/views.py
Labels: bug

#1814 Excludes fields not required for dashboards
  src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue
Labels: enhancement

#1815 Adds some activity for old incidents
  src/dispatch/database/revisions/tenant/versions/2021-11-01_5f96c909a3c0.py
Labels: bug

#1816 Fixes an issue with marking storage readonly when there is none
  src/dispatch/incident/flows.py
Labels: bug

#1817 Fixes an issue with missing reported at
  src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue
Labels: bug

#1821 Fixes issue with the incident type dashboard not rendering
  src/dispatch/static/dispatch/src/incident_type/IncidentTypeCombobox.vue
Labels: bug

#1823 Bugfix/incident type dashboard render
  src/dispatch/static/dispatch/src/incident_type/IncidentTypeCombobox.vue
Labels: bug

#1825 Makes the monaco editor load lazily reduces bundle size by 3x
  src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue
Labels: enhancement

#1830 Removes commander and liaison service columns from incident type table
  src/dispatch/static/dispatch/src/incident_type/Table.vue
Labels: enhancement

#1831 Removes duplicated Pydantic fields
  src/dispatch/incident/models.py
Labels: bug

#1836 Making project owner optional
  src/dispatch/project/models.py
Labels: bug

#1824 Removes status code check
  src/dispatch/database/manage.py
  src/dispatch/organization/service.py
  tests/api/test_schema.py
Labels: bug

#1837 Fixes a bug were settings couldn't be filled on plugin creation
  src/dispatch/plugin/models.py
  src/dispatch/plugins/dispatch_google/config.py
  src/dispatch/static/dispatch/src/plugin/NewEditSheet.vue
  src/dispatch/static/dispatch/src/plugin/PluginCombobox.vue
Labels: bug

#1838 Fixes an issue were flow breaks when no group plugin exists
  src/dispatch/incident/flows.py
Labels: bug

#1845 Fixes typo in subscribe to incident messaging
  src/dispatch/plugins/dispatch_slack/actions.py
  src/dispatch/static/dispatch/package-lock.json
Labels: bug

#1847 Fixes schemathesis tests
  tests/api/test_schema.py
Labels: bug

#1849 Updates pinned version for scipy package
  requirements-base.in
  requirements-base.txt
  requirements-dev.txt
Labels: enhancement
