Repository Netflix/dispatch, pull requests merged in 2022-03, with the labels that each got.

#1868 Enhances the performance of the incident data model
  src/dispatch/__init__.py
  src/dispatch/database/revisions/tenant/versions/2021-11-18_ce5c4ac967d8.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/models.py
  src/dispatch/incident_type/models.py
  src/dispatch/models.py
  src/dispatch/participant/flows.py
  src/dispatch/participant_role/flows.py
Labels: enhancement

#2030 Minor fixes surrounding data sources
  src/dispatch/cli.py
  src/dispatch/data/source/service.py
  src/dispatch/static/dispatch/src/data/source/EditBasicInfoTab.vue
  src/dispatch/static/dispatch/src/data/source/Table.vue
  src/dispatch/static/dispatch/src/data/source/dataFormat/NewEditSheet.vue
  src/dispatch/static/dispatch/src/data/source/store.js
Labels: bug

#2037 Bugfix/source links
  src/dispatch/static/dispatch/src/data/source/EditLinksTab.vue
Labels: bug

#2040 Improves incident filtering reliability
  src/dispatch/static/dispatch/src/incident/IncidentWindowInput.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
Labels: enhancement

#2041 Improves task, feedback, query, and source filter dialogs
  src/dispatch/incident/models.py
  src/dispatch/static/dispatch/src/data/query/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/data/source/Table.vue
  src/dispatch/static/dispatch/src/data/source/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/feedback/Table.vue
  src/dispatch/static/dispatch/src/feedback/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/task/Table.vue
  src/dispatch/static/dispatch/src/task/TableFilterDialog.vue
Labels: enhancement

#2045 Fixes task status filtering and adds the ability for model to be specified during table option parsing
  src/dispatch/static/dispatch/src/data/query/store.js
  src/dispatch/static/dispatch/src/data/source/dataFormat/store.js
  src/dispatch/static/dispatch/src/data/source/environment/store.js
  src/dispatch/static/dispatch/src/data/source/status/store.js
  src/dispatch/static/dispatch/src/data/source/store.js
  src/dispatch/static/dispatch/src/data/source/transport/store.js
  src/dispatch/static/dispatch/src/data/source/type/store.js
  src/dispatch/static/dispatch/src/definition/store.js
  src/dispatch/static/dispatch/src/document/runbook/store.js
  src/dispatch/static/dispatch/src/document/store.js
  src/dispatch/static/dispatch/src/document/template/store.js
  src/dispatch/static/dispatch/src/feedback/store.js
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/static/dispatch/src/incident_cost_type/store.js
  src/dispatch/static/dispatch/src/incident_priority/store.js
  src/dispatch/static/dispatch/src/incident_type/store.js
  src/dispatch/static/dispatch/src/individual/store.js
  src/dispatch/static/dispatch/src/notification/store.js
  src/dispatch/static/dispatch/src/plugin/store.js
  src/dispatch/static/dispatch/src/search/utils.js
  src/dispatch/static/dispatch/src/service/store.js
  src/dispatch/static/dispatch/src/tag/store.js
  src/dispatch/static/dispatch/src/tag_type/store.js
  src/dispatch/static/dispatch/src/task/store.js
  src/dispatch/static/dispatch/src/team/store.js
  src/dispatch/static/dispatch/src/term/store.js
  src/dispatch/static/dispatch/src/workflow/store.js
Labels: bug

#2046 Adds apply filter button to dashboards
  src/dispatch/static/dispatch/src/dashboard/DataDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/TaskDialogFilter.vue
  src/dispatch/static/dispatch/src/incident/IncidentWindowInput.vue
Labels: bug

#2047 Disables ad-hoc tag creation (e.g. combobox)
  src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue
  src/dispatch/static/dispatch/src/data/query/EditBasicInfoTab.vue
  src/dispatch/static/dispatch/src/data/query/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/data/source/EditBasicInfoTab.vue
  src/dispatch/static/dispatch/src/data/source/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident_role/PolicyRoleBuilder.vue
  src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue
  src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue
Labels: bug

#2048 Improvement/incident closed at
  src/dispatch/data/source/service.py
  src/dispatch/static/dispatch/src/incident/IncidentWindowInput.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/store.js
Labels: improvement

#2049 Bugfix/incident forecasting
  src/dispatch/incident/metrics.py
  src/dispatch/incident/views.py
  src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue
  src/dispatch/static/dispatch/src/incident/IncidentWindowInput.vue
Labels: bug

#2052 Improves data filtering reliability
  src/dispatch/data/source/service.py
  src/dispatch/database/service.py
  src/dispatch/incident/metrics.py
  src/dispatch/incident/views.py
Labels: bug

#2053 Improves title of dashboard filter dialogs
  src/dispatch/static/dispatch/src/dashboard/DataDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/TaskDialogFilter.vue
Labels: improvement

#2054 Bugfix/task dashboard
  src/dispatch/static/dispatch/src/dashboard/TaskDialogFilter.vue
Labels: bug

#2058 Adds resolution to incident close review notification
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/strings.py
Labels: enhancement

#2060 Fixes issue with incident task creation
  src/dispatch/incident/models.py
Labels: bug

#2061 Return projects and incident types sorted by name desc
  src/dispatch/static/dispatch/src/incident_type/IncidentTypeCombobox.vue
  src/dispatch/static/dispatch/src/incident_type/IncidentTypeSelect.vue
  src/dispatch/static/dispatch/src/incident_type/store.js
  src/dispatch/static/dispatch/src/project/ProjectCombobox.vue
  src/dispatch/static/dispatch/src/project/store.js
Labels: enhancement

#2062 Fixes incident forecast and makes sure url params are respected in dashboard.
  src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/IncidentOverview.vue
  src/dispatch/static/dispatch/src/incident/IncidentForecastCard.vue
Labels: bug

#2067 Fixing selects, making them searchable
  src/dispatch/static/dispatch/src/data/query/QuerySelect.vue
  src/dispatch/static/dispatch/src/data/source/SourceSelect.vue
  src/dispatch/static/dispatch/src/data/source/dataFormat/DataFormatSelect.vue
  src/dispatch/static/dispatch/src/data/source/environment/EnvironmentSelect.vue
  src/dispatch/static/dispatch/src/data/source/status/StatusSelect.vue
  src/dispatch/static/dispatch/src/data/source/transport/TransportSelect.vue
  src/dispatch/static/dispatch/src/data/source/type/TypeSelect.vue
  src/dispatch/static/dispatch/src/incident/IncidentSelect.vue
  src/dispatch/static/dispatch/src/project/ProjectSelect.vue
Labels: bug

#2068 Making source required for query creation
  src/dispatch/data/query/models.py
Labels: bug

#2071 Enhancement/data source UI
  src/dispatch/static/dispatch/src/data/source/Table.vue
  src/dispatch/static/dispatch/src/filters.js
Labels: enhancement

#2075 Makes default time range timezone aware
  src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue
Labels: bug

#2073 Bugfix/data status
  src/dispatch/static/dispatch/src/data/source/Table.vue
Labels: bug

#2084 Fixes issue with comboboxes not displaying multiple items with the same name.
  src/dispatch/static/dispatch/src/data/query/QuerySelect.vue
  src/dispatch/static/dispatch/src/data/query/store.js
  src/dispatch/static/dispatch/src/data/source/SourceSelect.vue
  src/dispatch/static/dispatch/src/data/source/dataFormat/DataFormatCombobox.vue
  src/dispatch/static/dispatch/src/data/source/dataFormat/DataFormatSelect.vue
  src/dispatch/static/dispatch/src/data/source/environment/EnvironmentCombobox.vue
  src/dispatch/static/dispatch/src/data/source/environment/EnvironmentSelect.vue
  src/dispatch/static/dispatch/src/data/source/status/StatusCombobox.vue
  src/dispatch/static/dispatch/src/data/source/status/StatusSelect.vue
  src/dispatch/static/dispatch/src/data/source/transport/TransportCombobox.vue
  src/dispatch/static/dispatch/src/data/source/transport/TransportSelect.vue
  src/dispatch/static/dispatch/src/data/source/type/TypeCombobox.vue
  src/dispatch/static/dispatch/src/data/source/type/TypeSelect.vue
  src/dispatch/static/dispatch/src/document/template/TemplateSelect.vue
  src/dispatch/static/dispatch/src/incident/IncidentCombobox.vue
  src/dispatch/static/dispatch/src/incident/IncidentFilterCombobox.vue
  src/dispatch/static/dispatch/src/incident/IncidentSelect.vue
  src/dispatch/static/dispatch/src/incident_cost_type/IncidentCostTypeCombobox.vue
  src/dispatch/static/dispatch/src/incident_type/IncidentTypeCombobox.vue
  src/dispatch/static/dispatch/src/individual/IndividualCombobox.vue
  src/dispatch/static/dispatch/src/individual/IndividualSelect.vue
  src/dispatch/static/dispatch/src/project/ProjectCombobox.vue
  src/dispatch/static/dispatch/src/project/ProjectSelect.vue
  src/dispatch/static/dispatch/src/search/SearchFilterCombobox.vue
  src/dispatch/static/dispatch/src/service/ServiceSelect.vue
  src/dispatch/static/dispatch/src/service/ServiceSelectNew.vue
  src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue
  src/dispatch/static/dispatch/src/tag_type/TagTypeFilterCombobox.vue
Labels: bug

#2074 Enhancement/mini nav
  src/dispatch/static/dispatch/src/components/AppDrawer.vue
Labels: enhancement

#2086 Fixes a typo such that aggregate correctly gets reset
  src/dispatch/static/dispatch/src/data/source/store.js
Labels: bug

#2087 Adds support for multi year charts and turns off animations to help performance.
  src/dispatch/static/dispatch/src/dashboard/IncidentOverview.vue
  src/dispatch/static/dispatch/src/incident/IncidentActiveTimeCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentCommandersLocationBarChartCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentCostBarChartCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentForecastCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentHeatmapCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentParticipantsLocationBarChartCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentParticipantsTeamBarChartCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentPriorityBarChartCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentReportersLocationBarChartCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentResolveTimeCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentTagsTreemapCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentTypeBarChartCard.vue
  src/dispatch/static/dispatch/src/task/TaskActiveTimeCard.vue
  src/dispatch/static/dispatch/src/task/TaskIncidentPriorityBarChartCard.vue
  src/dispatch/static/dispatch/src/task/TaskIncidentTypeBarChartCard.vue
Labels: enhancement

#2088 Fixes a few issues with the incident dashboard drilldown table
  src/dispatch/static/dispatch/src/dashboard/IncidentDrillDownTable.vue
Labels: bug

#2083 Adds support for user settings
  src/dispatch/auth/models.py
  src/dispatch/auth/service.py
  src/dispatch/auth/views.py
  src/dispatch/database/revisions/tenant/versions/2022-03-16_03b7e0d36519.py
  src/dispatch/static/dispatch/src/auth/OrganizationMemberEdit.vue
Labels: enhancement

#2089 Moves owner permission check for user update to function logic
  src/dispatch/auth/views.py
Labels: enhancement

#2090 Adds a protection for when we send the feedback direct message to all participants
  src/dispatch/auth/views.py
  src/dispatch/incident/messaging.py
Labels: enhancement

#2093 Uses the simple search dictionary for fulltext search
  src/dispatch/tag/models.py
Labels: bug

#2107 Hovering over a tag name shows its description and clicking on it opens its URI
  src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue
Labels: enhancement

#2108 Updates the incident templates doc
  docs/admin-guide/administration/incident/templates.md
Labels: documentation

#2109 Removes unnecessary bot token scopes from Slack doc
  docs/admin-guide/administration/incident/plugins/configuring-slack.md
Labels: documentation

#2113 Updates Slack documentation
  docs/admin-guide/administration/incident/plugins/configuring-slack.md
Labels: documentation

#2114 Adds screenshots to Slack docs
  docs/.gitbook/assets/slack-plugin-contact-information-resolver.png
  docs/.gitbook/assets/slack-plugin-conversation-management.png
  docs/.gitbook/assets/slack-setup-commands-2.png
  docs/admin-guide/administration/incident/plugins/configuring-slack.md
Labels: documentation

#2121 Uses the simple search dictionary for incident type search
  src/dispatch/incident_type/models.py
Labels: enhancement
