Repository Netflix/dispatch, pull requests merged in 2022-09, with the labels that each got.

#2481 Add support for mapping case types to incident types
  src/dispatch/case/type/models.py
  src/dispatch/case/type/service.py
  src/dispatch/case/type/views.py
  src/dispatch/database/revisions/tenant/versions/2022-09-02_f9384b873721.py
  src/dispatch/document/flows.py
  src/dispatch/group/flows.py
  src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/case/type/Table.vue
  src/dispatch/static/dispatch/src/case/type/store.js
  src/dispatch/static/dispatch/src/incident_type/IncidentTypeSelect.vue
  src/dispatch/storage/flows.py
  src/dispatch/ticket/flows.py
Labels: enhancement

#2491 Removes Flake8 project config file
  .flake8
Labels: skip-changelog

#2492 Bumps Python version in Pyproject toml file
  pyproject.toml
Labels: skip-changelog

#2493 Checks if commander has a relationship to an oncall service before attempting to page
  src/dispatch/incident/flows.py
Labels: bug

#2482 Creates an incident when a case is moved to the escalated status
  src/dispatch/case/flows.py
  src/dispatch/group/flows.py
  src/dispatch/plugins/dispatch_google/drive/drive.py
  src/dispatch/plugins/dispatch_google/drive/plugin.py
  src/dispatch/storage/enums.py
  src/dispatch/storage/flows.py
  src/dispatch/ticket/flows.py
Labels: enhancement

#2494 Adds header-based auth plugin
  docs/admin-guide/administration/server.md
  setup.py
  src/dispatch/config.py
  src/dispatch/plugins/dispatch_core/plugin.py
Labels: enhancement

#2499 Only update the tactical group if we have a new assignee
  src/dispatch/case/flows.py
Labels: enhancement

#2503 Replaces assoc object tables in favor of 1:1 relationships for case and types, priorities, and severities
  setup.cfg
  src/dispatch/case/models.py
  src/dispatch/case/service.py
  src/dispatch/database/revisions/tenant/versions/2022-09-09_4452426c6905.py
Labels: enhancement

#2501 Bugfix/table layout
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/priority/Table.vue
  src/dispatch/static/dispatch/src/case/severity/Table.vue
  src/dispatch/static/dispatch/src/case/type/Table.vue
  src/dispatch/static/dispatch/src/data/query/Table.vue
  src/dispatch/static/dispatch/src/data/source/Table.vue
  src/dispatch/static/dispatch/src/data/source/dataFormat/Table.vue
  src/dispatch/static/dispatch/src/data/source/environment/Table.vue
  src/dispatch/static/dispatch/src/data/source/status/Table.vue
  src/dispatch/static/dispatch/src/data/source/transport/Table.vue
  src/dispatch/static/dispatch/src/data/source/type/Table.vue
  src/dispatch/static/dispatch/src/definition/Table.vue
  src/dispatch/static/dispatch/src/feedback/Table.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident_cost_type/Table.vue
  src/dispatch/static/dispatch/src/incident_priority/Table.vue
  src/dispatch/static/dispatch/src/incident_role/Table.vue
  src/dispatch/static/dispatch/src/incident_type/Table.vue
  src/dispatch/static/dispatch/src/individual/Table.vue
  src/dispatch/static/dispatch/src/notification/Table.vue
  src/dispatch/static/dispatch/src/plugin/Table.vue
  src/dispatch/static/dispatch/src/project/Table.vue
  src/dispatch/static/dispatch/src/service/Table.vue
  src/dispatch/static/dispatch/src/tag/Table.vue
  src/dispatch/static/dispatch/src/tag_type/Table.vue
  src/dispatch/static/dispatch/src/task/Table.vue
  src/dispatch/static/dispatch/src/team/Table.vue
  src/dispatch/static/dispatch/src/term/Table.vue
  src/dispatch/static/dispatch/src/workflow/Table.vue
Labels: enhancement

#2504 Removes relationship to source in the case data model
  src/dispatch/case/models.py
  src/dispatch/case/service.py
  src/dispatch/database/revisions/tenant/versions/2022-09-09_e49209df586d.py
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/store.js
Labels: enhancement

#2505 Adds missing Vue template for project in the feedback table
  src/dispatch/feedback/models.py
  src/dispatch/static/dispatch/src/feedback/Table.vue
  src/dispatch/static/dispatch/src/feedback/store.js
Labels: enhancement

#2506 Allows setting breadcrumbs to utilize the whole width before collapsing
  src/dispatch/static/dispatch/src/case/priority/Table.vue
  src/dispatch/static/dispatch/src/case/severity/Table.vue
  src/dispatch/static/dispatch/src/case/type/Table.vue
  src/dispatch/static/dispatch/src/data/source/dataFormat/Table.vue
  src/dispatch/static/dispatch/src/data/source/environment/Table.vue
  src/dispatch/static/dispatch/src/data/source/status/Table.vue
  src/dispatch/static/dispatch/src/data/source/transport/Table.vue
  src/dispatch/static/dispatch/src/data/source/type/Table.vue
  src/dispatch/static/dispatch/src/definition/Table.vue
  src/dispatch/static/dispatch/src/document/reference/ReferenceTable.vue
  src/dispatch/static/dispatch/src/document/runbook/RunbookTable.vue
  src/dispatch/static/dispatch/src/document/template/TemplateTable.vue
  src/dispatch/static/dispatch/src/incident_cost_type/Table.vue
  src/dispatch/static/dispatch/src/incident_priority/Table.vue
  src/dispatch/static/dispatch/src/incident_role/Table.vue
  src/dispatch/static/dispatch/src/incident_type/Table.vue
  src/dispatch/static/dispatch/src/individual/Table.vue
  src/dispatch/static/dispatch/src/notification/Table.vue
  src/dispatch/static/dispatch/src/plugin/Table.vue
  src/dispatch/static/dispatch/src/service/Table.vue
  src/dispatch/static/dispatch/src/tag/Table.vue
  src/dispatch/static/dispatch/src/tag_type/Table.vue
  src/dispatch/static/dispatch/src/team/Table.vue
  src/dispatch/static/dispatch/src/workflow/Table.vue
Labels: bug

#2511 Renames and reorders columns in the Feedback table
  src/dispatch/static/dispatch/src/feedback/Table.vue
Labels: enhancement

#2512 Cases Dashboard
  src/dispatch/static/dispatch/src/dashboard/case/CaseDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseEscalatedClosedAverageTimeCard.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseNewClosedAverageTimeCard.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseNewTriageAverageTimeCard.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseOverview.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseSeverityBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseTriageEscalatedAverageTimeCard.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseTypeBarChartCard.vue
Labels: enhancement

#2521 Disables other empty swaggers for container apps
  src/dispatch/main.py
Labels: enhancement

#2517 Improves incidents dashboard
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentCommandersLocationBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentCostBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentForecastCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentHeatmapCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentMeanResponseTimeCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentOverview.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentParticipantsLocationBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentParticipantsTeamBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentPriorityBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentReportersLocationBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentResolveTimeCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentTagsTreemapCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentTypeBarChartCard.vue
  src/dispatch/static/dispatch/src/data/source/IncidentsTab.vue
Labels: enhancement

#2526 Fixes docs and images paths
  docs/SUMMARY.md
  docs/admin-guide/administration/plugins/configuring-pagerduty.md
  docs/admin-guide/administration/plugins/configuring-slack.md
  docs/admin-guide/administration/templates.md
Labels: documentation

#2527 Fixes plugins readme links
  docs/admin-guide/administration/plugins/README.md
Labels: documentation

#2536 Adds case reporting support
  src/dispatch/case/views.py
  src/dispatch/static/dispatch/src/case/CaseSummaryTable.vue
  src/dispatch/static/dispatch/src/case/ReportForm.vue
  src/dispatch/static/dispatch/src/case/ReportReceiptCard.vue
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/case/Status.vue
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/router/config.js
Labels: enhancement

#2540 Enable case types in one project to be mapped to incident types in any project
  src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident_type/IncidentTypeSelect.vue
Labels: enhancement

#2545 Allows to load more tag types
  src/dispatch/static/dispatch/src/tag_type/TagTypeFilterCombobox.vue
  src/dispatch/static/dispatch/src/tag_type/TagTypeSelect.vue
Labels: enhancement

#2548 Allows to load more than five incident types
  src/dispatch/static/dispatch/src/case/type/CaseTypeCombobox.vue
  src/dispatch/static/dispatch/src/incident_type/IncidentTypeSelect.vue
Labels: enhancement

#2541 Enhancement/case escalation modal
  src/dispatch/case/flows.py
  src/dispatch/case/views.py
  src/dispatch/incident/flows.py
  src/dispatch/static/dispatch/src/case/BulkEditSheet.vue
  src/dispatch/static/dispatch/src/case/EditSheet.vue
  src/dispatch/static/dispatch/src/case/EscalateDialog.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/api.js
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/incident/ReportReceiptResources.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionForm.vue
  src/dispatch/static/dispatch/src/incident/store.js
Labels: enhancement

#2510 Runs every scheduled job in it's own thread.
  src/dispatch/scheduler.py
Labels: enhancement

#2559 Uses the 'simple' dictionary to provide better search consistancy
  src/dispatch/auth/models.py
  src/dispatch/case/severity/models.py
  src/dispatch/data/alert/models.py
  src/dispatch/data/query/models.py
  src/dispatch/data/source/data_format/models.py
  src/dispatch/data/source/environment/models.py
  src/dispatch/data/source/models.py
  src/dispatch/data/source/status/models.py
  src/dispatch/data/source/transport/models.py
  src/dispatch/data/source/type/models.py
  src/dispatch/definition/models.py
  src/dispatch/document/models.py
  src/dispatch/feedback/models.py
  src/dispatch/notification/models.py
  src/dispatch/service/models.py
  src/dispatch/tag_type/models.py
  src/dispatch/task/models.py
  src/dispatch/term/models.py
Labels: bug

#2546 Show related cases in the incident details tab
  src/dispatch/case/models.py
  src/dispatch/database/revisions/tenant/versions/2022-09-30_df200ca113f7.py
  src/dispatch/incident/models.py
  src/dispatch/incident/service.py
  src/dispatch/static/dispatch/src/case/CaseTypeCombobox.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/store.js
Labels: enhancement

#2564 Hides escalate option and button if case is already escalated or closed
  src/dispatch/static/dispatch/src/case/EditSheet.vue
  src/dispatch/static/dispatch/src/case/Table.vue
Labels: enhancement

#2563 Deprecates relationship between task and ticket
  src/dispatch/database/revisions/tenant/versions/2022-09-30_c1abb0cc40e5.py
  src/dispatch/static/dispatch/src/task/Table.vue
  src/dispatch/static/dispatch/src/task/TableExportDialog.vue
  src/dispatch/task/models.py
  src/dispatch/task/service.py
Labels: enhancement

#2565 Shortens total response hours widget label
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentOverview.vue
Labels: enhancement
