Repository Netflix/dispatch, pull requests merged in 2022-02, with the labels that each got.

#1944 Initializes data properties to avoid typerror exceptions in report submission card
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
Labels: bug

#1945 Upgrades Python dev requirements
  requirements-base.in
  requirements-base.txt
  requirements-dev.txt
Labels: dependencies

#1956 Reverts default value for business work hours in year back to 2080
  src/dispatch/project/models.py
Labels: bug

#1961 Adds bar charts for incident commanders and reporters location
  src/dispatch/incident/models.py
  src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/IncidentOverview.vue
  src/dispatch/static/dispatch/src/incident/IncidentCommandersLocationBarChartCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentParticipantsLocationBarChartCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentParticipantsTeamBarChartCard.vue
  src/dispatch/static/dispatch/src/incident/IncidentReportersLocationBarChartCard.vue
  src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
Labels: enhancement

#1963 Fixes incident pydantic models and hybrid properties
  src/dispatch/incident/models.py
  src/dispatch/static/dispatch/src/dashboard/DialogFilter.vue
  src/dispatch/static/dispatch/src/incident/IncidentParticipantsTeamBarChartCard.vue
Labels: bug

#1967 Creates a timeline event when the ticket is updated
  src/dispatch/incident/flows.py
Labels: enhancement

#1968 Adds IPython package to development requirements
  requirements-dev.in
  requirements-dev.txt
Labels: enhancement

#1962 Update our estimate of yearly business hours.
  src/dispatch/project/models.py
  src/dispatch/static/dispatch/src/project/NewEditSheet.vue
Labels: enhancement

#1973 Bumps tomli package version to resolve conflict
  requirements-base.txt
Labels: bug

#1974 Do not reactivate incident participant if incident status is closed
  src/dispatch/incident/flows.py
Labels: bug

#1975 Improves logging for ticket status changes and assign role flow
  src/dispatch/incident/flows.py
Labels: enhancement

#1981 Creates timeline event when incident document is opened or marked as read only
  src/dispatch/incident/flows.py
Labels: enhancement

#1980 Addresses a race condition on incident update
  src/dispatch/incident/flows.py
  src/dispatch/incident/views.py
  src/dispatch/plugins/dispatch_slack/actions.py
  src/dispatch/plugins/dispatch_slack/modals/incident/handlers.py
Labels: bug

#1992 Adds new field to capture incident resolution
  src/dispatch/database/revisions/tenant/versions/2022-02-15_3097592c0739.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/models.py
  src/dispatch/incident/service.py
  src/dispatch/plugins/dispatch_slack/modals/incident/enums.py
  src/dispatch/plugins/dispatch_slack/modals/incident/fields.py
  src/dispatch/plugins/dispatch_slack/modals/incident/handlers.py
  src/dispatch/plugins/dispatch_slack/modals/incident/views.py
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
  src/dispatch/static/dispatch/src/incident/store.js
Labels: enhancement

#2009 Fixing an issue with spacy library change.
  src/dispatch/nlp.py
Labels: bug

#2014 Fixes indentation when checking if commander needs to be paged on incident creation
  src/dispatch/incident/flows.py
Labels: bug
