Repository Netflix/dispatch, pull requests merged in 2022-08, with the labels that each got.

#2393 Reverts to using logger for logging incident cost updates to reduce number of events in the incident timeline
  src/dispatch/incident_cost/scheduled.py
Labels: enhancement

#2402 Re-organizes categories in the project settings panel
  src/dispatch/static/dispatch/src/document/template/TemplateNewEditSheet.vue
  src/dispatch/static/dispatch/src/router/config.js
Labels: enhancement

#2403 Adds support for deleting all external resources on case deletion
  src/dispatch/case/flows.py
  src/dispatch/case/views.py
  src/dispatch/group/flows.py
  src/dispatch/plugins/dispatch_google/drive/drive.py
  src/dispatch/plugins/dispatch_google/drive/plugin.py
  src/dispatch/plugins/dispatch_jira/plugin.py
  src/dispatch/static/dispatch/src/api.js
  src/dispatch/storage/flows.py
  src/dispatch/ticket/flows.py
Labels: enhancement

#2404 Fixes case bulk actions UI component
  src/dispatch/static/dispatch/src/case/BulkEditSheet.vue
  src/dispatch/static/dispatch/src/incident/BulkEditSheet.vue
Labels: bug

#2409 Adds project Flake8 config file
  .flake8
  src/dispatch/group/flows.py
  src/dispatch/storage/flows.py
  src/dispatch/ticket/flows.py
  tox.ini
Labels: skip-changelog

#2414 Case assignee gets set to current user if none is provided on case creation
  src/dispatch/case/service.py
  src/dispatch/case/views.py
Labels: enhancement

#2410 Copy over incident_costs, terms & duplicates before updating incident from Slack
  src/dispatch/plugins/dispatch_slack/modals/incident/handlers.py
Labels: bug

#2417 Adds support for mapping oncall services to case types
  src/dispatch/case/type/models.py
  src/dispatch/case/type/service.py
  src/dispatch/database/revisions/tenant/versions/2022-08-16_a27964951d4f.py
  src/dispatch/service/models.py
  src/dispatch/service/service.py
  src/dispatch/service/views.py
  src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/case/type/store.js
Labels: enhancement

#2418 Adds support for resolving the case assignee via an oncall plugin on case creation
  src/dispatch/case/service.py
  src/dispatch/service/flows.py
Labels: enhancement

#2420 Adds protections to prevent hitting char limits in SaaS integrations
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/strings.py
Labels: bug

#2421 Do not process events generated by Slackbot
  .flake8
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#2425 Implements the case creation triage, escalated, and closed flows
  src/dispatch/case/flows.py
Labels: enhancement

#2426 Runs tasks common between case status transition flows
  .flake8
  src/dispatch/case/flows.py
Labels: enhancement

#2427 Creates timeline events on case visibility, type, severity, priority, source and assignee changes
  src/dispatch/case/service.py
  src/dispatch/case/views.py
Labels: enhancement

#2428 Updates group membership on case assignee changes
  .flake8
  src/dispatch/case/flows.py
  src/dispatch/group/enums.py
  src/dispatch/group/flows.py
Labels: enhancement

#2419 slack_menu empty tag list fix; uvloop support.
  requirements-base.in
  requirements-base.txt
  src/dispatch/plugins/dispatch_slack/decorators.py
  src/dispatch/plugins/dispatch_slack/menus.py
  src/dispatch/plugins/dispatch_slack/views.py
Labels: bug

#2429 Replaces composite primary key for a new primary key in all assoc objects in the case data model
  src/dispatch/case/models.py
  src/dispatch/database/revisions/tenant/versions/2022-08-18_86ec96cd14f8.py
Labels: bug

#2430 Wrap gmail.send in try/except due to tenacity.RetryError
  src/dispatch/evergreen/scheduled.py
  src/dispatch/feedback/messaging.py
  src/dispatch/incident/messaging.py
  src/dispatch/notification/service.py
  src/dispatch/plugins/dispatch_slack/config.py
  src/dispatch/report/messaging.py
  src/dispatch/task/flows.py
Labels: bug

#2440 Always upper log_level before logging config
  src/dispatch/logging.py
Labels: enhancement

#2443 Fixes doc creation issue if template is None
  src/dispatch/incident/flows.py
  src/dispatch/plugins/dispatch_google/drive/drive.py
Labels: bug

#2452 Return after deleting case and case resources if there's a failure during case creation
  src/dispatch/case/flows.py
Labels: bug

#2453 Fixes colors for case priorities
  src/dispatch/static/dispatch/src/case/priority/CasePriority.vue
Labels: bug

#2454 Fixes case severity colors
  src/dispatch/static/dispatch/src/case/severity/CaseSeverity.vue
Labels: bug

#2455 Fixes issue during the creation of incident collaboration documents
  src/dispatch/incident/flows.py
Labels: bug

#2456 Adds initial version of dashboard for cases
  src/dispatch/static/dispatch/src/components/DateWindowInput.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseOverview.vue
  src/dispatch/static/dispatch/src/dashboard/data/DataDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/data/DataOverview.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentDrillDownTable.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentOverview.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentsDrillDownSheet.vue
  src/dispatch/static/dispatch/src/dashboard/task/TaskDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/task/TaskOverview.vue
  src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/router/config.js
Labels: enhancement

#2457 Removes trailing comma
  src/dispatch/incident/flows.py
Labels: bug

#2458 Truncates incident description and resolution when they're too long
  src/dispatch/incident/messaging.py
Labels: enhancement

#2469 Sets a default resolution if not provided on case or incident creation
  src/dispatch/case/models.py
  src/dispatch/database/revisions/tenant/versions/2022-08-29_479024506e05.py
  src/dispatch/incident/models.py
  src/dispatch/incident_type/service.py
  src/dispatch/messaging/strings.py
  src/dispatch/project/service.py
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
Labels: bug

#2470 Fixes case default resolution string
  src/dispatch/messaging/strings.py
Labels: bug

#2472 Sets response model to None for all delete endpoints to address breaking changes in FastAPI v0.80.0
  src/dispatch/case/views.py
  src/dispatch/data/alert/views.py
  src/dispatch/data/query/views.py
  src/dispatch/data/source/data_format/views.py
  src/dispatch/data/source/environment/views.py
  src/dispatch/data/source/status/views.py
  src/dispatch/data/source/transport/views.py
  src/dispatch/data/source/type/views.py
  src/dispatch/data/source/views.py
  src/dispatch/definition/views.py
  src/dispatch/document/views.py
  src/dispatch/feedback/views.py
  src/dispatch/incident/views.py
  src/dispatch/incident_cost/views.py
  src/dispatch/incident_cost_type/views.py
  src/dispatch/individual/views.py
  src/dispatch/notification/views.py
  src/dispatch/plugin/views.py
  src/dispatch/project/views.py
  src/dispatch/search_filter/views.py
  src/dispatch/service/views.py
  src/dispatch/tag/views.py
  src/dispatch/tag_type/views.py
  src/dispatch/task/views.py
  src/dispatch/team/views.py
  src/dispatch/term/views.py
  src/dispatch/workflow/views.py
Labels: bug
