Repository Netflix/dispatch, pull requests merged in 2022-10, with the labels that each got.

#2568 Set the triage at time when case is escalated via UI modal
  src/dispatch/case/flows.py
Labels: bug

#2569 Add hint to using CLI to install plugins
  docs/admin-guide/administration/cli.md
  docs/admin-guide/administration/plugins/README.md
Labels: documentation

#2576 Fixes null values in case reporting form and allows for url updating and copying URL to clipboard
  src/dispatch/static/dispatch/src/case/ReportForm.vue
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/incident/ReportForm.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
Labels: bug

#2574 Minor fixes to slack config
  docs/admin-guide/administration/plugins/configuring-slack.md
Labels: documentation

#2578 add small descriptions of what Cases are
  docs/admin-guide/administration/case/README.md
  docs/user-guide/case.md
Labels: documentation

#2589 Allows for tasks to be specifically excluded (useful for scheduling signals)
  src/dispatch/cli.py
Labels: enhancement

#2613 Disables dropping search triggers and functions
  src/dispatch/search/fulltext/__init__.py
Labels: bug

#2618 Disables escalate option and button when case is escalated or closed
  src/dispatch/static/dispatch/src/case/Table.vue
Labels: enhancement

#2619 Prefills mapped incident type in case type in escalate case form
  src/dispatch/static/dispatch/src/case/EscalateDialog.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionForm.vue
Labels: enhancement

#2625 Adds support for a new incident observer participant role
  src/dispatch/database/revisions/tenant/versions/2022-10-26_4b65941d065a.py
  src/dispatch/incident/flows.py
  src/dispatch/incident_cost/service.py
  src/dispatch/participant/models.py
  src/dispatch/participant_role/enums.py
  src/dispatch/participant_role/flows.py
  src/dispatch/participant_role/models.py
  src/dispatch/plugins/dispatch_slack/actions.py
  src/dispatch/plugins/dispatch_slack/events.py
Labels: enhancement

#2633 Improvements to participant role's activity
  src/dispatch/incident_cost/service.py
  src/dispatch/participant_role/models.py
  src/dispatch/plugins/dispatch_slack/events.py
Labels: enhancement

#2634 Announce when participants are assigned the observer role in the incident channel
  src/dispatch/incident/flows.py
  src/dispatch/plugins/dispatch_slack/actions.py
Labels: enhancement

#2636 Adds section for commander paged in the incident report receipt card
  src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue
Labels: enhancement

#2587 Adds support for visibility in SearchFilter
  src/dispatch/plugins/dispatch_slack/dialogs.py
  src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue
  src/dispatch/static/dispatch/src/search/store.js
  src/dispatch/static/dispatch/src/search/utils.js
Labels: enhancement

#2635 Sorted PD Schedule names
  src/dispatch/service/service.py
Labels: bug

#2550 Enhancement/case management workflows
  src/dispatch/case/models.py
  src/dispatch/cli.py
  src/dispatch/config.py
  src/dispatch/database/revisions/tenant/versions/2022-09-23_cfde1bca6a6e.py
  src/dispatch/database/revisions/tenant/versions/2022-10-04_3a5e776ddce4.py
  src/dispatch/plugins/dispatch_slack/modals/workflow/handlers.py
  src/dispatch/plugins/generic_workflow/plugin.py
  src/dispatch/static/dispatch/src/case/EditSheet.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/dashboard/case/CaseOverview.vue
  src/dispatch/static/dispatch/src/incident/EditSheet.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/static/dispatch/src/workflow/RunModal.vue
  src/dispatch/static/dispatch/src/workflow/WorkflowInstanceDetailMenu.vue
  src/dispatch/static/dispatch/src/workflow/WorkflowInstanceTab.vue
  src/dispatch/static/dispatch/src/workflow/WorkflowSelect.vue
  src/dispatch/static/dispatch/src/workflow/api.js
  src/dispatch/static/dispatch/src/workflow/store.js
  src/dispatch/workflow/models.py
  src/dispatch/workflow/scheduled.py
  src/dispatch/workflow/service.py
  src/dispatch/workflow/views.py
  tests/workflow/test_workflow_service.py
Labels: enhancement

#2631 Enhancement/signal deduplication
  .gitignore
  setup.py
  src/dispatch/__init__.py
  src/dispatch/api.py
  src/dispatch/case/flows.py
  src/dispatch/case/models.py
  src/dispatch/cli.py
  src/dispatch/database/revisions/tenant/versions/2022-10-27_01aa49ca0470.py
  src/dispatch/plugins/dispatch_google/sheets/__init__.py
  src/dispatch/plugins/dispatch_google/sheets/_version.py
  src/dispatch/plugins/dispatch_google/sheets/plugin.py
  src/dispatch/plugins/dispatch_uptycs/__init__.py
  src/dispatch/plugins/dispatch_uptycs/_version.py
  src/dispatch/plugins/dispatch_uptycs/config.py
  src/dispatch/plugins/dispatch_uptycs/plugin.py
  src/dispatch/signal/duplication_rule/__init__.py
  src/dispatch/signal/duplication_rule/models.py
  src/dispatch/signal/duplication_rule/service.py
  src/dispatch/signal/duplication_rule/views.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/scheduled.py
  src/dispatch/signal/service.py
  src/dispatch/signal/suppression_rule/__init__.py
  src/dispatch/signal/suppression_rule/models.py
  src/dispatch/signal/suppression_rule/service.py
  src/dispatch/signal/suppression_rule/views.py
  src/dispatch/signal/views.py
  src/dispatch/static/dispatch/src/case/CasePopover.vue
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/signal/DeleteDialog.vue
  src/dispatch/static/dispatch/src/signal/DuplicationRule.vue
  src/dispatch/static/dispatch/src/signal/NewEditSheet.vue
  src/dispatch/static/dispatch/src/signal/RawSignalViewer.vue
  src/dispatch/static/dispatch/src/signal/SignalFilterCombobox.vue
  src/dispatch/static/dispatch/src/signal/SignalPopover.vue
  src/dispatch/static/dispatch/src/signal/SuppressionRule.vue
  src/dispatch/static/dispatch/src/signal/Table.vue
  src/dispatch/static/dispatch/src/signal/TableExportDialog.vue
  src/dispatch/static/dispatch/src/signal/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
  src/dispatch/static/dispatch/src/signal/api.js
  src/dispatch/static/dispatch/src/signal/duplication_rule/NewEditSheet.vue
  src/dispatch/static/dispatch/src/signal/duplication_rule/Table.vue
  src/dispatch/static/dispatch/src/signal/duplication_rule/api.js
  src/dispatch/static/dispatch/src/signal/duplication_rule/store.js
  src/dispatch/static/dispatch/src/signal/store.js
  src/dispatch/static/dispatch/src/signal/suppression_rule/NewEditSheet.vue
  src/dispatch/static/dispatch/src/signal/suppression_rule/Table.vue
  src/dispatch/static/dispatch/src/signal/suppression_rule/api.js
  src/dispatch/static/dispatch/src/signal/suppression_rule/store.js
  src/dispatch/static/dispatch/src/store.js
Labels: enhancement

#2637 Enhancement/build with vite
  src/dispatch/cli.py
  src/dispatch/static/dispatch/babel.config.js
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/static/dispatch/index.html
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/postcss.config.js
  src/dispatch/static/dispatch/src/api.js
  src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js
  src/dispatch/static/dispatch/src/case/ReportForm.vue
  src/dispatch/static/dispatch/src/case/Status.vue
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
  src/dispatch/static/dispatch/src/components/Combobox.vue
  src/dispatch/static/dispatch/src/components/layouts/BasicLayout.vue
  src/dispatch/static/dispatch/src/components/layouts/DashboardLayout.vue
  src/dispatch/static/dispatch/src/components/layouts/DefaultLayout.vue
  src/dispatch/static/dispatch/src/components/layouts/index.js
  src/dispatch/static/dispatch/src/incident/ReportForm.vue
  src/dispatch/static/dispatch/src/incident/Status.vue
  src/dispatch/static/dispatch/src/main.js
  src/dispatch/static/dispatch/src/plugin/NewEditSheet.vue
  src/dispatch/static/dispatch/src/registerServiceWorker.js
  src/dispatch/static/dispatch/src/router/index.js
  src/dispatch/static/dispatch/src/store.js
  src/dispatch/static/dispatch/src/util/index.js
  src/dispatch/static/dispatch/src/workflow/NewEditSheet.vue
  src/dispatch/static/dispatch/test/e2e/nightwatch.conf.js
  src/dispatch/static/dispatch/test/e2e/runner.js
  src/dispatch/static/dispatch/vite.config.js
  src/dispatch/static/dispatch/vue.config.js
Labels: enhancement

#2640 Fixing import and database revision branches
  src/dispatch/case/models.py
  src/dispatch/database/revisions/tenant/versions/2022-10-31_34aeedc9d09a.py
Labels: bug

#2641 Always ensure there is a fingerprint for each signal
  src/dispatch/database/revisions/tenant/versions/2022-10-31_34aeedc9d09a.py
  src/dispatch/signal/service.py
  src/dispatch/static/dispatch/src/components/Combobox.vue
Labels: bug

#2642 Bugfix/signal fingerprint
  .vscode/settings.json
  src/dispatch/database/revisions/tenant/versions/2022-10-31_34aeedc9d09a.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/service.py
Labels: bug

#2643 Adds a way to view signal instances associated with a case.
  src/dispatch/case/models.py
  src/dispatch/static/dispatch/src/case/EditSheet.vue
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/signal/SignalInstanceTab.vue
Labels: enhancement
