Repository Netflix/dispatch, pull requests merged in 2023-03, with the labels that each got.

#3035 Creates a new plugin for Duo that provides on-demand MFA across Dispatch
  requirements-base.in
  requirements-base.txt
  setup.py
  src/dispatch/plugins/bases/__init__.py
  src/dispatch/plugins/bases/auth_mfa.py
  src/dispatch/plugins/dispatch_duo/__init__.py
  src/dispatch/plugins/dispatch_duo/_version.py
  src/dispatch/plugins/dispatch_duo/config.py
  src/dispatch/plugins/dispatch_duo/plugin.py
  src/dispatch/plugins/dispatch_duo/service.py
Labels: enhancement

#3008 Add Entity Type create dialog and Entity Type playground editor
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/entity/EntitiesTab.vue
  src/dispatch/static/dispatch/src/entity/EntityCard.vue
  src/dispatch/static/dispatch/src/entity/api.js
  src/dispatch/static/dispatch/src/entity/store.js
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialog.vue
  src/dispatch/static/dispatch/src/entity_type/EntityTypeFilterCombobox.vue
  src/dispatch/static/dispatch/src/entity_type/Table.vue
  src/dispatch/static/dispatch/src/entity_type/playground/PlaygroundTextBox.vue
  src/dispatch/static/dispatch/src/entity_type/playground/store.js
  src/dispatch/static/dispatch/src/entity_type/store.js
  src/dispatch/static/dispatch/src/entity_type/utils.js
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
  src/dispatch/static/dispatch/src/signal/SignalDefinitionCombobox.vue
  src/dispatch/static/dispatch/src/signal/filter/SignalFilterCreateDialog.vue
  src/dispatch/static/dispatch/src/store.js
  tests/entity/test_entity_service.py
  tests/factories.py
Labels: enhancement, UI/UX, javascript

#3042 Adds the ability for signal definitions to be disabled
  src/dispatch/database/revisions/tenant/versions/2023-03-02_5955ed5f76b4.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
  src/dispatch/static/dispatch/src/signal/store.js
Labels: enhancement

#3043 Adds protection to prevent the creation of duplicate tasks
  src/dispatch/database/revisions/tenant/versions/2023-03-02_65db2acae3ea.py
  src/dispatch/task/models.py
  src/dispatch/task/service.py
Labels: bug

#3030 Support incident date in storage
  src/dispatch/incident/flows.py
Labels: enhancement

#3044 Fixes multiple head revisions are present issue
  src/dispatch/database/revisions/tenant/versions/2023-03-02_65db2acae3ea.py
Labels: bug

#3045 Fixes an issue with the generation of signal API Documentation.
  src/dispatch/api.py
Labels: bug

#3046 Fixes pagination
  src/dispatch/static/dispatch/src/signal/Table.vue
Labels: bug

#3047 Fixes issue with global search
  src/dispatch/enums.py
Labels: bug

#3048 Ensures all case and incident priorities and severities are returned for rendering dashboard charts
  src/dispatch/incident/severity/views.py
  src/dispatch/static/dispatch/src/dashboard/case/CaseSeverityBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentPriorityBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentSeverityBarChartCard.vue
Labels: bug

#3019 Added visibility to welcome message
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/strings.py
Labels: enhancement

#3051 Enhancement/searchable variant
  src/dispatch/database/revisions/tenant/versions/2023-03-03_7ddae3ba7822.py
  src/dispatch/signal/models.py
Labels: enhancement

#3052 Improves the signal filter UI
  src/dispatch/static/dispatch/src/signal/filter/SignalFilterCreateDialog.vue
Labels: enhancement

#3050 Add a new slack slash command `/dispatch-list-signals` and allow creation of Snooze filter w/ MFA
  docs/admin-guide/administration/plugins/configuring-slack.md
  src/dispatch/entity/service.py
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/config.py
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/search/utils.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
Labels: enhancement

#3053 Converts timestamps to strings before passing them to the document plugin
  src/dispatch/incident/flows.py
Labels: bug

#2966 Feature/markdown in incident desc
  requirements-base.in
  requirements-base.txt
  requirements-dev.txt
  src/dispatch/config.py
  src/dispatch/messaging/email/filters.py
  src/dispatch/messaging/strings.py
Labels: enhancement

#3058 Fixing playwrite e2e tests
  .github/workflows/playwright.yml
Labels: bug

#3059 Enhancement/signal definition UI
  src/dispatch/database/service.py
  src/dispatch/signal/flows.py
  src/dispatch/static/dispatch/src/signal/Table.vue
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
  src/dispatch/static/dispatch/src/signal/store.js
Labels: bug

#3060 Fixes issues with case messaging
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#3061 Correctly pass response data back after saving entity type to display as chip in combobox
  src/dispatch/static/dispatch/src/entity_type/store.js
Labels: bug

#3067 Fix bug where signal sheet save button is disabled on entity dialog open
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialog.vue
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
Labels: bug

#3069 wait for selected signal data for rendering signal tab
  src/dispatch/static/dispatch/src/case/EditSheet.vue
Labels: bug

#3062 Adds signal entities to case notifications and support for viewing raw signal data.
  src/dispatch/entity_type/models.py
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/signal/models.py
  src/dispatch/signal/service.py
  src/dispatch/static/dispatch/src/signal/SignalInstanceTab.vue
  src/dispatch/static/dispatch/src/signal/filter/SignalFilterCreateDialog.vue
Labels: enhancement

#3064 CLI drop database modified to address in case the database doesn't exist
  src/dispatch/cli.py
Labels: enhancement

#3070 Fixes an incorrect enum
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3071 Resolves conversation is None exception
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#3072 Bugfix/signal instance raw
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/signal/service.py
Labels: bug

#3075 Removing all references to raw data
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  tests/signal/test_signal_service.py
Labels: bug

#3076 Bugfix/removing raw data
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
Labels: bug

#3074 check for entity types when we create a signal
  src/dispatch/signal/models.py
  src/dispatch/static/dispatch/src/signal/store.js
Labels: bug

#3073 Add snooze button to signal instance message in Slack plugin and add Case/Signal subject enum
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/models.py
  src/dispatch/signal/models.py
Labels: enhancement

#3063 Refactors incident flows and adds more resource-based flow modules
  src/dispatch/conference/flows.py
  src/dispatch/conference/service.py
  src/dispatch/conversation/flows.py
  src/dispatch/document/flows.py
  src/dispatch/group/flows.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/views.py
  src/dispatch/participant/flows.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/ticket/flows.py
Labels: enhancement, techdebt

#3077 Adds testing to signal instance creation
  src/dispatch/document/flows.py
  src/dispatch/signal/flows.py
  tests/conftest.py
  tests/factories.py
  tests/signal/test_signal_flow.py
Labels: bug

#3082 Adds ondelete cascades to foreign keys in the participant and case tables to allow project deletion
  src/dispatch/case/models.py
  src/dispatch/database/revisions/tenant/versions/2023-03-08_1d21b28bc553.py
  src/dispatch/database/revisions/tenant/versions/2023-03-08_1ded4c2a7801.py
  src/dispatch/participant/models.py
Labels: bug

#3081 Add documentation for Duo plugin
  docs/SUMMARY.md
  docs/admin-guide/administration/plugins/configuring-duo.md
Labels: documentation, enhancement

#3084 Adds support for deleting external incident-related resources
  src/dispatch/case/flows.py
  src/dispatch/case/views.py
  src/dispatch/conversation/flows.py
  src/dispatch/group/flows.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/views.py
  src/dispatch/plugins/dispatch_core/plugin.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/static/dispatch/src/case/DeleteDialog.vue
  src/dispatch/static/dispatch/src/incident/DeleteDialog.vue
  src/dispatch/storage/flows.py
  src/dispatch/ticket/flows.py
Labels: enhancement

#3088 remove entities from signal instance table
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
Labels: bug

#3091 Adding tags and entitity types to signal defintitions.
  src/dispatch/signal/models.py
Labels: enhancement

#3090 Adding case resolution reason
  src/dispatch/case/enums.py
  src/dispatch/case/models.py
  src/dispatch/database/revisions/tenant/versions/2023-03-09_ec78c132ab93.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/store.js
  tests/factories.py
Labels: enhancement

#3092 Enhancement/missing tag search
  src/dispatch/database/revisions/tenant/versions/2023-03-09_7db13bf5c5d7.py
  src/dispatch/tag/models.py
Labels: enhancement

#3097 Creating a linear revision history
  src/dispatch/database/revisions/tenant/versions/2023-03-09_7db13bf5c5d7.py
Labels: bug

#3083 Update signal instance message
  src/dispatch/case/flows.py
  src/dispatch/entity/service.py
  src/dispatch/entity/views.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: enhancement

#3089 update action context middleware to account for other data in private_metadata
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/models.py
Labels: bug

#3098 Fixing frontend typo
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
Labels: bug

#3099 Remove unneeded arg
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#3100 only show Correlation context element if there are entities in message
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#3103 Adding the resolution reason to the resolve modal and adding a label
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#3104 FormData argument is redundant in _create_snooze_filter function
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: enhancement, techdebt

#3105 Minor fixes to case participant slack plugin
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3113 Providing better user input on long signals.
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3106 Add case popover/dialog to entity tab correlation card
  src/dispatch/static/dispatch/src/case/CasePopover.vue
  src/dispatch/static/dispatch/src/case/CaseTab.vue
  src/dispatch/static/dispatch/src/entity/EntityCard.vue
  src/dispatch/static/dispatch/src/entity/store.js
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialog.vue
  src/dispatch/static/dispatch/src/search/utils.js
  src/dispatch/static/dispatch/src/store.js
Labels: enhancement, UI/UX, javascript

#3119 name_or_raise for workflow doesn't require project_id
  src/dispatch/database/revisions/tenant/versions/2023-03-14_b48b245f9c4c.py
  src/dispatch/signal/service.py
  src/dispatch/workflow/service.py
Labels: bug

#3120 Upgrade Python to `3.11.2` in `Dockerfile` and `setup.py`
  .devcontainer/Dockerfile
  docker/Dockerfile
  setup.py
Labels: bug

#3121 Fixes issue with timeline event Slack-based reaction by using a listerner matcher
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#3124 Adds event handler to ignore not configured Slack reactions
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: enhancement

#3125 Adds util function to deslug and capitalize a resource type string and fixes name for incident review document Slack bookmark name
  src/dispatch/conversation/flows.py
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/utils.py
Labels: bug

#3127 Fixes call to update external ticket on incident role change
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#3126 move components.d.ts to .gitignore
  .gitignore
Labels: enhancement

#3115 Improve scheduler shutdown procedure during deployments.
  src/dispatch/cli.py
  src/dispatch/scheduler.py
Labels: enhancement

#3132 Returns empty list if Google group has no members
  src/dispatch/plugins/dispatch_google/groups/plugin.py
Labels: bug

#3131 Enhancement/signal api
  src/dispatch/case/flows.py
  src/dispatch/case/service.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
  tests/signal/test_signal_service.py
Labels: enhancement

#3140 Fixes an issue with select missing project scope
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
Labels: bug

#3149 add support for errors in threads
  src/dispatch/plugins/dispatch_slack/bolt.py
Labels: bug

#3151 improve no entity error message and return early after modal open
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug, enhancement

#3150 Fixing an issue with case group add
  src/dispatch/case/flows.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#3157 Minor improvements to case and signal slack messages
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#3159 Adds plugin for OpenAI's Generative Artificial Intelligence platform
  setup.py
  src/dispatch/plugins/bases/__init__.py
  src/dispatch/plugins/bases/artificial_intelligence.py
  src/dispatch/plugins/dispatch_openai/__init__.py
  src/dispatch/plugins/dispatch_openai/_version.py
  src/dispatch/plugins/dispatch_openai/config.py
  src/dispatch/plugins/dispatch_openai/plugin.py
Labels: enhancement

#3160 Adds openai Python requirement and updates others
  requirements-base.in
  requirements-base.txt
Labels: enhancement

#3161 Updates more Python requirements
  requirements-base.in
  requirements-base.txt
  requirements-dev.in
  requirements-dev.txt
Labels: enhancement

#3162 add .pre-commit.config.yaml for `black`, `ruff`, and `pytest`
  .pre-commit-config.yaml
  requirements-dev.in
  requirements-dev.txt
Labels: enhancement

#3167 Adds email individual search
  src/dispatch/database/revisions/tenant/versions/2023-03-27_d1b5ed66d83d.py
  src/dispatch/individual/models.py
Labels: bug

#3172 Ensure case assignee always gets looped in
  src/dispatch/case/flows.py
Labels: bug

#3173 Pins cryptography and bumps some package versions
  requirements-base.in
  requirements-base.txt
Labels: enhancement

#3176 Fixes missing flow name
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3177 Fixes bug in oncall service paging via Slack command
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/static/dispatch/components.d.ts
Labels: bug

#3178 Adds missing project id
  src/dispatch/case/flows.py
Labels: bug

#3183 Fixes error with creating signal definition workflows
  .gitignore
  src/dispatch/static/dispatch/src/signal/store.js
Labels: bug

#3184 Fixing an issue with case creation
  src/dispatch/signal/flows.py
Labels: bug

#3185 Fixing publish action
  .github/workflows/deploy-docs.yml
Labels: bug

#3186 Fixing publish path
  .github/workflows/deploy-docs.yml
Labels: bug

#3190 Fixing an issue with case creation
  src/dispatch/case/flows.py
Labels: bug

#3187 Fix documentation broken links
  docs/docs/administration/installation.mdx
Labels: documentation

#3196 Docs/improvements
  docs/docs/administration/api.mdx
  docs/docs/administration/case/case-priority.mdx
  docs/docs/administration/case/case-severity.mdx
  docs/docs/administration/case/case-type.mdx
  docs/docs/administration/case/index.mdx
  docs/docs/administration/cli.mdx
  docs/docs/administration/contact/index.mdx
  docs/docs/administration/contact/individual.mdx
  docs/docs/administration/contact/introduction.mdx
  docs/docs/administration/contact/service.mdx
  docs/docs/administration/contact/team.mdx
  docs/docs/administration/data/index.mdx
  docs/docs/administration/incident/incident-cost-type.mdx
  docs/docs/administration/incident/incident-priority.mdx
  docs/docs/administration/incident/incident-type.mdx
  docs/docs/administration/incident/index.mdx
  docs/docs/administration/incident/notification.mdx
  docs/docs/administration/incident/workflow.mdx
  docs/docs/administration/index.mdx
  docs/docs/administration/knowledge/index.mdx
  docs/docs/administration/knowledge/runbooks.mdx
  docs/docs/administration/knowledge/tag-type.mdx
  docs/docs/administration/knowledge/tag.mdx
  docs/docs/administration/plugins/configuring-pagerduty.mdx
  docs/docs/administration/plugins/configuring-slack.mdx
  docs/docs/administration/plugins/index.mdx
  docs/docs/administration/project.mdx
  docs/docs/administration/server.mdx
  docs/docs/administration/templates.mdx
  docs/docs/administration/user.mdx
  docs/docs/contributing/plugins/index.mdx
  docs/docs/user-guide/dashboard.mdx
  docs/docs/user-guide/feedback.mdx
  docs/docs/user-guide/incident-commander.mdx
  docs/docs/user-guide/incident-participant.mdx
  docs/docs/user-guide/incident.mdx
  docs/docs/user-guide/index.mdx
  docs/docs/user-guide/tasks.mdx
  docs/docusaurus.config.js
  docs/src/css/custom.css
Labels: documentation

#3198 generate a unique monaco uri using a uuid for entity type playground
  src/dispatch/static/dispatch/src/entity_type/playground/PlaygroundTextBox.vue
Labels: bug

#3192 Use Annotated types for FastAPI `db_session`, `get_current_user` parameter
  src/dispatch/auth/permissions.py
  src/dispatch/auth/service.py
  src/dispatch/auth/views.py
  src/dispatch/case/priority/views.py
  src/dispatch/case/severity/views.py
  src/dispatch/case/type/views.py
  src/dispatch/case/views.py
  src/dispatch/data/alert/views.py
  src/dispatch/data/query/views.py
  src/dispatch/data/source/data_format/views.py
  src/dispatch/data/source/environment/views.py
  src/dispatch/data/source/status/views.py
  src/dispatch/data/source/transport/views.py
  src/dispatch/data/source/type/views.py
  src/dispatch/data/source/views.py
  src/dispatch/database/core.py
  src/dispatch/database/service.py
  src/dispatch/definition/views.py
  src/dispatch/document/views.py
  src/dispatch/entity/views.py
  src/dispatch/entity_type/views.py
  src/dispatch/feedback/views.py
  src/dispatch/incident/priority/views.py
  src/dispatch/incident/severity/views.py
  src/dispatch/incident/type/views.py
  src/dispatch/incident/views.py
  src/dispatch/incident_cost/views.py
  src/dispatch/incident_cost_type/views.py
  src/dispatch/incident_role/views.py
  src/dispatch/individual/views.py
  src/dispatch/notification/views.py
  src/dispatch/organization/views.py
  src/dispatch/plugin/views.py
  src/dispatch/project/views.py
  src/dispatch/search_filter/views.py
  src/dispatch/service/views.py
  src/dispatch/signal/views.py
  src/dispatch/tag/views.py
  src/dispatch/tag_type/views.py
  src/dispatch/task/views.py
  src/dispatch/team/views.py
  src/dispatch/term/views.py
  src/dispatch/workflow/views.py
Labels: enhancement

#3201 Fixes an issue where filter action was not being saved
  src/dispatch/signal/service.py
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialog.vue
  src/dispatch/static/dispatch/src/entity_type/playground/PlaygroundTextBox.vue
  src/dispatch/static/dispatch/src/entity_type/store.js
Labels: bug

#3202 remove debug log statements from playgroundeditor
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialog.vue
  src/dispatch/static/dispatch/src/entity_type/playground/PlaygroundTextBox.vue
Labels: bug
