Repository Netflix/dispatch, pull requests merged in 2023-08, with the labels that each got.

#3648 Missing db_session
  src/dispatch/signal/service.py
Labels: bug

#3647 Moving avatar URL template to configuration file
  src/dispatch/static/dispatch/src/auth/store.js
Labels: bug

#3652 Bugfix/conversation UI
  src/dispatch/static/dispatch/src/case/ReportReceiptCard.vue
  src/dispatch/static/dispatch/src/case/ResourcesTab.vue
  src/dispatch/static/dispatch/src/case/store.js
Labels: bug

#3653 Adds ability to expand case attributes via the api
  src/dispatch/case/models.py
  src/dispatch/case/views.py
Labels: enhancement

#3656 Allows the signal api to process an external id
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
Labels: bug

#3661 Fix banned threads by checking for case_id is not null in middleware
  src/dispatch/conversation/service.py
Labels: bug

#3662 Use the correct filter
  src/dispatch/signal/service.py
Labels: bug

#3663 disambiguates between incident threads, case threads, and incident messages
  src/dispatch/conversation/service.py
Labels: bug

#3655 Adding ability to report incident from shortcut
  src/dispatch/plugins/dispatch_slack/incident/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: enhancement

#3669 Putting a cap on the number of threads a scheduler can create
  src/dispatch/scheduler.py
Labels: bug

#3664 Add ability to turn off daily reports
  data/dispatch-sample-data.dump
  src/dispatch/database/revisions/tenant/versions/2023-08-04_6b98c28edd86.py
  src/dispatch/incident/scheduled.py
  src/dispatch/project/models.py
  src/dispatch/static/dispatch/src/notification/Table.vue
  src/dispatch/static/dispatch/src/notification/store.js
Labels: enhancement

#3554 Autofill the tactical report's action section with opened tasks
  src/dispatch/incident/models.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/static/dispatch/src/incident/store.js
Labels: enhancement

#3605 Support for PagerDuty EU
  src/dispatch/plugins/dispatch_pagerduty/plugin.py
Labels: enhancement

#3679 Adds support for opening access and marking incident review documents as readonly
  src/dispatch/document/flows.py
  src/dispatch/incident/flows.py
Labels: enhancement

#3680 Add the Dispatch UI bookmark to incident channel
  src/dispatch/conversation/flows.py
Labels: enhancement

#3681 Fixes an issue where some filter fields did not have the correct model set
  src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue
Labels: bug

#3691 Enhancement/adding case resolution to thread
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#3695 Removes error message for malformed JWT tokens
  src/dispatch/plugins/dispatch_core/plugin.py
Labels: bug

#3690 Checking for manual snooze on report reminder before sending regularly scheduled one
  src/dispatch/report/scheduled.py
Labels: bug

#3698 Adds missing pagination-related fields to users endpoint
  src/dispatch/auth/views.py
  src/dispatch/static/dispatch/src/organization/OrganizationMemberTable.vue
Labels: bug

#3704 Fixes issue with adding a participant to an incident conversation from an escalated case
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3705 Do not add the incident's tactical email as a member of the case storage if it doesn't exist
  src/dispatch/case/flows.py
Labels: bug

#3706 Fixes issue with case escalation dialog
  src/dispatch/static/dispatch/src/case/EscalateDialog.vue
Labels: bug

#3707 Checks if the incident tactical group exists before adding it to the case storage
  src/dispatch/case/flows.py
Labels: enhancement

#3195 Adds support for collecting oncall service-related health metrics
  src/dispatch/__init__.py
  src/dispatch/api.py
  src/dispatch/cli.py
  src/dispatch/conversation/enums.py
  src/dispatch/database/revisions/tenant/versions/2023-08-10_74d279f6e4f6.py
  src/dispatch/database/revisions/tenant/versions/2023-08-11_4e57f5b1f3f3.py
  src/dispatch/database/service.py
  src/dispatch/feedback/incident/__init__.py
  src/dispatch/feedback/incident/enums.py
  src/dispatch/feedback/incident/messaging.py
  src/dispatch/feedback/incident/models.py
  src/dispatch/feedback/incident/scheduled.py
  src/dispatch/feedback/incident/service.py
  src/dispatch/feedback/incident/views.py
  src/dispatch/feedback/service/__init__.py
  src/dispatch/feedback/service/enums.py
  src/dispatch/feedback/service/messaging.py
  src/dispatch/feedback/service/models.py
  src/dispatch/feedback/service/scheduled.py
  src/dispatch/feedback/service/service.py
  src/dispatch/incident_role/service.py
  src/dispatch/messaging/strings.py
  src/dispatch/models.py
  src/dispatch/plugins/dispatch_pagerduty/plugin.py
  src/dispatch/plugins/dispatch_pagerduty/service.py
  src/dispatch/plugins/dispatch_slack/feedback/enums.py
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
  src/dispatch/service/models.py
  src/dispatch/service/service.py
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/service/List.vue
  src/dispatch/static/dispatch/src/service/NewEditSheet.vue
  src/dispatch/static/dispatch/src/service/Table.vue
  src/dispatch/static/dispatch/src/service/store.js
  tests/factories.py
  tests/feedback/test_feedback_service.py
Labels: feature

#3699 Allows for filtering by participant and incident commander
  src/dispatch/database/service.py
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/store.js
Labels: enhancement

#3713 Replacing direct value access with getter
  src/dispatch/database/service.py
Labels: bug

#3714 Renames function and adds two more functions to AI base plugin
  src/dispatch/plugins/bases/artificial_intelligence.py
  src/dispatch/plugins/dispatch_openai/plugin.py
Labels: enhancement

#3717 Upgrades Python dependencies
  requirements-base.in
  requirements-base.txt
  requirements-dev.txt
Labels: enhancement

#3718 No need to retry for certain Slack errors
  src/dispatch/plugins/dispatch_slack/service.py
Labels: enhancement

#3719 Update Incident Update Modal
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#3722 Correcting link for Dispatch UI Slack bookmark
  src/dispatch/conversation/flows.py
Labels: bug

#3721 Reverts unneeded changes to PagerDuty plugin
  src/dispatch/plugins/dispatch_pagerduty/plugin.py
  src/dispatch/plugins/dispatch_pagerduty/service.py
Labels: bug

#3726 Fixes bug in case escalate flow
  src/dispatch/case/flows.py
Labels: bug

#3725 Query paths are always parsed as strings
  src/dispatch/signal/service.py
Labels: bug

#3734 Fixes issues with updating case reporter and assignee
  src/dispatch/case/flows.py
  src/dispatch/case/views.py
  src/dispatch/group/flows.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3735 Fixes bug in user middleware
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#3736 Fixes issue with resolution reason when trying to edit a case in Slack
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3737 Fixes import error in feedback service scheduled module
  src/dispatch/feedback/service/scheduled.py
Labels: bug

#3741 Removing test scheduling
  src/dispatch/feedback/service/scheduled.py
Labels: bug
