Repository Netflix/dispatch, pull requests merged in 2023-04, with the labels that each got.

#3208 Improvements to tag recommender logging
  src/dispatch/tag/recommender.py
Labels: enhancement

#3200 Remove unnecessary `*` parameter in views, create `CommonParameters` and `CurrentIncident` Annotated types
  src/dispatch/auth/views.py
  src/dispatch/case/priority/views.py
  src/dispatch/case/severity/views.py
  src/dispatch/case/type/views.py
  src/dispatch/case/views.py
  src/dispatch/data/alert/views.py
  src/dispatch/data/query/views.py
  src/dispatch/data/source/data_format/views.py
  src/dispatch/data/source/environment/views.py
  src/dispatch/data/source/status/views.py
  src/dispatch/data/source/transport/views.py
  src/dispatch/data/source/type/views.py
  src/dispatch/data/source/views.py
  src/dispatch/database/service.py
  src/dispatch/definition/views.py
  src/dispatch/document/views.py
  src/dispatch/entity/views.py
  src/dispatch/entity_type/views.py
  src/dispatch/feedback/views.py
  src/dispatch/incident/priority/views.py
  src/dispatch/incident/severity/views.py
  src/dispatch/incident/type/views.py
  src/dispatch/incident/views.py
  src/dispatch/incident_cost/views.py
  src/dispatch/incident_cost_type/views.py
  src/dispatch/incident_role/views.py
  src/dispatch/individual/views.py
  src/dispatch/models.py
  src/dispatch/notification/views.py
  src/dispatch/organization/views.py
  src/dispatch/plugin/views.py
  src/dispatch/project/views.py
  src/dispatch/search/views.py
  src/dispatch/search_filter/views.py
  src/dispatch/service/views.py
  src/dispatch/signal/views.py
  src/dispatch/tag/views.py
  src/dispatch/tag_type/views.py
  src/dispatch/task/views.py
  src/dispatch/team/views.py
  src/dispatch/term/views.py
  src/dispatch/workflow/views.py
Labels: enhancement

#3207 Fixing tests
  src/dispatch/signal/flows.py
  tests/signal/test_signal_service.py
Labels: bug

#3210 Fixing issue with filter actions
  src/dispatch/signal/flows.py
Labels: bug

#3219 Fixes enforce labels workflow
  .github/workflows/enforce-labels.yml
Labels: skip-changelog

#3218 Removes more dead code from Slack plugin
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/plugins/dispatch_slack/incident/enums.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: techdebt

#3224 Fixing case creation logic
  src/dispatch/signal/flows.py
  src/dispatch/signal/service.py
  tests/signal/test_signal_service.py
Labels: bug

#3227 Fixes issue where the model would not save.
  src/dispatch/signal/service.py
Labels: bug

#3226 Add Filter Action column to SignalInstance table
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
Labels: enhancement, UI/UX

#3225 Adds new command for bulk PR merging and improves release notes command
  utils/github_utils.py
  utils/release_notes.py
Labels: enhancement

#3234 Only show entities for the subject Signal type on snooze button Slack modal
  src/dispatch/entity/service.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  tests/entity/test_entity_service.py
Labels: bug

#3241 add a button to visit a case in the case popover
  src/dispatch/static/dispatch/src/case/CasePopover.vue
Labels: enhancement, UI/UX

#3242 Updating documentation links
  README.md
  docker/.env.example
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
Labels: documentation

#3244 Minor improvements to tag scheduler
  src/dispatch/tag/scheduled.py
Labels: enhancement

#3239 Fixes an potential race condition when multiple signals were sent at the same time.
  src/dispatch/entity/models.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/scheduled.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
  tests/factories.py
  tests/signal/test_signal_service.py
Labels: bug

#3243 group entities and display a counter in the card
  src/dispatch/static/dispatch/src/entity/EntitiesTab.vue
  src/dispatch/static/dispatch/src/entity/EntityCard.vue
Labels: bug, UI/UX, javascript

#3245 Show correct cases in Case Dialog on Entity Card
  src/dispatch/static/dispatch/src/entity/EntityCard.vue
Labels: bug, UI/UX, javascript

#3246 No longer needs to be a background task
  src/dispatch/signal/flows.py
  src/dispatch/signal/scheduled.py
Labels: bug

#3247 Add footer and pagination to summary tables to fix global search
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/signal/flows.py
  src/dispatch/static/dispatch/src/case/CaseSummaryTable.vue
  src/dispatch/static/dispatch/src/data/query/QuerySummaryTable.vue
  src/dispatch/static/dispatch/src/data/source/SourceSummaryTable.vue
  src/dispatch/static/dispatch/src/document/DocumentSummaryTable.vue
  src/dispatch/static/dispatch/src/incident/IncidentSummaryTable.vue
  src/dispatch/static/dispatch/src/tag/TagSummaryTable.vue
  src/dispatch/static/dispatch/src/task/TaskSummaryTable.vue
Labels: enhancement

#3255 For larger sheets with ensure that they are not hidden regardless of …
  src/dispatch/static/dispatch/src/case/NewSheet.vue
  src/dispatch/static/dispatch/src/data/source/dataFormat/NewEditSheet.vue
  src/dispatch/static/dispatch/src/data/source/environment/NewEditSheet.vue
  src/dispatch/static/dispatch/src/data/source/status/NewEditSheet.vue
  src/dispatch/static/dispatch/src/data/source/transport/NewEditSheet.vue
  src/dispatch/static/dispatch/src/data/source/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident/EditSheet.vue
  src/dispatch/static/dispatch/src/incident/ExecutiveReportSheet.vue
  src/dispatch/static/dispatch/src/incident/NewSheet.vue
Labels: bug

#3263 Resolve bug on Case Escalate button when `incident_type` not set for Case
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3254 Fixes issue with mini width when submenu is displayed
  src/dispatch/static/dispatch/src/components/AppDrawer.vue
Labels: bug

#3257 Allowing for case type select with typeahead
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
Labels: bug

#3258 Adding bulk closed resolution
  src/dispatch/static/dispatch/src/case/BulkEditSheet.vue
  src/dispatch/static/dispatch/src/case/ClosedDialog.vue
  src/dispatch/static/dispatch/src/case/store.js
Labels: enhancement

#3266 Re-order case creation check so signals are still associated with existing cases
  src/dispatch/signal/flows.py
Labels: bug

#3267 Limit the number of instances we hope to processes within the 1 min window.
  src/dispatch/signal/scheduled.py
Labels: bug

#3273 Making entities optional for snoozing
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/signal/service.py
Labels: enhancement

#3271 Aligns ui with the defaults in slack close.
  src/dispatch/static/dispatch/src/case/ClosedDialog.vue
Labels: bug

#3269 Adding more granularity to the relative dates
  src/dispatch/static/dispatch/src/filters.js
Labels: bug

#3270 Fixes an issue were the entity type dialog wasn't closing
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialog.vue
Labels: bug

#3274 Automatically engage users in Signal data with Signal Engagements and confirm behavior
  src/dispatch/auth/models.py
  src/dispatch/auth/service.py
  src/dispatch/database/revisions/core/versions/2023-04-14_3dd4d12844dc.py
  src/dispatch/database/revisions/tenant/versions/2023-04-14_38a7fb709167.py
  src/dispatch/plugins/dispatch_duo/enums.py
  src/dispatch/plugins/dispatch_duo/plugin.py
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/models.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/signal/enums.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
  src/dispatch/static/dispatch/src/signal/engagement/SignalEngagementCombobox.vue
  src/dispatch/static/dispatch/src/signal/engagement/SignalEngagementCreateDialog.vue
  src/dispatch/static/dispatch/src/signal/engagement/api.js
  src/dispatch/static/dispatch/src/signal/engagement/store.js
  src/dispatch/static/dispatch/src/signal/store.js
  src/dispatch/static/dispatch/src/store.js
Labels: enhancement

#3288 Fix incorrect attribute lookup for `signal.id` and 24 char blockkit limit
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3289 Allowing signals to override case types and case priorities
  src/dispatch/database/revisions/tenant/versions/2023-04-20_56eb1c0a3a92.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/service.py
Labels: enhancement

#3292 Adds cli to register a user from the command line
  src/dispatch/cli.py
Labels: enhancement

#3290 Aggregate signal instance messages in Case thread
  src/dispatch/case/models.py
  src/dispatch/database/revisions/tenant/versions/2023-04-20_930eb80028d2.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/signal/flows.py
Labels: enhancement

#3293 convert snooze filter MFA to use `last_mfa_time` and other cleanup
  src/dispatch/plugins/dispatch_duo/plugin.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: enhancement

#3297 Fixes a bug in case reporting slack shortcut
  src/dispatch/case/models.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#3305 change related_case_count conditional to 1 for first seen
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#3313 Fix relative (days) time option for snooze filter creation in Slack plugin
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3312 Add custom items-per-page to Signal and Case tables
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
Labels: enhancement, UI/UX

#3321 Fixes breaking changes impacting incident ban threads feature
  src/dispatch/case/flows.py
  src/dispatch/conversation/service.py
  src/dispatch/participant/flows.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug
