Repository Netflix/dispatch, pull requests merged in 2023-01, with the labels that each got.

#2799 enhancement/conversation-bookmarks
  src/dispatch/incident/flows.py
Labels: enhancement

#2805 gmail plugin. dont fail when there are no threads with mailer daemon
  src/dispatch/plugins/dispatch_google/gmail/plugin.py
Labels: bug

#2814 Adding success state
  src/dispatch/evergreen/scheduled.py
Labels: bug

#2817 Fixing issue with raw signal data
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
Labels: bug

#2815 Only require workflow_id
  src/dispatch/plugins/generic_workflow/plugin.py
  src/dispatch/workflow/scheduled.py
Labels: bug

#2818 Initializes default project on new organization creation
  src/dispatch/database/manage.py
  src/dispatch/organization/views.py
  src/dispatch/project/flows.py
  src/dispatch/project/views.py
Labels: enhancement

#2819 Fixes issues with ingestion
  src/dispatch/case/models.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/scheduled.py
  src/dispatch/signal/service.py
  src/dispatch/static/dispatch/src/signal/Table.vue
Labels: bug

#2807 individual name is wrongly resolved
  src/dispatch/plugin/models.py
  src/dispatch/plugins/base/v1.py
  src/dispatch/plugins/dispatch_core/plugin.py
Labels: bug

#2793 Checks for auth token on app refresh
  src/dispatch/static/dispatch/src/router/index.js
Labels: bug

#2788 Bugfix/incident-endpoint-performance
  src/dispatch/case/models.py
  src/dispatch/conference/models.py
  src/dispatch/conversation/models.py
  src/dispatch/data/source/models.py
  src/dispatch/database/core.py
  src/dispatch/document/models.py
  src/dispatch/event/models.py
  src/dispatch/feedback/models.py
  src/dispatch/group/models.py
  src/dispatch/incident/models.py
  src/dispatch/incident/priority/models.py
  src/dispatch/incident/severity/models.py
  src/dispatch/incident/type/models.py
  src/dispatch/incident_cost/models.py
  src/dispatch/incident_cost_type/models.py
  src/dispatch/individual/models.py
  src/dispatch/participant/models.py
  src/dispatch/participant_role/models.py
  src/dispatch/service/models.py
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/storage/models.py
  src/dispatch/tag/models.py
  src/dispatch/tag_type/models.py
  src/dispatch/task/models.py
  src/dispatch/ticket/models.py
  src/dispatch/workflow/models.py
Labels: enhancement

#2767 Enhancement/slack bolt
  docs/admin-guide/administration/plugins/configuring-slack.md
  src/dispatch/cli.py
  src/dispatch/incident/flows.py
  src/dispatch/plugins/dispatch_slack/actions.py
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/commands.py
  src/dispatch/plugins/dispatch_slack/decorators.py
  src/dispatch/plugins/dispatch_slack/dialogs.py
  src/dispatch/plugins/dispatch_slack/events.py
  src/dispatch/plugins/dispatch_slack/exceptions.py
  src/dispatch/plugins/dispatch_slack/feedback.py
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/plugins/dispatch_slack/incident/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/messages.py
  src/dispatch/plugins/dispatch_slack/menus.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/modals/common.py
  src/dispatch/plugins/dispatch_slack/modals/feedback/__init__.py
  src/dispatch/plugins/dispatch_slack/modals/feedback/handlers.py
  src/dispatch/plugins/dispatch_slack/modals/feedback/views.py
  src/dispatch/plugins/dispatch_slack/modals/incident/__init__.py
  src/dispatch/plugins/dispatch_slack/modals/incident/enums.py
  src/dispatch/plugins/dispatch_slack/modals/incident/fields.py
  src/dispatch/plugins/dispatch_slack/modals/incident/handlers.py
  src/dispatch/plugins/dispatch_slack/modals/incident/views.py
  src/dispatch/plugins/dispatch_slack/modals/workflow/__init__.py
  src/dispatch/plugins/dispatch_slack/modals/workflow/handlers.py
  src/dispatch/plugins/dispatch_slack/modals/workflow/views.py
  src/dispatch/plugins/dispatch_slack/models.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/plugins/dispatch_slack/socket_mode.py
  src/dispatch/plugins/dispatch_slack/tests/__init__.py
  src/dispatch/plugins/dispatch_slack/views.py
  src/dispatch/plugins/dispatch_slack/workflow.py
  src/dispatch/static/dispatch/src/workflow/WorkflowInstanceTab.vue
Labels: enhancement

#2820 Adding blockkit
  requirements-base.in
  requirements-base.txt
Labels: bug

#2821 Bugfix/requirements
  requirements-base.in
  requirements-base.txt
Labels: bug

#2826 Removing button url
  src/dispatch/plugins/dispatch_slack/messaging.py
Labels: bug

#2827 Bugfix/slack endpoints
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/endpoints.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#2830 Adding read minimal duplcates and related
  src/dispatch/case/models.py
Labels: bug

#2831 Fixing db_session var
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#2832 Removes the depedency on user middleware from most commands
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#2834 Adds a simple cache for an expensive slack api call
  requirements-base.in
  requirements-base.txt
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#2835 Adding incidents ref'd to cases
  src/dispatch/case/models.py
Labels: bug

#2836 Adding user context for restricted commands
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#2837 Small tweaks and lots of timing log lines
  src/dispatch/conversation/service.py
  src/dispatch/decorators.py
  src/dispatch/main.py
  src/dispatch/organization/service.py
  src/dispatch/participant/service.py
  src/dispatch/plugins/dispatch_slack/endpoints.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#2838 add lazy error decorator, resolve tuple unpack exception, and minor type changes
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/decorators.py
  src/dispatch/plugins/dispatch_slack/endpoints.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#2839 Fixes an issue with how the daily notifications where being created
  src/dispatch/notification/service.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#2841 Fixes issue with timeline emoji not being recognized
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#2842 Ignore's bot join events
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#2847 bugfix/bolt-unhandled-exception-and-httpstatus-literals
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/endpoints.py
Labels: bug

#2849 Fixes incident feedback button and modal
  src/dispatch/cli.py
  src/dispatch/conversation/enums.py
  src/dispatch/database/core.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/endpoints.py
  src/dispatch/plugins/dispatch_slack/feedback/enums.py
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/messages.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#2848 bugfix/handle-slash-command-timeouts-and-error-handling
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/exceptions.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#2840 add env var to disable registration
  docker/Dockerfile
  src/dispatch/auth/views.py
  src/dispatch/config.py
  src/dispatch/static/dispatch/src/auth/Login.vue
  src/dispatch/static/dispatch/src/router/config.js
Labels: enhancement

#2859 consolidate get_conversations service method and resolve cache issue
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#2860 Creates default incident and case type on new project creation
  src/dispatch/case/type/config.py
  src/dispatch/incident/type/config.py
  src/dispatch/project/flows.py
Labels: enhancement

#2862 ensure banned thread messages only trigger for human users
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#2863 Adds handlers for incident join and subscribe button click events
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: enhancement

#2829 organization switch reloads to old route
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
Labels: bug

#2868 Bugfix/slack websockets only
  src/dispatch/cli.py
  src/dispatch/decorators.py
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/decorators.py
  src/dispatch/plugins/dispatch_slack/endpoints.py
  src/dispatch/plugins/dispatch_slack/exceptions.py
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/plugins/dispatch_slack/workflow.py
Labels: bug

#2869 bugfix/unasync
  src/dispatch/cli.py
  src/dispatch/plugins/dispatch_slack/decorators.py
  src/dispatch/plugins/dispatch_slack/endpoints.py
  src/dispatch/plugins/dispatch_slack/incident/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/models.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#2874 Adding back in the events router
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#2875 disables request verification
  src/dispatch/plugins/dispatch_slack/bolt.py
Labels: bug

#2877 adds monitor button logic that was lost in merge
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#2700 Enhancement/case notifications
  src/dispatch/case/flows.py
  src/dispatch/case/models.py
  src/dispatch/case/service.py
  src/dispatch/case/type/models.py
  src/dispatch/cli.py
  src/dispatch/conversation/models.py
  src/dispatch/database/revisions/tenant/versions/2023-01-13_6e53722fa1f2.py
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/strings.py
  src/dispatch/notification/service.py
  src/dispatch/plugins/dispatch_slack/case/__init__.py
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/models.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/search_filter/models.py
  src/dispatch/search_filter/service.py
  src/dispatch/search_filter/views.py
  src/dispatch/signal/models.py
  src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/case/type/store.js
  src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue
  src/dispatch/static/dispatch/src/search/store.js
  src/dispatch/task/service.py
  src/dispatch/workflow/service.py
  tests/conftest.py
  tests/factories.py
  tests/search_filter/test_search_filter_service.py
Labels: enhancement

#2879 Missing arg
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#2881 Bugfix/missing arg
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#2880 Bugfix/button bugs
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#2883 Adding case configuration
  src/dispatch/plugins/dispatch_slack/endpoints.py
Labels: bug

#2885 Fixing button links and typings
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#2891 Replaces hyphen with vertical bar as conversation topic separator
  src/dispatch/incident/flows.py
Labels: enhancement

#2893 Makes SearchFilter creator optional
  src/dispatch/search_filter/models.py
Labels: bug

#2895 Fixes issues with conversation creation, incident creation and search filter creation.
  src/dispatch/database/revisions/tenant/versions/2023-01-25_e23c468440c9.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/models.py
  src/dispatch/static/dispatch/src/search/store.js
Labels: bug

#2892 switch report_incident to ack ephem message
  src/dispatch/plugins/dispatch_slack/decorators.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/workflow.py
Labels: bug

#2896 Adds the ability for the message dispatcher to exclude subtypes
  src/dispatch/plugins/dispatch_slack/decorators.py
Labels: bug

#2887 add task button handler and modal draw function, support front-end tasks
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/models.py
  src/dispatch/task/service.py
Labels: bug, enhancement

#2898 Fix none error when conversation plugin is not enabled
  src/dispatch/incident/flows.py
Labels: bug

#2899 Fixes timeline reaction event in incident conversation
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#2900 Reverts a change to the incident conversation description
  src/dispatch/conversation/models.py
  src/dispatch/incident/flows.py
Labels: bug

#2897 update command helper messages from ephemeral message to modal
  docs/admin-guide/administration/plugins/configuring-slack.md
Labels: documentation

#2902 Adds more protections for when conversation does not exist
  src/dispatch/incident/messaging.py
Labels: bug

#2903 Fixes conversation description
  src/dispatch/conversation/models.py
Labels: bug

#2904 Removes email from list participants Slack modal (again)
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: enhancement

#2905 fix exclude logic in message dispatch decorator
  src/dispatch/plugins/dispatch_slack/decorators.py
Labels: bug

#2907 instantly acknowledge /command and /event requests from slack
  src/dispatch/plugins/dispatch_slack/endpoints.py
  src/dispatch/plugins/dispatch_slack/handler.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/workflow.py
Labels: enhancement

#2908 Fixes action_id
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#2909 Add custom error message for expired trigger ids
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/decorators.py
  src/dispatch/plugins/dispatch_slack/messaging.py
Labels: enhancement

#2910 add slack conversation_id to participant model so we don't need expensive api calls
  src/dispatch/database/revisions/tenant/versions/2023-01-27_956eb8f8987e.py
  src/dispatch/participant/models.py
  src/dispatch/participant/service.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: enhancement

#2911 github repo and org/user can have dashes
  src/dispatch/plugins/dispatch_github/plugin.py
Labels: bug

#2912 clean up db_middleware where we already have a session in context obj
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/endpoints.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: enhancement

#2920 Fixes signal slack message
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#2921 testing/case-tests
  tests/case/test_case_service.py
  tests/conftest.py
  tests/factories.py
Labels: enhancement, tests

#2922 Adds participant base data
  src/dispatch/participant/models.py
Labels: bug

#2924 Re-adds added by and added reason to list participants modal
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#2923 Better error handling when creating executive reports via Slack plugin
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#2918 Fixes a few issues with project deletion
  src/dispatch/project/models.py
  src/dispatch/service/views.py
Labels: bug
