Repository Netflix/dispatch, pull requests merged in 2023-07, with the labels that each got.

#3544 Resolve permalink
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#3545 Add's reporter to Case model and displays in UI
  src/dispatch/case/models.py
  src/dispatch/case/service.py
  src/dispatch/database/revisions/tenant/versions/2023-07-03_fa23324d5679.py
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/ParticipantSelect.vue
  src/dispatch/static/dispatch/src/case/store.js
Labels: bug

#3546 Checks for admin role or above on signal definition or filter update or delete
  src/dispatch/signal/views.py
Labels: enhancement

#3547 Fixes bug in Organization Member New Edit UI component
  src/dispatch/static/dispatch/src/organization/OrganizationMemberNewEdit.vue
Labels: bug

#3551 Pass Slack Client to `does_user_exist` function
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#3552 Resolve reporter for cases created via Slack shortcut
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3565 Removes incident tagging logic from Slack plugin
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#3553 Adds ability to snooze Slack reminders for tactical and executive reports
  pyproject.toml
  src/dispatch/conversation/enums.py
  src/dispatch/database/revisions/tenant/versions/2023-07-05_a3fb1380cf76.py
  src/dispatch/database/service.py
  src/dispatch/decorators.py
  src/dispatch/incident/models.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/incident/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/report/messaging.py
  src/dispatch/report/scheduled.py
Labels: enhancement

#3567 Do not fail to reactivate or inactivate all participants if one fails
  src/dispatch/incident/flows.py
Labels: enhancement

#3574 Skips select context parsing if not a select message
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#3575 Updates list of code owners
  .github/CODEOWNERS
Labels: skip-changelog

#3579 Shows Inactive instead of empty string in the participants tab when a participant is inactive
  src/dispatch/static/dispatch/src/filters.js
  src/dispatch/static/dispatch/src/incident/ParticipantsTab.vue
Labels: enhancement

#3573 Allows signals to override case priority by name
  src/dispatch/case/priority/models.py
Labels: enhancement

#3564 Allows for signals to be updated
  src/dispatch/signal/flows.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
Labels: enhancement

#3580 Let's default to the email's username for contact full name and email's domain for team if id provider doesn't have them
  src/dispatch/individual/service.py
  src/dispatch/participant/service.py
Labels: enhancement

#3587 Allows users with member role to update their individual contact info
  src/dispatch/auth/permissions.py
  src/dispatch/individual/views.py
Labels: enhancement

#3585 Removes the time limiting window
  src/dispatch/cli.py
Labels: bug

#3592 the engaged_user should be used in the updated message
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3594 Fix bug where edit button submission would route to resolve submission submit function
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3596 Check for existing case document in update flow
  src/dispatch/case/flows.py
Labels: bug

#3597 lower all case priorities to standardize
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#3588 Make Case report form more user friendly
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
Labels: enhancement, UI/UX, techdebt

#3595 Adds new incident participant permission
  src/dispatch/auth/permissions.py
Labels: bug

#3593 Do not raise an exception when the user cannot be found in MFA provider
  src/dispatch/plugins/dispatch_duo/enums.py
  src/dispatch/plugins/dispatch_duo/plugin.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#3590 Bugfix/missing task notifications
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/task/service.py
  src/dispatch/task/views.py
Labels: bug

#3598 Add cases to search results
  src/dispatch/search/models.py
  src/dispatch/static/dispatch/src/case/CaseSummaryTable.vue
  src/dispatch/static/dispatch/src/search/ResultList.vue
Labels: enhancement

#3604 Fetch SignalInstance UUID from `raw` key in `update_signal_instance`
  src/dispatch/signal/service.py
Labels: bug

#3608 Fixes error when plugin table failed to load if one had a configuration error
  src/dispatch/plugin/models.py
  src/dispatch/static/dispatch/src/plugin/Table.vue
  src/dispatch/static/dispatch/src/plugin/store.js
Labels: bug

#3618 Shows version in help dialog and toast for full version info
  docker/Dockerfile
  src/dispatch/static/dispatch/src/app/store.js
  src/dispatch/static/dispatch/src/auth/store.js
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
  src/dispatch/static/dispatch/src/filters.js
Labels: enhancement

#3619 Fixing wrong var name in import
  src/dispatch/static/dispatch/src/app/store.js
Labels: bug

#3584 Fixes a bug with [] as a filter expression
  src/dispatch/database/service.py
Labels: bug

#3622 Handle missing MFA user in Snooze auth flow
  src/dispatch/plugins/dispatch_core/plugin.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3625 Enabled assignee updating via case modal
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#3628 Allows searching by incident number for Jira-created incident names
  src/dispatch/database/service.py
Labels: bug

#3630 Fixing issue where global search wouldn't return restricted visibility incidents
  src/dispatch/search/views.py
Labels: bug

#3642 Replaces avatar URL with correct format
  src/dispatch/static/dispatch/src/auth/store.js
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
Labels: bug

#3633 Allows users to conduct global search via the URL
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/search/ResultList.vue
Labels: enhancement

#3631 Refactors pagnination fields and allows cases to be expanded.
  src/dispatch/auth/models.py
  src/dispatch/case/models.py
  src/dispatch/case/priority/models.py
  src/dispatch/case/severity/models.py
  src/dispatch/case/type/models.py
  src/dispatch/data/alert/models.py
  src/dispatch/data/query/models.py
  src/dispatch/data/source/data_format/models.py
  src/dispatch/data/source/environment/models.py
  src/dispatch/data/source/models.py
  src/dispatch/data/source/status/models.py
  src/dispatch/data/source/transport/models.py
  src/dispatch/data/source/type/models.py
  src/dispatch/definition/models.py
  src/dispatch/document/models.py
  src/dispatch/entity/models.py
  src/dispatch/entity_type/models.py
  src/dispatch/feedback/models.py
  src/dispatch/incident/models.py
  src/dispatch/incident/priority/models.py
  src/dispatch/incident/severity/models.py
  src/dispatch/incident/type/models.py
  src/dispatch/incident_cost/models.py
  src/dispatch/incident_cost_type/models.py
  src/dispatch/individual/models.py
  src/dispatch/models.py
  src/dispatch/notification/models.py
  src/dispatch/organization/models.py
  src/dispatch/participant/models.py
  src/dispatch/participant_role/models.py
  src/dispatch/plugin/models.py
  src/dispatch/project/models.py
  src/dispatch/report/models.py
  src/dispatch/search_filter/models.py
  src/dispatch/service/models.py
  src/dispatch/signal/models.py
  src/dispatch/tag/models.py
  src/dispatch/tag_type/models.py
  src/dispatch/task/models.py
  src/dispatch/team/models.py
  src/dispatch/term/models.py
  src/dispatch/workflow/models.py
Labels: enhancement

#3641 Fixes a bug were triage at was being overridden
  src/dispatch/case/flows.py
Labels: bug

#3632 Adds triage button
  src/dispatch/conversation/service.py
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: enhancement

#3634 Uses a scoped session for scheduler objects.
  src/dispatch/decorators.py
Labels: bug

#3643 Fixes bug were case conversation is not returned by api
  src/dispatch/case/models.py
Labels: bug

#3646 Allow a signal definition to be referenced by it's external id
  src/dispatch/signal/service.py
Labels: enhancement
