Repository Netflix/dispatch, pull requests merged in 2023-12, with the labels that each got.

#4062 Fixing snackbar errors not showing
  src/dispatch/static/dispatch/src/api.js
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/components/LockButton.vue
  src/dispatch/static/dispatch/src/data/query/store.js
  src/dispatch/static/dispatch/src/data/source/dataFormat/store.js
  src/dispatch/static/dispatch/src/data/source/environment/store.js
  src/dispatch/static/dispatch/src/data/source/status/store.js
  src/dispatch/static/dispatch/src/data/source/store.js
  src/dispatch/static/dispatch/src/data/source/transport/store.js
  src/dispatch/static/dispatch/src/data/source/type/store.js
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/static/dispatch/src/plugin/store.js
  src/dispatch/static/dispatch/src/vuetify/index.js
Labels: bug

#4065 Fix error where exception for missing vector is silenced.
  .github/workflows/python.yml
  src/dispatch/database/service.py
Labels: bug

#4070 Adds vitest proof-of-concept for LockButton component
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/tests/LockButton.spec.js
  src/dispatch/static/dispatch/vitest.config.js
Labels: enhancement, tests, UI/UX, javascript

#4037 Increases text visibility for plugin edit sheet in dark mode.
  src/dispatch/static/dispatch/src/styles/index.scss
Labels: bug

#4071 Change `name` to `id` for reminder URL
  src/dispatch/case/messaging.py
Labels: bug

#4074 Adds filtering support by signal definition to signal instance table
  src/dispatch/static/dispatch/src/signal/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
  src/dispatch/static/dispatch/src/signal/store.js
Labels: enhancement

#4079 Get all items for Pri, Sev, Type, and Project in `SearchPopover` component and add tests
  src/dispatch/static/dispatch/src/case/priority/CasePrioritySearchPopover.vue
  src/dispatch/static/dispatch/src/case/severity/CaseSeveritySearchPopover.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeSearchPopover.vue
  src/dispatch/static/dispatch/src/project/ProjectSearchPopover.vue
  src/dispatch/static/dispatch/src/tests/SearchPopover.spec.js
Labels: bug, tests, UI/UX, javascript

#4080 Require all fields but tags, fix Submit button validation
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
Labels: bug

#4082 Filter by project in SearchPopovers
  src/dispatch/static/dispatch/src/case/CaseAttributesDrawer.vue
  src/dispatch/static/dispatch/src/case/priority/CasePrioritySearchPopover.vue
  src/dispatch/static/dispatch/src/case/severity/CaseSeveritySearchPopover.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeSearchPopover.vue
Labels: bug

#4083 Make only title and description required on case form
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
Labels: bug

#4088 Add CaseStatusSelect group tests, refactor to script setup, and fix a couple bugs
  src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue
  src/dispatch/static/dispatch/src/tests/CaseStatusSelectGroup.spec.js
Labels: bug, tests, UI/UX

#4090 use `flex-shrink` and `min-width 0` for signal instance tab viewer
  src/dispatch/static/dispatch/src/case/CaseSignalInstanceTab.vue
Labels: bug, UI/UX

#4092 Resolve unreferenced conversation variable in no target conditional case
  src/dispatch/conversation/flows.py
Labels: bug

#4093 Change View Case button to Open in Dispatch
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#4095 Aligns closed status name and label
  src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue
Labels: bug

#4100 Add next oncall incident commander as observer
  src/dispatch/database/revisions/tenant/versions/2023-12-08_2f06fd73eae6.py
  src/dispatch/incident/service.py
  src/dispatch/incident_role/models.py
  src/dispatch/plugins/dispatch_pagerduty/plugin.py
  src/dispatch/plugins/dispatch_pagerduty/service.py
  src/dispatch/static/dispatch/src/case/priority/Table.vue
  src/dispatch/static/dispatch/src/case/severity/Table.vue
  src/dispatch/static/dispatch/src/case/type/Table.vue
  src/dispatch/static/dispatch/src/incident/priority/Table.vue
  src/dispatch/static/dispatch/src/incident/severity/Table.vue
  src/dispatch/static/dispatch/src/incident/type/Table.vue
  src/dispatch/static/dispatch/src/incident_cost_type/Table.vue
  src/dispatch/static/dispatch/src/incident_role/PolicyRoleBuilder.vue
  src/dispatch/static/dispatch/src/incident_role/Table.vue
  src/dispatch/static/dispatch/src/search/Table.vue
  src/dispatch/static/dispatch/src/signal/Table.vue
  src/dispatch/static/dispatch/src/workflow/Table.vue
Labels: enhancement

#4094 Move "Signal too large" message to top of `Raw Data` modal, change messaging
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: enhancement

#4102 Fixing issue where case type parameter in route is not resolving
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
Labels: bug

#4101 Allows for an incident commander to be specified when reporting an incident
  src/dispatch/incident/models.py
  src/dispatch/incident/service.py
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
Labels: enhancement

#4130 [Cases] - Clicking row in case table should open page, fix regression
  src/dispatch/static/dispatch/src/case/Table.vue
Labels: bug, UI/UX

#4099 Do not try to render Slack Button with empty url in Signal message
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#4131 [Case] - Refactor table to use script setup v3 api
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/case/store.js
Labels: enhancement, UI/UX, techdebt

#4132 Avoid fetching data on sheet close
  src/dispatch/static/dispatch/src/case/EditSheet.vue
  src/dispatch/static/dispatch/src/data/source/Detail.vue
  src/dispatch/static/dispatch/src/incident/EditSheet.vue
Labels: bug

#4133 Implements missing bulk edit functionality
  src/dispatch/static/dispatch/src/case/BulkEditSheet.vue
  src/dispatch/static/dispatch/src/case/Table.vue
Labels: bug, techdebt

#4144 Restricting oncall feedback permission
  src/dispatch/feedback/service/views.py
  src/dispatch/static/dispatch/src/feedback/service/store.js
Labels: enhancement

#4146 Set closed at time when resolving case in Slack plugin
  src/dispatch/case/models.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4145 Polish CaseStatusSelectGroup dialog when changing status
  src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue
Labels: enhancement, UI/UX

#4147 Only add project to participant filter if non-null
  src/dispatch/static/dispatch/src/components/ParticipantSelect.vue
Labels: bug

#4134 Fixing signal dedup and snooze conflict
  .vscode/settings.json
  src/dispatch/signal/service.py
  tests/signal/test_signal_service.py
Labels: bug

#4135 Fixes table column sorting
  src/dispatch/static/dispatch/src/search/utils.js
Labels: bug

#4157 Fix bug in slack response plan button
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#4153 Enhancement/timeline export
  src/dispatch/event/flows.py
  src/dispatch/event/service.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/service.py
  src/dispatch/incident/views.py
  src/dispatch/plugins/dispatch_google/docs/plugin.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/report/flows.py
  src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue
  src/dispatch/static/dispatch/src/incident/TimelineExportDialog.vue
  src/dispatch/static/dispatch/src/incident/TimelineTab.vue
  src/dispatch/static/dispatch/src/incident/api.js
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/task/service.py
Labels: enhancement
