Repository Netflix/dispatch, pull requests merged in 2023-10, with the labels that each got.

#3796 Enhancement/case reminders
  src/dispatch/case/messaging.py
  src/dispatch/case/scheduled.py
  src/dispatch/cli.py
  src/dispatch/messaging/strings.py
Labels: enhancement

#3827 Fixing var
  src/dispatch/case/scheduled.py
Labels: bug

#3813 Process Signal SQS
  requirements-base.in
  setup.py
  src/dispatch/cli.py
  src/dispatch/plugins/dispatch_aws/__init__.py
  src/dispatch/plugins/dispatch_aws/_version.py
  src/dispatch/plugins/dispatch_aws/config.py
  src/dispatch/plugins/dispatch_aws/plugin.py
  src/dispatch/signal/exceptions.py
  src/dispatch/signal/models.py
  src/dispatch/signal/scheduled.py
  src/dispatch/signal/service.py
Labels: enhancement

#3828 Enhancement/clearer signal consume msg
  src/dispatch/cli.py
Labels: enhancement

#3829 Passes the current state of `experimental_features` to `UserApi`
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
Labels: bug

#3830 Adds Create Case checkbox to Signal Definition table
  src/dispatch/static/dispatch/src/signal/Table.vue
Labels: enhancement

#3834 Fix fast loop when no plugins are enabled
  src/dispatch/cli.py
Labels: bug

#3836 Fixes issues with updating case tickets
  src/dispatch/case/flows.py
  src/dispatch/case/service.py
  src/dispatch/ticket/flows.py
Labels: bug

#3837 Fixing issue with multiprocessing
  src/dispatch/cli.py
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: bug

#3838 Remove extra conditional in resource creation for Case flow
  src/dispatch/case/flows.py
Labels: bug

#3839 Pass create_resources boolean to case_create_resources_flow
  src/dispatch/case/flows.py
Labels: bug

#3842 Renames parameter create_resources to create_all_resources
  src/dispatch/case/flows.py
  src/dispatch/signal/flows.py
Labels: enhancement

#3843 Fixes self-closing warning for v-switch in AppToolbar.vue component
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
Labels: bug

#3845 Adds a note to the engagement initial modal to have MFA device ready …
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: enhancement

#3847 Do not fail to process all case close reminders if one fails
  src/dispatch/case/scheduled.py
Labels: enhancement

#3795 Timeline enhancements
  src/dispatch/auth/permissions.py
  src/dispatch/database/revisions/tenant/versions/2023-09-15_3538650dc471.py
  src/dispatch/enums.py
  src/dispatch/event/flows.py
  src/dispatch/event/models.py
  src/dispatch/event/service.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/service.py
  src/dispatch/incident/views.py
  src/dispatch/participant/flows.py
  src/dispatch/participant_role/flows.py
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/static/dispatch/src/components/DateTimePickerMenu.vue
  src/dispatch/static/dispatch/src/incident/DeleteEventDialog.vue
  src/dispatch/static/dispatch/src/incident/EditEventDialog.vue
  src/dispatch/static/dispatch/src/incident/EditSheet.vue
  src/dispatch/static/dispatch/src/incident/TimelineFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/TimelineTab.vue
  src/dispatch/static/dispatch/src/incident/api.js
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/styles/timeline.css
  src/dispatch/static/dispatch/src/vuetify/config.js
  tests/event/test_event_service.py
Labels: enhancement

#3855 Fix bug where entity types created via Modal don't appear in combobox
  src/dispatch/static/dispatch/src/entity/EntityFilterCombobox.vue
  src/dispatch/static/dispatch/src/entity_type/EntityTypeFilterCombobox.vue
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
Labels: bug

#3846 Allows users to edit name and description of search filter and view membership
  src/dispatch/search_filter/models.py
  src/dispatch/static/dispatch/src/search/EditDialog.vue
  src/dispatch/static/dispatch/src/search/Table.vue
  src/dispatch/static/dispatch/src/search/store.js
Labels: enhancement

#3856 Adds new oncall service feedback table
  src/dispatch/auth/permissions.py
  src/dispatch/database/revisions/tenant/versions/2023-10-06_064c71206256.py
  src/dispatch/feedback/service/models.py
  src/dispatch/feedback/service/service.py
  src/dispatch/feedback/service/views.py
  src/dispatch/individual/models.py
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
  src/dispatch/static/dispatch/src/feedback/incident/DeleteDialog.vue
  src/dispatch/static/dispatch/src/feedback/incident/Table.vue
  src/dispatch/static/dispatch/src/feedback/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/feedback/incident/api.js
  src/dispatch/static/dispatch/src/feedback/incident/store.js
  src/dispatch/static/dispatch/src/feedback/service/DeleteDialog.vue
  src/dispatch/static/dispatch/src/feedback/service/Table.vue
  src/dispatch/static/dispatch/src/feedback/service/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/feedback/service/api.js
  src/dispatch/static/dispatch/src/feedback/service/store.js
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/store.js
Labels: enhancement

#3867 Fixes bug in the case report receipt card UI component
  src/dispatch/static/dispatch/src/case/ReportReceiptCard.vue
Labels: bug

#3863 installation.mdx: Add code markers, lint
  docs/docs/administration/installation.mdx
Labels: documentation

#3844 Link directly to dispatch
  src/dispatch/case/messaging.py
  src/dispatch/messaging/strings.py
Labels: enhancement

#3874 Ensures that signals are actually consumed forever
  src/dispatch/cli.py
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: bug

#3885 Only try to delete if there are entries
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: bug

#3886 Use threads instead of processes for better sqlalchemy support
  src/dispatch/cli.py
Labels: bug

#3871 To allow deletable chips to be saved for `SearchFilterCombobox.vue`, call `$emit` ('input') in remove method
  src/dispatch/static/dispatch/src/search/SearchFilterCombobox.vue
Labels: bug, UI/UX, javascript

#3899 Reverts package-lock.json file to version in PR 3892
  src/dispatch/static/dispatch/package-lock.json
Labels: dependencies

#3902 Fixing an issue where we aren't paging for critical
  src/dispatch/case/flows.py
  src/dispatch/signal/models.py
Labels: bug

#3912 Adds default org for api calls
  src/dispatch/main.py
  src/dispatch/static/dispatch/src/api.js
Labels: bug

#3913 Do not print out raw role policies in the incident roles UI section
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/src/incident_role/PolicyRoleBuilder.vue
  src/dispatch/static/dispatch/src/incident_role/Table.vue
Labels: bug
