Repository Netflix/dispatch, pull requests merged in 2023-02, with the labels that each got.

#2927 Fixes issue when selects have null values
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
  src/dispatch/static/dispatch/src/data/query/QuerySelect.vue
  src/dispatch/static/dispatch/src/data/source/SourceSelect.vue
  src/dispatch/static/dispatch/src/data/source/dataFormat/DataFormatSelect.vue
  src/dispatch/static/dispatch/src/data/source/environment/EnvironmentSelect.vue
  src/dispatch/static/dispatch/src/data/source/status/StatusSelect.vue
  src/dispatch/static/dispatch/src/data/source/transport/TransportSelect.vue
  src/dispatch/static/dispatch/src/data/source/type/TypeSelect.vue
  src/dispatch/static/dispatch/src/document/template/TemplateSelect.vue
  src/dispatch/static/dispatch/src/incident/IncidentSelect.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
  src/dispatch/static/dispatch/src/project/ProjectSelect.vue
  src/dispatch/static/dispatch/src/tag_type/TagTypeSelect.vue
Labels: bug

#2929 Fixes issue where tags list expected a project field
  src/dispatch/database/service.py
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue
  src/dispatch/static/dispatch/src/tag_type/TagTypeFilterCombobox.vue
Labels: bug

#2930 Fixes an issue with the search menu not being rendered correctly
  src/dispatch/static/dispatch/src/router/config.js
Labels: bug

#2931 Make black happy
  src/dispatch/database/revisions/core/env.py
  src/dispatch/database/service.py
  src/dispatch/incident/metrics.py
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/tag/recommender.py
  tests/factories.py
Labels: bug

#2932 Removes minimal models from pagination endpoints
  src/dispatch/incident/priority/models.py
  src/dispatch/incident/severity/models.py
  src/dispatch/incident/type/models.py
  src/dispatch/participant_role/models.py
  src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue
  src/dispatch/static/dispatch/src/tag_type/TagTypeFilterCombobox.vue
  src/dispatch/tag/models.py
  src/dispatch/tag_type/models.py
Labels: bug

#2933 Bugfix/incident read minimal
  src/dispatch/case/models.py
  src/dispatch/incident/models.py
  src/dispatch/individual/models.py
Labels: bug

#2937 Bookmark Incident Review document in the conversation after its creation
  src/dispatch/incident/flows.py
Labels: enhancement

#2938 Adds a query param that expands incident pagination to return the fully populated object
  src/dispatch/incident/models.py
  src/dispatch/incident/views.py
Labels: bug

#2939 Code scanning: CodeQL Action v1 is now deprecated
  .github/workflows/codeql-analysis.yml
Labels: bug, dependencies

#2936 tests/end-to-end-test-for-report-submission-using-playwright-in-ci
  .github/workflows/playwright.yml
  .gitignore
  data/dispatch-sample-data.dump
  playwright.config.ts
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  tests/e2e/report-submission.spec.ts
  tests/e2e/utils/login.ts
Labels: enhancement, tests, javascript

#2945 Refact E2E tests to use Page Object Model (POM), fixtures, and add additional tests
  .gitignore
  playwright.config.ts
  src/dispatch/static/dispatch/src/incident/Table.vue
  tests/e2e/report-submission.spec.ts
  tests/e2e/utils/login.ts
  tests/static/e2e/fixtures/dispatch-fixtures.ts
  tests/static/e2e/incidents-table.spec.ts
  tests/static/e2e/pages/auth-page.ts
  tests/static/e2e/pages/incident-edit-sheet.ts
  tests/static/e2e/pages/incidents-page.ts
  tests/static/e2e/pages/report-incident-page.ts
  tests/static/e2e/report-submission.spec.ts
  tests/static/e2e/routes.ts
  tests/static/e2e/utils/common.ts
  tests/static/e2e/utils/register.ts
Labels: enhancement, tests, UI/UX, javascript

#2800 Add participants to the Case model and add Case permissions
  src/dispatch/auth/permissions.py
  src/dispatch/case/flows.py
  src/dispatch/case/models.py
  src/dispatch/case/service.py
  src/dispatch/case/views.py
  src/dispatch/database/revisions/tenant/versions/2023-01-30_e4b4991dddcd.py
  src/dispatch/document/flows.py
  src/dispatch/group/flows.py
  src/dispatch/participant/flows.py
  src/dispatch/participant/models.py
  src/dispatch/participant/service.py
  src/dispatch/participant_role/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/EditSheet.vue
  src/dispatch/static/dispatch/src/case/Participant.vue
  src/dispatch/static/dispatch/src/case/ParticipantSelect.vue
  src/dispatch/static/dispatch/src/case/ParticipantsTab.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/storage/flows.py
  src/dispatch/ticket/flows.py
  tests/case/test_case_service.py
Labels: enhancement

#2947 Removes unused Individual VueJS components
  src/dispatch/static/dispatch/src/individual/Individual.vue
  src/dispatch/static/dispatch/src/individual/IndividualCombobox.vue
  src/dispatch/static/dispatch/src/individual/IndividualSelect.vue
Labels: enhancement

#2940 Confluence storage and document plugin
  requirements-base.in
  requirements-base.txt
  setup.py
  src/dispatch/incident/flows.py
  src/dispatch/plugins/dispatch_atlassian_confluence/__init__.py
  src/dispatch/plugins/dispatch_atlassian_confluence/_version.py
  src/dispatch/plugins/dispatch_atlassian_confluence/config.py
  src/dispatch/plugins/dispatch_atlassian_confluence/docs/__init__.py
  src/dispatch/plugins/dispatch_atlassian_confluence/docs/_version.py
  src/dispatch/plugins/dispatch_atlassian_confluence/docs/plugin.py
  src/dispatch/plugins/dispatch_atlassian_confluence/plugin.py
Labels: enhancement

#2948 Bugfix/signal schema
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/scheduled.py
Labels: bug

#2913 Enhancement/case search filters
  src/dispatch/case/flows.py
  src/dispatch/conversation/service.py
  src/dispatch/database/revisions/tenant/versions/2023-01-30_941efd922446.py
  src/dispatch/database/revisions/tenant/versions/2023-01-30_e4b4991dddcd.py
  src/dispatch/database/service.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/scheduled.py
  src/dispatch/individual/service.py
  src/dispatch/notification/service.py
  src/dispatch/participant/flows.py
  src/dispatch/participant/service.py
  src/dispatch/plugins/dispatch_core/plugin.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/decorators.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/route/service.py
  src/dispatch/search_filter/models.py
  src/dispatch/search_filter/service.py
  src/dispatch/static/dispatch/src/case/EscalateDialog.vue
  src/dispatch/static/dispatch/src/individual/NewEditSheet.vue
  src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue
  src/dispatch/static/dispatch/src/search/store.js
  src/dispatch/static/dispatch/src/service/NewEditSheet.vue
  src/dispatch/static/dispatch/src/team/NewEditSheet.vue
  src/dispatch/team/service.py
Labels: enhancement

#2952 Direct add participants and allow for new participants via messages.
  src/dispatch/case/flows.py
  src/dispatch/participant/service.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#2949 Allow cases to be re-assigned after addition of participant model
  src/dispatch/case/flows.py
  src/dispatch/case/service.py
  src/dispatch/case/views.py
  src/dispatch/participant/flows.py
  src/dispatch/participant/service.py
  src/dispatch/participant_role/flows.py
Labels: bug

#2960 Only display active roles in CaseParticipantsTab component, add Vitest, and unit test(s)
  .github/workflows/javascript.yml
  .gitignore
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/case/ParticipantsTab.vue
  src/dispatch/static/dispatch/src/filters.js
  src/dispatch/static/dispatch/src/incident/ParticipantsTab.vue
  src/dispatch/static/dispatch/tests/participants-tab.spec.js
  src/dispatch/static/dispatch/vitest.config.js
Labels: enhancement, tests, UI/UX, javascript

#2965 Try to remove tests and test dep to resolve react dep conflict
  .github/workflows/javascript.yml
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/tests/participants-tab.spec.js
  src/dispatch/static/dispatch/vitest.config.js
Labels: bug

#2967 add timers to func calls in add_or_reactivate_participant
  src/dispatch/incident/flows.py
  src/dispatch/incident/messaging.py
  src/dispatch/incident/service.py
  src/dispatch/participant/flows.py
  src/dispatch/participant/service.py
Labels: bug, tests

#2968 Temporarily disables calls to the Dispatch document resolver
  src/dispatch/incident/flows.py
Labels: bug

#2969 Deprecates Slack slash command dispatch-list-resources in favor of channel bookmarks
  src/dispatch/plugins/dispatch_slack/endpoints.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: techdebt

#2970 Adds techdebt label for PRs
  .github/workflows/enforce-labels.yml
  utils/release_notes.py
Labels: enhancement

#2983 Adds more labels
  utils/release_notes.py
Labels: documentation

#2984 Allows to handoff incidents in bulk
  src/dispatch/incident/views.py
  src/dispatch/models.py
  src/dispatch/static/dispatch/src/api.js
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/BulkEditSheet.vue
  src/dispatch/static/dispatch/src/incident/HandoffDialog.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/api.js
  src/dispatch/static/dispatch/src/incident/store.js
Labels: enhancement

#2985 Adds support for handing off cases in bulk
  src/dispatch/static/dispatch/src/case/BulkEditSheet.vue
  src/dispatch/static/dispatch/src/case/HandoffDialog.vue
  src/dispatch/static/dispatch/src/case/store.js
Labels: enhancement

#2946 Removes dispatch-list-resources command code
  docs/admin-guide/administration/plugins/configuring-slack.md
  docs/user-guide/incident-commander.md
  src/dispatch/conversation/enums.py
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/config.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: enhancement

#2986 Resets incident priority to default priority when incident is marked as stable
  src/dispatch/incident/service.py
Labels: enhancement

#2987 update entity tab to display a card for no entities and fix typo in route
  src/dispatch/static/dispatch/src/entity/EntitiesTab.vue
  src/dispatch/static/dispatch/src/router/config.js
Labels: bug, enhancement

#2988 add support for specifying an entity type key/field without a pattern
  src/dispatch/entity/service.py
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/static/dispatch/src/entity_type/NewEditSheet.vue
  tests/conftest.py
  tests/entity/test_entity_service.py
  tests/factories.py
Labels: enhancement

#2993 Removes missed reference to list-resources command
  src/dispatch/incident/messaging.py
Labels: bug

#2989 Adds tab for incident tasks in incident details
  src/dispatch/incident/models.py
  src/dispatch/static/dispatch/src/filters.js
  src/dispatch/static/dispatch/src/incident/EditSheet.vue
  src/dispatch/static/dispatch/src/incident/TasksTab.vue
  src/dispatch/static/dispatch/src/incident/store.js
Labels: enhancement

#2997 Fixes issue with all bulk actions and removes dupe duplicates in IncidentRead Pydantic model
  src/dispatch/incident/models.py
  src/dispatch/tag/models.py
  src/dispatch/tag_type/models.py
Labels: bug

#2999 Fixing associated signal tables
  src/dispatch/signal/models.py
Labels: bug

#3001 adds a relative date chip group to entity tab
  src/dispatch/entity/views.py
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/static/dispatch/src/components/DateChipGroupRelative.vue
  src/dispatch/static/dispatch/src/entity/EntitiesTab.vue
  src/dispatch/static/dispatch/src/entity/EntityCard.vue
  src/dispatch/static/dispatch/src/entity/api.js
Labels: enhancement, UI/UX, javascript

#2994 add support for JSONPath to entity type field extraction
  requirements-base.in
  requirements-base.txt
  src/dispatch/entity/models.py
  src/dispatch/entity/service.py
  src/dispatch/signal/service.py
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/entity_type/NewEditSheet.vue
  tests/entity/test_entity_service.py
Labels: enhancement

#2998 Replaces flake8 with ruff and associated fixes.
  .github/workflows/python.yml
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
  setup.cfg
  src/dispatch/__init__.py
  src/dispatch/case/views.py
  src/dispatch/database/revisions/tenant/versions/2021-07-22_2780d28e4f39.py
  src/dispatch/database/revisions/tenant/versions/2022-05-26_5e2bc6083503.py
  src/dispatch/database/revisions/tenant/versions/2023-01-25_e23c468440c9.py
  src/dispatch/database/revisions/tenant/versions/2023-01-27_956eb8f8987e.py
  src/dispatch/database/service.py
  src/dispatch/entity_type/views.py
  src/dispatch/event/models.py
  src/dispatch/evergreen/scheduled.py
  src/dispatch/incident/scheduled.py
  src/dispatch/logging.py
  src/dispatch/notification/service.py
  src/dispatch/organization/views.py
  src/dispatch/plugins/dispatch_atlassian_confluence/docs/plugin.py
  src/dispatch/plugins/dispatch_atlassian_confluence/plugin.py
  src/dispatch/plugins/dispatch_core/plugin.py
  src/dispatch/plugins/dispatch_google/calendar/plugin.py
  src/dispatch/plugins/dispatch_google/drive/drive.py
  src/dispatch/plugins/dispatch_google/drive/plugin.py
  src/dispatch/plugins/dispatch_google/groups/plugin.py
  src/dispatch/plugins/dispatch_jira/plugin.py
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/endpoints.py
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/plugins/dispatch_zoom/plugin.py
  src/dispatch/search/fulltext/__init__.py
  src/dispatch/search_filter/views.py
  src/dispatch/service/views.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/views.py
  src/dispatch/tag_type/views.py
  src/dispatch/ticket/models.py
  tests/case/test_case_service.py
  tests/event/test_event_service.py
  tests/factories.py
  tests/incident_cost/test_incident_cost_service.py
  tests/notification/test_notification_service.py
  tests/report/test_report_service.py
  tox.ini
Labels: bug

#3004 Fixing ruff errors
  pyproject.toml
  src/dispatch/signal/service.py
Labels: bug

#2976 Enhancement/signal search filters
  src/dispatch/case/models.py
  src/dispatch/database/revisions/tenant/versions/2023-02-13_93b517de08e2.py
  src/dispatch/database/revisions/tenant/versions/2023-02-13_b168b50764c7.py
  src/dispatch/database/service.py
  src/dispatch/entity/service.py
  src/dispatch/entity_type/service.py
  src/dispatch/enums.py
  src/dispatch/main.py
  src/dispatch/models.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
  src/dispatch/static/dispatch/src/components/DateTimePicker.vue
  src/dispatch/static/dispatch/src/entity/EntityFilterCombobox.vue
  src/dispatch/static/dispatch/src/signal/DuplicationRule.vue
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
  src/dispatch/static/dispatch/src/signal/SignalInstanceTab.vue
  src/dispatch/static/dispatch/src/signal/SuppressionRule.vue
  src/dispatch/static/dispatch/src/signal/Table.vue
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
  src/dispatch/static/dispatch/src/signal/api.js
  src/dispatch/static/dispatch/src/signal/filter/ExpirationInput.vue
  src/dispatch/static/dispatch/src/signal/filter/SignalFilterCombobox.vue
  src/dispatch/static/dispatch/src/signal/filter/SignalFilterCreateDialog.vue
  src/dispatch/static/dispatch/src/signal/filter/api.js
  src/dispatch/static/dispatch/src/signal/filter/store.js
  src/dispatch/static/dispatch/src/signal/store.js
  src/dispatch/static/dispatch/src/store.js
  tests/conftest.py
  tests/entity/test_entity_service.py
  tests/entity_type/test_entity_type_service.py
  tests/factories.py
  tests/signal/test_signal_filter_service.py
  tests/signal/test_signal_service.py
Labels: enhancement

#3006 Adds and initializes default project during database initialization to allow user registration
  src/dispatch/database/manage.py
  src/dispatch/signal/service.py
  src/dispatch/static/dispatch/components.d.ts
Labels: bug

#3007 Speeds up plugin install on db init
  src/dispatch/database/manage.py
Labels: enhancement

#3009 Bumps PostgreSQL version in docker files
  docker/Dockerfile
  docker/docker-compose.yml
Labels: docker

#3028 Allows tags to have external IDs
  src/dispatch/database/revisions/tenant/versions/2023-02-27_20d3801ad5b7.py
  src/dispatch/static/dispatch/src/tag/NewEditSheet.vue
  src/dispatch/static/dispatch/src/tag/Table.vue
  src/dispatch/static/dispatch/src/tag/store.js
  src/dispatch/tag/models.py
Labels: enhancement
