Repository Netflix/dispatch, pull requests merged in 2023-09, with the labels that each got.

#3757 Filters health metrics for given project
  src/dispatch/feedback/service/scheduled.py
  src/dispatch/service/service.py
Labels: bug

#3758 Record added and removed tags in timeline
  src/dispatch/incident/flows.py
  src/dispatch/tag/flows.py
Labels: enhancement

#3761 Fixing drill down pane not closing issue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentOverview.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentsDrillDownSheet.vue
Labels: bug

#3756 Adds signal env
  src/dispatch/database/revisions/tenant/versions/2023-09-05_1dd78f49e303.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
  tests/factories.py
  tests/signal/test_signal_flow.py
Labels: enhancement

#3770 Ensures we respect the signal's case override
  src/dispatch/signal/flows.py
Labels: bug

#3771 Revert "Adds signal env"
  src/dispatch/database/revisions/tenant/versions/2023-09-05_1dd78f49e303.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
  tests/factories.py
  tests/signal/test_signal_flow.py
Labels: bug

#3766 bind drilldown drawer attrs
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentOverview.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentsDrillDownSheet.vue
Labels: bug

#3774 Add support for SQLAlchemy pool pre ping
  src/dispatch/config.py
  src/dispatch/database/core.py
Labels: bug

#3773 Adds reminder to oncall end-of-shift feedback request
  src/dispatch/database/revisions/tenant/versions/2023-09-08_0560fab4537f.py
  src/dispatch/feedback/service/messaging.py
  src/dispatch/feedback/service/reminder/__init__.py
  src/dispatch/feedback/service/reminder/models.py
  src/dispatch/feedback/service/reminder/service.py
  src/dispatch/feedback/service/scheduled.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
Labels: enhancement

#3785 Adds canary support for signals.
  src/dispatch/database/revisions/tenant/versions/2023-09-13_e875e9544048.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
Labels: enhancement

#3788 Fixing case resolution error
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3797 Do not run playwright with Webkit
  .github/workflows/playwright.yml
Labels: bug

#3798 Appends outstanding incident tasks in tactical reports
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/static/dispatch/src/incident/store.js
Labels: bug

#3789 Rework the way slack api errors are propagated (to the caller)
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#3803 Only use stable priority if it is set
  src/dispatch/incident/service.py
Labels: bug

#3799 Making experience textbox from oncall end-of-shift feedback optional
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
Labels: enhancement

#3814 Revert "Making experience textbox from oncall end-of-shift feedback optional"
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
Labels: bug

#3791 Adds functionality to manually create missing incident and case resources.
  src/dispatch/case/flows.py
  src/dispatch/case/views.py
  src/dispatch/conversation/flows.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/messaging.py
  src/dispatch/incident/views.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/static/dispatch/src/case/ResourcesTab.vue
  src/dispatch/static/dispatch/src/case/api.js
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/incident/ResourcesTab.vue
  src/dispatch/static/dispatch/src/incident/api.js
  src/dispatch/static/dispatch/src/incident/store.js
Labels: enhancement

#3817 Fixes errors in oncall end-of-shift feedback reminders plus opens api to fetch feedback
  src/dispatch/api.py
  src/dispatch/feedback/service/models.py
  src/dispatch/feedback/service/reminder/service.py
  src/dispatch/feedback/service/scheduled.py
  src/dispatch/feedback/service/views.py
  src/dispatch/plugins/dispatch_pagerduty/plugin.py
  src/dispatch/plugins/dispatch_pagerduty/service.py
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
  src/dispatch/static/dispatch/src/service_feedback/api.js
Labels: bug

#3802 Allowing filtering in incident dashboard by participant or commander
  src/dispatch/database/service.py
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentDialogFilter.vue
  src/dispatch/static/dispatch/src/router/utils.js
  src/dispatch/static/dispatch/src/search/utils.js
Labels: enhancement

#3822 Fixing restricted query statement
  src/dispatch/database/service.py
Labels: bug

#3818 Adds `Experimental Features` toggle for built-in feature flags
  src/dispatch/auth/models.py
  src/dispatch/auth/service.py
  src/dispatch/database/revisions/core/versions/2023-09-27_5c60513d6e5e.py
  src/dispatch/static/dispatch/src/auth/store.js
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
Labels: enhancement, UI/UX
