Repository Netflix/dispatch, pull requests merged in 2023-05, with the labels that each got.

#3330 change signal not enabled log from warning to info
  src/dispatch/signal/views.py
Labels: bug

#3329 Adds a default 1 hour window deduplication check on signal filter flow
  src/dispatch/signal/scheduled.py
  src/dispatch/signal/service.py
  tests/signal/test_signal_service.py
Labels: enhancement

#3340 Downgrades error levels and improves some logic
  src/dispatch/document/scheduled.py
  src/dispatch/plugins/dispatch_google/drive/drive.py
  src/dispatch/signal/views.py
  src/dispatch/workflow/scheduled.py
  src/dispatch/workflow/service.py
Labels: enhancement

#3342 Resolve ruff `B017` in `test_signal_flow.py`
  src/dispatch/signal/flows.py
  src/dispatch/workflow/service.py
  tests/signal/test_signal_flow.py
Labels: bug

#3345 Filters out Slack events from USLACKBOT
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#3339 limit entity select to 100 and only show entities for signal
  src/dispatch/entity/service.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#3344 handle cases where the Email Display setting is unchecked in Slack Admin settings
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#3350 fix typo in signal edit sheet
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
Labels: bug

#3352 Adds project and organization name to warning messages
  src/dispatch/monitor/scheduled.py
  src/dispatch/task/scheduled.py
  src/dispatch/workflow/scheduled.py
Labels: enhancement

#3331 Conditional creation of case resources for perf improvement on signal ingest
  src/dispatch/case/flows.py
  src/dispatch/incident/flows.py
  src/dispatch/individual/service.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/signal/flows.py
Labels: enhancement

#3337 Optimize signal ingestion pipeline and create perf-test cli util
  src/dispatch/cli.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/scheduled.py
  src/dispatch/signal/service.py
Labels: enhancement

#3355 Improves incident auto-tagger scheduled job
  src/dispatch/incident/scheduled.py
  src/dispatch/tag/scheduled.py
Labels: enhancement

#3356 Improves task syncing scheduled job
  src/dispatch/plugins/dispatch_google/drive/drive.py
  src/dispatch/task/scheduled.py
Labels: enhancement

#3357 Disables tag recommendations in TagFilterAutoComplete UI component
  src/dispatch/static/dispatch/src/tag/DeleteDialog.vue
  src/dispatch/static/dispatch/src/tag/List.vue
  src/dispatch/static/dispatch/src/tag/NewEditSheet.vue
  src/dispatch/static/dispatch/src/tag/Table.vue
  src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue
  src/dispatch/static/dispatch/src/tag/TagSummaryTable.vue
Labels: bug

#3338 Adds 250/minute rate limit to SignalInstance POST API endpoint using `slowapi`
  requirements-base.in
  requirements-base.txt
  src/dispatch/main.py
  src/dispatch/rate_limiter.py
  src/dispatch/signal/views.py
Labels: enhancement

#3314 Allows for a signal's raw uuid to be our raw id
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
Labels: enhancement

#3376 Remove `gitter` from README.md
  README.md
Labels: documentation

#3368 set explicit build dir in Vite to resolve `Expected a JavaScript module on rebuild` error
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/vite.config.js
Labels: bug, UI/UX

#3311 Fix issue where Snooze filter cannot be created when no entities are selected
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/signal/models.py
Labels: bug

#3367 Add common modal for success that catches not_found exception
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/modals/common.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug, enhancement

#3369 Allow customizing notification templates per project
  docs/docs/administration/settings/messaging.mdx
  src/dispatch/messaging/email/utils.py
  src/dispatch/plugins/dispatch_google/gmail/plugin.py
Labels: enhancement

#3384 Adding optional external id
  src/dispatch/signal/views.py
Labels: bug

#3385 Modifying the way the editor is imported
  src/dispatch/static/dispatch/src/data/query/EditTextTab.vue
  src/dispatch/static/dispatch/src/data/source/DetailsTab.vue
  src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue
  src/dispatch/static/dispatch/src/signal/RawSignalViewer.vue
  src/dispatch/static/dispatch/src/signal/filter/SignalFilterCreateDialog.vue
Labels: bug

#3386 rolling back #3368
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/vite.config.js
Labels: bug

#3390 Reducing the amount of data return by the signal instance api
  src/dispatch/signal/models.py
  src/dispatch/static/dispatch/src/signal/store.js
Labels: enhancement

#3394 Removing non-uuid id
  tests/performance/signalInstances.lua
Labels: bug

#3396 Rolls back session changes in #3365
  src/dispatch/decorators.py
Labels: bug

#3399 Signals aren't required to have IDs
  src/dispatch/signal/scheduled.py
Labels: bug

#3398 Adds a new project settings section for managing search filters
  src/dispatch/database/revisions/tenant/versions/2023-05-17_9ad021045e45.py
  src/dispatch/search_filter/models.py
  src/dispatch/search_filter/views.py
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/search/DeleteDialog.vue
  src/dispatch/static/dispatch/src/search/Table.vue
  src/dispatch/static/dispatch/src/search/api.js
  src/dispatch/static/dispatch/src/search/store.js
Labels: enhancement

#3397 Adds the ability to create users via the UI
  src/dispatch/auth/models.py
  src/dispatch/auth/service.py
  src/dispatch/auth/views.py
  src/dispatch/static/dispatch/src/auth/api.js
  src/dispatch/static/dispatch/src/auth/store.js
  src/dispatch/static/dispatch/src/organization/OrganizationMemberEdit.vue
  src/dispatch/static/dispatch/src/organization/OrganizationMemberNewEdit.vue
  src/dispatch/static/dispatch/src/organization/OrganizationMemberTable.vue
Labels: enhancement

#3413 Increases items per page to 25 in incidents table
  src/dispatch/static/dispatch/src/incident/Table.vue
Labels: enhancement

#3412 Adds a new permissions class for editing and deleting search filters
  src/dispatch/search_filter/permissions.py
  src/dispatch/search_filter/views.py
Labels: enhancement

#3420 Fixes an issue where the wrong enum was associated
  src/dispatch/plugins/dispatch_slack/incident/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#3419 Updates documentation about prerequisites
  docs/docs/administration/contributing/environment.mdx
Labels: documentation

#3414 Aligns schedule job and function names and fixes some bugs
  src/dispatch/cli.py
  src/dispatch/data/source/scheduled.py
  src/dispatch/document/scheduled.py
  src/dispatch/evergreen/scheduled.py
  src/dispatch/feedback/scheduled.py
  src/dispatch/incident/scheduled.py
  src/dispatch/monitor/scheduled.py
  src/dispatch/plugins/dispatch_slack/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/tag/scheduled.py
  src/dispatch/tag/views.py
  src/dispatch/task/scheduled.py
  src/dispatch/term/scheduled.py
  src/dispatch/workflow/scheduled.py
Labels: bug

#3421 Fixes an issue where we were using the name instead of id for tag select
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#3422 Build incident tag models once a day
  src/dispatch/tag/scheduled.py
Labels: enhancement

#3423 Uses colors to visually differentiate between used and unused filters in search filter table
  .eslintrc.json
  .prettierrc
  src/dispatch/static/dispatch/src/search/Table.vue
Labels: enhancement

#3424 Improves alert text in search filter UI table
  src/dispatch/static/dispatch/src/search/Table.vue
Labels: enhancement

#3427 Adds timer decorator to scheduled job functions
  src/dispatch/data/source/scheduled.py
  src/dispatch/document/scheduled.py
  src/dispatch/evergreen/scheduled.py
  src/dispatch/feedback/scheduled.py
  src/dispatch/incident/scheduled.py
  src/dispatch/incident_cost/scheduled.py
  src/dispatch/monitor/scheduled.py
  src/dispatch/report/scheduled.py
  src/dispatch/signal/scheduled.py
  src/dispatch/tag/scheduled.py
  src/dispatch/task/scheduled.py
  src/dispatch/term/scheduled.py
  src/dispatch/workflow/scheduled.py
Labels: enhancement

#3428 Checks if conversation is archived before trying to archive it
  src/dispatch/conversation/flows.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#3443 Fix a bug where db_session is not passed in Slack Case creation
  src/dispatch/case/flows.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3447 db_session needs to be passed to `case_new_create_flow`
  src/dispatch/case/views.py
Labels: bug

#3445 Re scoping the database session close
  src/dispatch/decorators.py
Labels: bug

#3444 Allows pre-population of the incident title, description, and tags in the incident intake form by including them in the URL path.
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
  tests/static/e2e/pages/report-incident-page.ts
  tests/static/e2e/report-submission.spec.ts
Labels: enhancement
