Repository Netflix/dispatch, pull requests merged in 2023-06, with the labels that each got.

#3456 Fixes issue were a new type would replace old types
  src/dispatch/static/dispatch/src/entity_type/EntityTypeFilterCombobox.vue
Labels: bug

#3457 Makes the entity type select have a type ahead
  src/dispatch/static/dispatch/src/entity_type/EntityTypeSelect.vue
Labels: bug

#3458 Fixes deleteable chips in various elements
  src/dispatch/static/dispatch/src/components/BaseCombobox.vue
  src/dispatch/static/dispatch/src/incident/IncidentCombobox.vue
  src/dispatch/static/dispatch/src/search/SearchFilterCombobox.vue
  src/dispatch/static/dispatch/src/signal/SignalDefinitionCombobox.vue
  src/dispatch/static/dispatch/src/signal/engagement/SignalEngagementCombobox.vue
  src/dispatch/static/dispatch/src/signal/filter/SignalFilterCombobox.vue
  src/dispatch/static/dispatch/src/workflow/WorkflowCombobox.vue
Labels: bug

#3459 Fixes side bar loading
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialog.vue
Labels: bug

#3349 First draft outline of new documentation for everything Signals in Dispatch
  docs/docs/administration/settings/signal/definition.mdx
  docs/docs/administration/settings/signal/engagement-filter.mdx
  docs/docs/administration/settings/signal/entity-type.mdx
  docs/docs/administration/settings/signal/filter.mdx
  docs/docs/administration/settings/signal/index.mdx
  docs/static/img/admin-ui-signal-definition.png
  docs/static/img/admin-ui-signal-engagement-filter.png
  docs/static/img/admin-ui-signal-entity-type-name.png
  docs/static/img/admin-ui-signal-entity-type.png
  docs/static/img/admin-ui-signal-filter-dedupe.png
  docs/static/img/admin-ui-signal-filter-snooze.png
Labels: documentation

#3461 Adds documentation for Signals
  docs/docs/administration/settings/signal/filter.mdx
Labels: documentation

#3463 Add pagination to mini signal table tab
  src/dispatch/static/dispatch/src/signal/SignalInstanceTab.vue
Labels: bug, UI/UX

#3468 Ensuring that the assignee override is respected
  src/dispatch/signal/flows.py
Labels: bug

#3469 guard against null/empty entity values in entity select
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#3471 Fixes issue with signal assignee
  src/dispatch/signal/flows.py
Labels: bug

#3470 mark resolution reason field as optional
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3473 Increasing size of signal viewer
  src/dispatch/static/dispatch/src/signal/RawSignalViewer.vue
Labels: enhancement

#3478 workflow related fixes
  src/dispatch/plugins/dispatch_slack/workflow.py
  src/dispatch/workflow/service.py
Labels: bug

#3479 Updates dashboard filters
  src/dispatch/static/dispatch/src/dashboard/case/CaseOverview.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentOverview.vue
Labels: bug

#3462 Adds entity type management UI
  src/dispatch/database/revisions/tenant/versions/2023-06-05_35a2ad8b53a2.py
  src/dispatch/database/revisions/tenant/versions/2023-06-05_bad95cd82724.py
  src/dispatch/database/revisions/tenant/versions/2023-06-06_0a19c5a4c2ba.py
  src/dispatch/entity/service.py
  src/dispatch/entity_type/models.py
  src/dispatch/entity_type/service.py
  src/dispatch/signal/flows.py
  src/dispatch/static/dispatch/src/entity_type/DeleteDialog.vue
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialog.vue
  src/dispatch/static/dispatch/src/entity_type/EntityTypeFilterCombobox.vue
  src/dispatch/static/dispatch/src/entity_type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/entity_type/Table.vue
  src/dispatch/static/dispatch/src/entity_type/playground/PlaygroundTextBox.vue
  src/dispatch/static/dispatch/src/entity_type/store.js
  src/dispatch/static/dispatch/src/router/config.js
  tests/entity/test_entity_service.py
  tests/entity_type/test_entity_type_service.py
  tests/factories.py
  tests/signal/test_signal_service.py
Labels: enhancement

#3483 removes the minimap from the `RawSignalViewer` component monaco editor
  src/dispatch/static/dispatch/src/signal/RawSignalViewer.vue
Labels: bug, UI/UX

#3489 Fixes some small bugs in the existing entity type dialog
  src/dispatch/entity_type/service.py
  src/dispatch/signal/service.py
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialog.vue
  src/dispatch/static/dispatch/src/entity_type/EntityTypeFilterCombobox.vue
Labels: bug

#3485 Fixes sending duplicate resolved messages
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3486 Always make sure there is a creator
  src/dispatch/plugins/dispatch_google/drive/task.py
Labels: bug

#3484 updates the case closed_at time when resolved from slack
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug, UI/UX

#3495 Fixes bug with entity type deletion
  src/dispatch/entity_type/views.py
Labels: bug

#3487 Opens incident and case details by clicking on the incident or case row
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/status/IncidentStatus.vue
Labels: enhancement

#3496 Addresses issues with cloud support in Jira plugin
  src/dispatch/plugins/dispatch_jira/plugin.py
Labels: bug

#3497 Fixes bug in Jira plugin
  src/dispatch/plugins/dispatch_jira/plugin.py
Labels: bug

#3500 Fixes is digit check in Jira plugin code
  src/dispatch/plugins/dispatch_jira/plugin.py
Labels: bug

#3502 Adds a color emjoii to case priority
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#3504 Fixes snoozing issue when signals have no entities
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#3509 Fixing case permissions
  src/dispatch/auth/permissions.py
Labels: bug

#3474 MS teams conference initial commit
  requirements-base.in
  requirements-base.txt
  setup.py
  src/dispatch/plugins/dispatch_microsoft_teams/__init__.py
  src/dispatch/plugins/dispatch_microsoft_teams/conference/__init__.py
  src/dispatch/plugins/dispatch_microsoft_teams/conference/_version.py
  src/dispatch/plugins/dispatch_microsoft_teams/conference/client.py
  src/dispatch/plugins/dispatch_microsoft_teams/conference/config.py
  src/dispatch/plugins/dispatch_microsoft_teams/conference/plugin.py
Labels: enhancement

#3515 Adding a different model for listing plugin instances
  src/dispatch/plugin/models.py
  src/dispatch/plugin/views.py
  src/dispatch/static/dispatch/src/plugin/store.js
Labels: bug

#3449 Updates Dispatch Conversation URLs to reflect complete workspace URL
  src/dispatch/plugins/dispatch_slack/enums.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#3511 Adding tooltip with actual datetime to timeline tabs
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/case/TimelineTab.vue
  src/dispatch/static/dispatch/src/filters.js
  src/dispatch/static/dispatch/src/incident/TimelineTab.vue
Labels: enhancement

#3519 Adding missing css files from PR 3511
  package-lock.json
  src/dispatch/static/dispatch/src/assets/styles/timeline.css
Labels: bug

#3522 Revert "Updates Dispatch Conversation URLs to reflect complete workspace URL"
  src/dispatch/plugins/dispatch_slack/enums.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#3523 Changing timeline to show UTC and adding local time to tooltip
  src/dispatch/static/dispatch/src/case/TimelineTab.vue
  src/dispatch/static/dispatch/src/filters.js
  src/dispatch/static/dispatch/src/incident/TimelineTab.vue
  src/dispatch/static/dispatch/src/styles/timeline.css
Labels: enhancement

#3518 Handles missing user in signal engagement flow
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#3527 don't update engagement message for failed response
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#3530 Fixes docstring in slack_menus handler function
  src/dispatch/plugins/dispatch_slack/endpoints.py
Labels: bug

#3520 Adds the Slack domain to the conversation weblink URL.
  src/dispatch/plugins/dispatch_slack/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: enhancement

#3533 Deduplicates participants lists before they're used for adding users to conversations or threads
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#3535 Adding original values to timeline details for incidents and cases
  src/dispatch/case/service.py
  src/dispatch/incident/service.py
Labels: enhancement
