Repository Netflix/dispatch, pull requests merged in 2023-11, with the labels that each got.

#3917 Rollback session in case of exceptions
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: bug

#3921 Bugfix/table font size
  src/dispatch/static/dispatch/src/main.js
  src/dispatch/static/dispatch/src/styles/index.scss
Labels: bug

#3920 Adding padding for spacing on participants and resources tabs
  src/dispatch/static/dispatch/src/case/ParticipantsTab.vue
  src/dispatch/static/dispatch/src/case/ResourcesTab.vue
  src/dispatch/static/dispatch/src/incident/ParticipantsTab.vue
  src/dispatch/static/dispatch/src/incident/ResourcesTab.vue
Labels: bug

#3919 Fixing export preview missing scroll for incidents, cases, and tasks
  src/dispatch/static/dispatch/src/case/TableExportDialog.vue
  src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
  src/dispatch/static/dispatch/src/task/TableExportDialog.vue
Labels: bug

#3918 Fixing styling for incident priority settings, search filter settings, and plugins table
  src/dispatch/static/dispatch/src/incident/priority/Table.vue
  src/dispatch/static/dispatch/src/plugin/Table.vue
  src/dispatch/static/dispatch/src/search/EditDialog.vue
Labels: bug

#3923 Ignore v-stepper and other deprecated component linter errors
  src/dispatch/static/dispatch/.eslintrc.js
Labels: bug

#3922 Fixes issues with Signals table after migration to Vue3
  src/dispatch/static/dispatch/src/signal/SignalPopover.vue
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
Labels: bug

#3914 handle possible null actions in interactive.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#3925 Fixing participant select and centralizes component
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/HandoffDialog.vue
  src/dispatch/static/dispatch/src/case/ParticipantSelect.vue
  src/dispatch/static/dispatch/src/components/ParticipantSelect.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentDialogFilter.vue
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/HandoffDialog.vue
  src/dispatch/static/dispatch/src/incident/ParticipantSelect.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/task/NewEditSheet.vue
Labels: bug

#3926 Restyling templates settings page
  src/dispatch/static/dispatch/src/document/template/TemplateTable.vue
Labels: bug

#3932 Bugfix/format timeline fixes
  src/dispatch/static/dispatch/src/components/DateTimePickerMenu.vue
  src/dispatch/static/dispatch/src/incident/EditEventDialog.vue
  src/dispatch/static/dispatch/src/incident/TimelineTab.vue
Labels: bug

#3933 Mirror the incident bottom sheet to prevent focus from being stolen
  src/dispatch/static/dispatch/src/case/BulkEditSheet.vue
Labels: bug, UI/UX

#3934 return object when an item is selected in case/incident table
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
Labels: bug

#3935 return object for tasks data table
  src/dispatch/static/dispatch/src/task/Table.vue
Labels: bug

#3936 Fixing issue with new template dialog always appearing
  src/dispatch/static/dispatch/src/case/type/Table.vue
  src/dispatch/static/dispatch/src/document/template/TemplateNewEditSheet.vue
  src/dispatch/static/dispatch/src/document/template/TemplateSelect.vue
  src/dispatch/static/dispatch/src/incident/type/Table.vue
Labels: bug

#3945 Removing password element from plugin form
  src/dispatch/static/dispatch/src/plugin/store.js
Labels: bug

#3946 Fixing time not saving correctly in edit event dialog
  src/dispatch/static/dispatch/src/incident/EditEventDialog.vue
  src/dispatch/static/dispatch/src/incident/TimelineTab.vue
  src/dispatch/static/dispatch/src/incident/store.js
Labels: bug

#3944 Project autocomplete
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/components/AutoComplete.vue
  src/dispatch/static/dispatch/src/components/ParticipantSelect.vue
  src/dispatch/static/dispatch/src/project/ProjectAutoComplete.vue
Labels: enhancement

#3951 Use real JSONPathError exception
  src/dispatch/entity/service.py
Labels: bug

#3955 Only display raw data in signal viewer
  src/dispatch/static/dispatch/src/incident/EditEventDialog.vue
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
Labels: bug

#3969 Fixing playwright tests
  tests/static/e2e/pages/auth-page.ts
  tests/static/e2e/pages/incident-edit-sheet.ts
  tests/static/e2e/pages/incidents-page.ts
  tests/static/e2e/pages/report-incident-page.ts
Labels: bug

#3970 Fixing playwright tests part 2
  src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue
  tests/static/e2e/pages/report-incident-page.ts
  tests/static/e2e/report-submission.spec.ts
Labels: bug

#3971 Replacing deprecated props
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialog.vue
  src/dispatch/static/dispatch/src/entity_type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/signal/filter/SignalFilterCreateDialog.vue
Labels: bug

#3967 Making search more reliable
  src/dispatch/database/service.py
Labels: bug

#3973 Bugfix/vuetify upgrade
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/vuetify/index.js
Labels: enhancement

#3975 Updates OpenAI plugin
  src/dispatch/plugins/dispatch_openai/config.py
  src/dispatch/plugins/dispatch_openai/plugin.py
Labels: enhancement

#3957 Pre commit/eslint ruff versions
  .pre-commit-config.yaml
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
Labels: enhancement

#3985 Removes canary column in signal instance table
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
Labels: enhancement

#3984 Only show variant in case notification if it is set
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#3994 Declutters Slack case threads
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: enhancement

#3986 Fixes DSN.
  src/dispatch/static/dispatch/src/main.js
Labels: bug

#3995 Uses entity type name in Slack snooze modal
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#3996 Show entity value in entity filter combobox
  src/dispatch/static/dispatch/src/entity/EntityFilterCombobox.vue
Labels: bug, UI/UX

#3989 Aligns form styles and reverts project autocomplete
  src/dispatch/static/dispatch/src/auth/Login.vue
  src/dispatch/static/dispatch/src/auth/Register.vue
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/ReportReceiptCard.vue
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/components/layouts/BasicLayout.vue
  src/dispatch/static/dispatch/src/incident/ReportForm.vue
  src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/styles/index.scss
Labels: bug

#3992 Fixing settings bread crumbs
  src/dispatch/static/dispatch/src/components/AppDrawer.vue
  src/dispatch/static/dispatch/src/components/SettingsBreadcrumbs.vue
  src/dispatch/static/dispatch/src/project/ProjectMenuSelect.vue
Labels: bug, UI/UX

#3990 Fixing table cards to remove card outlines
  src/dispatch/static/dispatch/src/App.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/priority/Table.vue
  src/dispatch/static/dispatch/src/case/severity/Table.vue
  src/dispatch/static/dispatch/src/case/type/Table.vue
  src/dispatch/static/dispatch/src/components/StatWidget.vue
  src/dispatch/static/dispatch/src/dashboard/DashboardCard.vue
  src/dispatch/static/dispatch/src/data/query/Table.vue
  src/dispatch/static/dispatch/src/data/source/Table.vue
  src/dispatch/static/dispatch/src/data/source/dataFormat/Table.vue
  src/dispatch/static/dispatch/src/data/source/environment/Table.vue
  src/dispatch/static/dispatch/src/data/source/status/Table.vue
  src/dispatch/static/dispatch/src/data/source/transport/Table.vue
  src/dispatch/static/dispatch/src/data/source/type/Table.vue
  src/dispatch/static/dispatch/src/definition/Table.vue
  src/dispatch/static/dispatch/src/document/reference/ReferenceTable.vue
  src/dispatch/static/dispatch/src/document/runbook/RunbookTable.vue
  src/dispatch/static/dispatch/src/document/template/TemplateTable.vue
  src/dispatch/static/dispatch/src/entity_type/Table.vue
  src/dispatch/static/dispatch/src/feedback/incident/Table.vue
  src/dispatch/static/dispatch/src/feedback/service/Table.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/priority/Table.vue
  src/dispatch/static/dispatch/src/incident/severity/Table.vue
  src/dispatch/static/dispatch/src/incident/type/Table.vue
  src/dispatch/static/dispatch/src/incident_cost_type/Table.vue
  src/dispatch/static/dispatch/src/individual/Table.vue
  src/dispatch/static/dispatch/src/notification/Table.vue
  src/dispatch/static/dispatch/src/organization/OrganizationMemberTable.vue
  src/dispatch/static/dispatch/src/plugin/Table.vue
  src/dispatch/static/dispatch/src/project/Table.vue
  src/dispatch/static/dispatch/src/search/Table.vue
  src/dispatch/static/dispatch/src/service/Table.vue
  src/dispatch/static/dispatch/src/signal/Table.vue
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
  src/dispatch/static/dispatch/src/tag/Table.vue
  src/dispatch/static/dispatch/src/tag_type/Table.vue
  src/dispatch/static/dispatch/src/task/Table.vue
  src/dispatch/static/dispatch/src/team/Table.vue
  src/dispatch/static/dispatch/src/term/Table.vue
  src/dispatch/static/dispatch/src/workflow/Table.vue
Labels: bug

#3993 Increase min page sizes to 25
  src/dispatch/static/dispatch/src/auth/store.js
  src/dispatch/static/dispatch/src/case/priority/store.js
  src/dispatch/static/dispatch/src/case/severity/store.js
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/case/type/store.js
  src/dispatch/static/dispatch/src/data/query/store.js
  src/dispatch/static/dispatch/src/data/source/dataFormat/store.js
  src/dispatch/static/dispatch/src/data/source/environment/store.js
  src/dispatch/static/dispatch/src/data/source/status/store.js
  src/dispatch/static/dispatch/src/data/source/store.js
  src/dispatch/static/dispatch/src/data/source/transport/store.js
  src/dispatch/static/dispatch/src/data/source/type/store.js
  src/dispatch/static/dispatch/src/definition/store.js
  src/dispatch/static/dispatch/src/document/reference/store.js
  src/dispatch/static/dispatch/src/document/runbook/store.js
  src/dispatch/static/dispatch/src/document/store.js
  src/dispatch/static/dispatch/src/document/template/store.js
  src/dispatch/static/dispatch/src/entity/store.js
  src/dispatch/static/dispatch/src/entity_type/store.js
  src/dispatch/static/dispatch/src/feedback/incident/store.js
  src/dispatch/static/dispatch/src/feedback/service/store.js
  src/dispatch/static/dispatch/src/incident/priority/store.js
  src/dispatch/static/dispatch/src/incident/severity/store.js
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/static/dispatch/src/incident/type/store.js
  src/dispatch/static/dispatch/src/incident_cost_type/store.js
  src/dispatch/static/dispatch/src/individual/store.js
  src/dispatch/static/dispatch/src/notification/store.js
  src/dispatch/static/dispatch/src/plugin/store.js
  src/dispatch/static/dispatch/src/project/store.js
  src/dispatch/static/dispatch/src/search/store.js
  src/dispatch/static/dispatch/src/service/store.js
  src/dispatch/static/dispatch/src/signal/filter/store.js
  src/dispatch/static/dispatch/src/tag/store.js
  src/dispatch/static/dispatch/src/tag_type/store.js
  src/dispatch/static/dispatch/src/task/store.js
  src/dispatch/static/dispatch/src/team/store.js
  src/dispatch/static/dispatch/src/term/store.js
  src/dispatch/static/dispatch/src/workflow/store.js
Labels: enhancement

#4002 Correctly render object title in SignalEngagementCombobox
  src/dispatch/static/dispatch/src/signal/engagement/SignalEngagementCombobox.vue
Labels: bug, UI/UX

#4007 Handle invalid JSONPath with KeyError, Exceptions, and add test cases
  src/dispatch/entity/service.py
  tests/entity/test_entity_service.py
Labels: bug

#4010 Fixing project and case type select
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
  src/dispatch/static/dispatch/src/project/ProjectSelect.vue
  tests/static/e2e/pages/report-incident-page.ts
Labels: bug

#4017 Bugfix/cant add assignee
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/HandoffDialog.vue
  src/dispatch/static/dispatch/src/case/Participant.vue
  src/dispatch/static/dispatch/src/case/ReportReceiptCard.vue
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/components/ParticipantSelect.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentDialogFilter.vue
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/HandoffDialog.vue
  src/dispatch/static/dispatch/src/incident/Participant.vue
  src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/static/dispatch/src/task/NewEditSheet.vue
  src/dispatch/static/dispatch/src/task/store.js
Labels: bug

#4008 Do not send case traige reminders if there is no assignee.
  src/dispatch/case/messaging.py
Labels: bug

#4033 Dark mode not persisting through reloads
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
Labels: bug

#4012 Fixes signal instance deduplication check.
  src/dispatch/signal/flows.py
Labels: bug

#4034 Swallow send exceptions
  src/dispatch/evergreen/scheduled.py
  src/dispatch/plugins/dispatch_slack/enums.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#3974 Adds Case Page, Signal Graph, and supporting components
  src/dispatch/case/flows.py
  src/dispatch/case/service.py
  src/dispatch/case/views.py
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/atomics/Hotkey.vue
  src/dispatch/static/dispatch/src/case/CaseAttributesDrawer.vue
  src/dispatch/static/dispatch/src/case/CaseResolutionSearchPopover.vue
  src/dispatch/static/dispatch/src/case/CaseSignalInstanceTab.vue
  src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue
  src/dispatch/static/dispatch/src/case/CaseTabs.vue
  src/dispatch/static/dispatch/src/case/CaseTimelineTabV1.vue
  src/dispatch/static/dispatch/src/case/EditSheet.vue
  src/dispatch/static/dispatch/src/case/EscalateButton.vue
  src/dispatch/static/dispatch/src/case/GraphTab.vue
  src/dispatch/static/dispatch/src/case/Page.vue
  src/dispatch/static/dispatch/src/case/PageHeader.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/TimelineTab.vue
  src/dispatch/static/dispatch/src/case/api.js
  src/dispatch/static/dispatch/src/case/priority/CasePrioritySearchPopover.vue
  src/dispatch/static/dispatch/src/case/severity/CaseSeveritySearchPopover.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeSearchPopover.vue
  src/dispatch/static/dispatch/src/components/DMenu.vue
  src/dispatch/static/dispatch/src/components/DTooltip.vue
  src/dispatch/static/dispatch/src/components/LockButton.vue
  src/dispatch/static/dispatch/src/components/RichEditor.vue
  src/dispatch/static/dispatch/src/components/SearchPopover.vue
  src/dispatch/static/dispatch/src/composables/useEventListener.ts
  src/dispatch/static/dispatch/src/composables/useHotkey.ts
  src/dispatch/static/dispatch/src/participant/ParticipantAvatarGroup.vue
  src/dispatch/static/dispatch/src/participant/ParticipantSearchPopover.vue
  src/dispatch/static/dispatch/src/project/ProjectSearchPopover.vue
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/signal/NewRawSignalViewer.vue
  src/dispatch/static/dispatch/src/signal/SignalInstanceNode.vue
  src/dispatch/static/dispatch/src/styles/index.scss
Labels: enhancement, UI/UX, javascript

#4045 Show the value of the Entity in Slack snooze dropdown
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#4044 Tries a different approach to signal instance table filtering
  src/dispatch/database/revisions/tenant/versions/2023-11-29_bdaeabba3e53.py
  src/dispatch/static/dispatch/src/signal/store.js
Labels: enhancement

#4046 Setup `eslint` for TypeScript and resolve all errors
  src/dispatch/static/dispatch/.eslintrc.js
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/case/CaseResolutionSearchPopover.vue
  src/dispatch/static/dispatch/src/case/CaseSignalInstanceTab.vue
  src/dispatch/static/dispatch/src/case/GraphTab.vue
  src/dispatch/static/dispatch/src/case/TimelineTab.vue
  src/dispatch/static/dispatch/src/case/priority/CasePrioritySearchPopover.vue
  src/dispatch/static/dispatch/src/case/severity/CaseSeveritySearchPopover.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeSearchPopover.vue
  src/dispatch/static/dispatch/src/components/DMenu.vue
  src/dispatch/static/dispatch/src/components/DTooltip.vue
  src/dispatch/static/dispatch/src/components/SearchPopover.vue
  src/dispatch/static/dispatch/src/participant/ParticipantAvatarGroup.vue
  src/dispatch/static/dispatch/src/participant/ParticipantSearchPopover.vue
  src/dispatch/static/dispatch/src/project/ProjectSearchPopover.vue
  src/dispatch/static/dispatch/src/signal/SignalInstanceNode.vue
Labels: enhancement, javascript, techdebt

#4036 Bugfix/datewindow fix
  package-lock.json
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/components/DateWindowInput.vue
Labels: bug

#4047 Removes signal instance fingerprint column
  src/dispatch/case/models.py
  src/dispatch/database/revisions/tenant/versions/2023-11-29_580a18ec4c39.py
  src/dispatch/signal/models.py
  tests/factories.py
Labels: enhancement

#4055 Fix self closing custom component lint flag on DateWindowInput
  src/dispatch/static/dispatch/src/components/DateWindowInput.vue
Labels: bug, UI/UX, techdebt

#4056 Add UTC hover to relative times in timeline
  src/dispatch/static/dispatch/src/case/TimelineTab.vue
Labels: enhancement, UI/UX

#4057 debounce `tiptatp` editor save to not interfere with typing
  src/dispatch/static/dispatch/src/case/CaseAttributesDrawer.vue
  src/dispatch/static/dispatch/src/case/Page.vue
  src/dispatch/static/dispatch/src/components/RichEditor.vue
Labels: bug, enhancement, UI/UX

#4058 Only update signal definition fields if provided
  src/dispatch/signal/service.py
Labels: bug

#4059 Display label correctly for SignalInstanceNode
  src/dispatch/static/dispatch/src/case/GraphTab.vue
Labels: bug

#4060 Show default participant icon and fix label for reporter
  src/dispatch/static/dispatch/src/participant/ParticipantSearchPopover.vue
Labels: enhancement

#4063 Renames Investigation Write-Up to Resolution and move button to top
  src/dispatch/static/dispatch/src/case/CaseAttributesDrawer.vue
Labels: enhancement

#4061 Change `View` button for Case Slack message to use `id` as route parameter
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug
