Repository Netflix/dispatch, pull requests merged in 2024-07, with the labels that each got.

#4899 Create case costs, case cost types, and case cost models
  src/dispatch/case/models.py
  src/dispatch/case/type/models.py
  src/dispatch/case_cost/models.py
  src/dispatch/case_cost_type/models.py
  src/dispatch/database/revisions/tenant/versions/2024-06-28_15a8d3228123.py
  src/dispatch/participant_activity/models.py
  tests/conftest.py
  tests/factories.py
Labels: enhancement

#4904 feat: simplify Slack `make_call` tenacity retry and wait strategy
  src/dispatch/plugins/dispatch_slack/service.py
Labels: enhancement

#4906 Don't retry adding users if they are already in the channel.
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#4907 feat: add self-join button and api to cases
  src/dispatch/auth/permissions.py
  src/dispatch/case/models.py
  src/dispatch/case/views.py
  src/dispatch/static/dispatch/src/case/CaseStatus.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/api.js
  src/dispatch/static/dispatch/src/case/store.js
Labels: enhancement

#4912 Adds Slack error code skip retry
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#4913 Skip retries for defined SlackAPIErrorCode
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#4914 style: define `__contains__` on `DispatchEnum` for easy checking, use in slack `should_retry`
  src/dispatch/enums.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: enhancement

#4915 refactor: use `StrEnum` python3.11 feature for `DispatchEnum`
  src/dispatch/enums.py
Labels: enhancement

#4930 bugfix: don't update channel topic on assignee role change for thread cases
  src/dispatch/case/flows.py
Labels: bug

#4931 chore: improve Duo user not found error messaging
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug, enhancement

#4932 chore: improve Duo timeout error message
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug, enhancement

#4916 Adding notifications to dedicated channel cases
  src/dispatch/case/flows.py
  src/dispatch/case/messaging.py
  src/dispatch/messaging/email/utils.py
  src/dispatch/messaging/strings.py
Labels: enhancement

#4933 bugfix: no __contains__ on StrEnum until 3.12
  src/dispatch/enums.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#4937 Resolving a case thread should update the other case resources.
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4939 bugfix: only update signal message if case conversation is not None
  src/dispatch/signal/flows.py
Labels: bug

#4938 Turns off unfurling links and adds conversation link to help tips
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug, enhancement

#4940 feat(signals): FIFO queue on signal processing, refactor into individual functions, other minor improvements
  src/dispatch/cli.py
  src/dispatch/signal/service.py
Labels: enhancement

#4948 bugfix(signal): test signal process without with_locked()
  src/dispatch/signal/service.py
Labels: bug

#4949 Do not overwrite description field
  src/dispatch/case/flows.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4966 Fixes issue where ephemeral welcome message was sent every time someone is @ mentioned
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4967 Rewrite case welcome into add_or_reactivate flow
  src/dispatch/case/flows.py
  src/dispatch/case/messaging.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4980 revet: switch back to old process_signals code, keep new functions
  src/dispatch/cli.py
Labels: enhancement

#4982 refactor(signal): move process functions to flows.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/service.py
Labels: bug

#4958 Adds form scoring based on scoring schema
  src/dispatch/database/revisions/tenant/versions/2024-07-12_25b8b5829158.py
  src/dispatch/forms/models.py
  src/dispatch/forms/scoring.py
  src/dispatch/forms/service.py
  src/dispatch/static/dispatch/src/forms/store.js
  src/dispatch/static/dispatch/src/forms/table/AttorneyEditForm.vue
  src/dispatch/static/dispatch/src/forms/table/Table.vue
Labels: enhancement

#4965 Updating Forms documentation
  docs/docs/user-guide/incidents/forms.mdx
  docs/static/img/attorney-section.png
  docs/static/img/example-risk-score.png
Labels: documentation

#4981 Removes ability to reassign task to another incident
  src/dispatch/static/dispatch/src/task/NewEditSheet.vue
Labels: bug

#4988 Formatting fix
  docs/docs/user-guide/incidents/forms.mdx
Labels: documentation

#4989 Small formatting fix
  docs/docs/user-guide/incidents/forms.mdx
Labels: documentation

#4908 Provides option of an alternative folder structure
  src/dispatch/database/revisions/tenant/versions/2024-07-19_a812a4cf61e1.py
  src/dispatch/document/flows.py
  src/dispatch/project/models.py
  src/dispatch/static/dispatch/src/project/NewEditSheet.vue
  src/dispatch/static/dispatch/src/project/store.js
  src/dispatch/static/dispatch/src/tag_type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/tag_type/TagTypeSelect.vue
  src/dispatch/storage/flows.py
  src/dispatch/tag_type/models.py
  src/dispatch/tag_type/service.py
Labels: enhancement

#4998 Allows tagging of runbooks
  src/dispatch/database/revisions/tenant/versions/2024-07-22_ef17416626ff.py
  src/dispatch/document/models.py
  src/dispatch/document/service.py
  src/dispatch/static/dispatch/src/document/runbook/RunbookNewEditSheet.vue
  src/dispatch/static/dispatch/src/document/runbook/RunbookTable.vue
  src/dispatch/static/dispatch/src/document/runbook/store.js
  src/dispatch/static/dispatch/src/tag/TagPicker.vue
  src/dispatch/static/dispatch/src/tag_type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/tag_type/Table.vue
  src/dispatch/tag_type/models.py
Labels: enhancement

#5001 Fixes issue with join case button
  src/dispatch/messaging/strings.py
Labels: bug

#5002 security: Do not render blocks in Jinja message templates
  src/dispatch/messaging/email/filters.py
  tests/conftest.py
  tests/factories.py
  tests/messaging/test_messaging.py
Labels: bug, security

#5007 ui: only allow escalation on case page, not in edit sheet
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
Labels: bug, UI/UX

#5008 plugin(slack): do not allow escalate status change in update case slack modal
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug, UI/UX

#5021 bugfix(case/ui): some escalate dialog resources never exit load state
  src/dispatch/static/dispatch/src/case/EscalateDialog.vue
  src/dispatch/static/dispatch/src/case/store.js
Labels: bug, UI/UX, javascript
