Repository Netflix/dispatch, pull requests merged in 2024-11, with the labels that each got.

#5420 techdebt(plugin): deprecates the document resolver plugin and its code
  src/dispatch/incident/flows.py
  src/dispatch/incident/messaging.py
  src/dispatch/plugins/bases/__init__.py
  src/dispatch/plugins/bases/document_resolver.py
  src/dispatch/plugins/dispatch_core/config.py
  src/dispatch/plugins/dispatch_core/plugin.py
Labels: techdebt

#5416 feat(genai): elevates GenAI feature to its own service library
  src/dispatch/ai/exceptions.py
  src/dispatch/ai/service.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: enhancement

#5421 feat(slack): add signal snooze channel notification for visibility
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: enhancement

#5419 fix(slack): skip after hours notification if no participant
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug, techdebt

#5415 fix(plugin): create fallback ticket in case Jira fails
  src/dispatch/incident/flows.py
  src/dispatch/plugins/dispatch_jira/plugin.py
  src/dispatch/static/dispatch/src/incident/ResourcesTab.vue
  src/dispatch/ticket/flows.py
Labels: bug, techdebt

#5408 feat(incident): Show the last update time of response costs in the UI
  src/dispatch/incident_cost/models.py
  src/dispatch/static/dispatch/src/incident/CostsTab.vue
Labels: enhancement

#5371 fix(case): handle no case conversation
  src/dispatch/case/flows.py
Labels: bug, techdebt

#5378 Timeline Error handling
  src/dispatch/event/flows.py
  src/dispatch/event/service.py
  src/dispatch/incident/views.py
  src/dispatch/plugins/dispatch_google/docs/plugin.py
  src/dispatch/static/dispatch/src/incident/store.js
Labels: bug

#5428 Fix docstring for get_definition and get_document routes
  src/dispatch/definition/views.py
  src/dispatch/document/views.py
Labels: bug, documentation

#5430 fix(groups/plugin): log when group no longer exists
  src/dispatch/plugins/dispatch_google/groups/plugin.py
Labels: bug, techdebt

#5429 enhancement(slack): adding slash command and button to manually engage user for mfa prompt
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/config.py
Labels: enhancement

#5432 fix(slack): using participant id for manual engagement
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#5349 Removes obsolete attribute version from docker-compose file
  docker/docker-compose.yml
Labels: docker, techdebt

#5435 tests(case): adds case reporting test
  data/dispatch-sample-data.dump
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  tests/static/e2e/fixtures/dispatch-fixtures.ts
  tests/static/e2e/pages/report-case-page.ts
  tests/static/e2e/report-case.spec.ts
  tests/static/e2e/routes.ts
Labels: tests

#5440 fix(slack): remove mfa button for now
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#5445 fix(plugin): check if challenge is already approved before raising exception
  src/dispatch/plugins/dispatch_core/plugin.py
Labels: bug

#5448 ui(mfa): dont require button click to validate mfa, do automatically
  src/dispatch/static/dispatch/src/auth/Mfa.vue
  src/dispatch/static/dispatch/src/tests/Mfa.spec.js
Labels: enhancement, javascript

#5444 fix(ui): use local event to prevent slow down
  src/dispatch/static/dispatch/src/incident/EditEventDialog.vue
Labels: bug

#5450 feat(case): add ability to MFA challenge user in case thread
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#5443 enhancement(ui): allow multiple assignee and participants
  src/dispatch/static/dispatch/src/case/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/router/utils.js
  src/dispatch/static/dispatch/src/search/utils.js
Labels: enhancement

#5449 chore(deps): bumping dependencies
  requirements-base.in
  requirements-base.txt
  requirements-dev.in
  requirements-dev.txt
  setup.cfg
  setup.py
  src/dispatch/conversation/flows.py
  src/dispatch/database/service.py
Labels: dependencies

#5431 fix(db): cleaning up alembic migration files
  src/dispatch/database/revisions/tenant/versions/2024-11-04_928b725d64f6.py
  src/dispatch/signal/models.py
Labels: bug, techdebt

#5455 chore(deps): ensure sentry_sdk is pinned at 1.45.0
  requirements-base.in
  requirements-base.txt
Labels: dependencies

#5456 fix(db): fixes migration to ensure index and column exist before dropping
  src/dispatch/database/revisions/tenant/versions/2024-11-04_928b725d64f6.py
Labels: bug

#5459 feat(ui): add dedicated status tab for can report in incident edit sheet
  src/dispatch/static/dispatch/src/incident/EditSheet.vue
  src/dispatch/static/dispatch/src/incident/TimelineReportTab.vue
  src/dispatch/static/dispatch/src/tests/TimelineReportTab.spec.js
Labels: enhancement

#5461 fix(db): ensure type is str before trying to deserialize
  src/dispatch/database/service.py
Labels: bug

#5457 fix(logging): log case has been linked to incident when incident has a name
  src/dispatch/case/flows.py
Labels: bug

#5470 ui: remove 'incident participant' string from report tab
  src/dispatch/static/dispatch/src/incident/TimelineReportTab.vue
Labels: enhancement, javascript

#5471 Removes option to delete a signal definition
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
  src/dispatch/static/dispatch/src/signal/DeleteDialog.vue
  src/dispatch/static/dispatch/src/signal/Table.vue
  tests/signal/test_signal_service.py
Labels: techdebt

#5462 fix(case/ui): fixes case page to show escalation
  src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue
  src/dispatch/static/dispatch/src/case/EscalateDialog.vue
  src/dispatch/static/dispatch/src/case/store.js
Labels: bug, techdebt

#5472 fix(slack): fixing append elements when adding buttons
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#5460 feat(scheduler): keep participant list in sync
  src/dispatch/incident/scheduled.py
  src/dispatch/plugins/dispatch_slack/enums.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: enhancement, techdebt

#5458 fix(ui/ux): show zero escalated cases if there are none
  src/dispatch/static/dispatch/src/dashboard/case/CaseOverview.vue
Labels: bug

#5474 Revert "chore(deps): bump vuetify from 3.7.3 to 3.7.4 in /src/dispatch/static/dispatch"
  src/dispatch/static/dispatch/package-lock.json
Labels: dependencies

#5473 ui(case): fix misaligned instance selector
  src/dispatch/static/dispatch/src/case/CaseSignalInstanceTab.vue
Labels: enhancement, javascript

#5483 Revert "Removes option to delete a signal definition"
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
  src/dispatch/static/dispatch/src/signal/DeleteDialog.vue
  src/dispatch/static/dispatch/src/signal/Table.vue
  tests/signal/test_signal_service.py
Labels: chore

#5484 Removes ability to delete signal definitions in Web UI
  src/dispatch/static/dispatch/src/signal/DeleteDialog.vue
  src/dispatch/static/dispatch/src/signal/Table.vue
Labels: enhancement

#5485 feat(slack plugin): improve user experience when resolving cases via Slack
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: enhancement

#5498 fix(slack): use case_id for mfa button metadata
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#5486 fix(ui): fixes broken resize component
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/incident/EditSheet.vue
  src/dispatch/static/dispatch/src/main.js
Labels: bug

#5503 fix(metrics): if filter spec is string, load to dict
  src/dispatch/incident/metrics.py
Labels: bug

#5439 Enables usage of welcome message template for creating case ephemeral welcome messages
  src/dispatch/case/flows.py
  src/dispatch/case/messaging.py
  src/dispatch/conversation/flows.py
  src/dispatch/messaging/email/utils.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: enhancement

#5500 (Bug/case) Do not fetch channel activity for threads.
  src/dispatch/plugins/dispatch_slack/events.py
Labels: bug

#5505 fix(ui): self closing tag
  src/dispatch/static/dispatch/src/auth/Mfa.vue
Labels: bug

#5522 Do not throw errors when trying to list members from a non-existent Google Group
  src/dispatch/plugins/dispatch_google/groups/plugin.py
Labels: bug

#5506 feat(slack): remove signal text from manual mfa engage and add user to channel
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#5528 fix(slack): ensure only one slash in tags
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug, techdebt

#5530 feat(slack): add users to threaded case on mention
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/models.py
Labels: enhancement
