Repository Netflix/dispatch, pull requests merged in 2024-12, with the labels that each got.

#5565 feat(mfa): change mfa prompt link to button
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: enhancement

#5553 fix(task): be sure to add user to incident before sending ephemeral message
  src/dispatch/task/service.py
Labels: bug

#5507 fix(ui): fixes edit pane on case type
  src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
  src/dispatch/static/dispatch/src/service/ServiceSelect.vue
Labels: bug

#5554 fix(groups): limit group_key username to first 60 characters
  src/dispatch/plugins/dispatch_google/groups/plugin.py
Labels: bug

#5576 feat(ui): show message if no tactical reports
  src/dispatch/static/dispatch/src/incident/TimelineReportTab.vue
Labels: enhancement

#5582 feat(ui): add incident summary to Reports tab
  src/dispatch/database/revisions/tenant/versions/2024-12-05_575ca7d954a8.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/models.py
  src/dispatch/incident/scheduled.py
  src/dispatch/incident/service.py
  src/dispatch/incident/views.py
  src/dispatch/messaging/strings.py
  src/dispatch/static/dispatch/src/incident/TimelineReportTab.vue
  src/dispatch/static/dispatch/src/incident/api.js
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/static/dispatch/src/styles/timeline.css
Labels: enhancement

#5583 fix(ui): filter incident type by selected project
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Labels: bug

#5523 feat(dispatch aws plugin): adds support for decompressing zlib compressed signals
  src/dispatch/plugins/bases/signal_consumer.py
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: enhancement

#5589 bugfix(aws-sqs-signal-consumer-plugin): fixes logic
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: bug

#5592 feat(signal processing): adds better logging for troubleshooting purposes
  src/dispatch/plugins/dispatch_aws/plugin.py
  src/dispatch/signal/service.py
Labels: enhancement

#5593 bugfix(aws-plugin-signal-consume): always json.loads() message body message
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: bug

#5594 feat(dispatch-aws-plugin): better logging
  src/dispatch/plugins/dispatch_aws/plugin.py
  src/dispatch/signal/service.py
Labels: enhancement

#5595 bugfix(signal service): fixes logging message
  src/dispatch/signal/service.py
Labels: bug

#5596 fix(signal): retrieve kv with get
  src/dispatch/signal/service.py
Labels: bug

#5597 fix(signal): get name from raw dictionary
  src/dispatch/signal/service.py
Labels: bug

#5575 feat(ticket): update ticket metadata on change of incident type
  src/dispatch/incident/service.py
  src/dispatch/plugins/dispatch_core/plugin.py
  src/dispatch/plugins/dispatch_jira/plugin.py
  src/dispatch/ticket/flows.py
Labels: enhancement

#5598 fix(ui): only show enabled incident types
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Labels: bug

#5581 feat(auth): aws application load balancer plugin
  docs/docs/administration/settings/server.mdx
  setup.py
  src/dispatch/config.py
  src/dispatch/plugins/dispatch_core/plugin.py
Labels: enhancement

#5604 fix(case): log warning instead of throw exception
  src/dispatch/case/messaging.py
  src/dispatch/conversation/flows.py
Labels: bug

#5605 feat(ui): adds button to go to legacy edit pane
  src/dispatch/static/dispatch/src/case/CaseTabs.vue
Labels: enhancement

#5607 fix(genai): incident summary generate takes only kw args
  src/dispatch/incident/flows.py
Labels: bug

#5564 Add tags and tickets fields to get cases request
  .vscode/settings.json
  src/dispatch/case/models.py
  src/dispatch/case/views.py
  src/dispatch/database/service.py
  tests/conftest.py
  tests/database/test_service.py
  tests/factories.py
Labels: enhancement

#5617 fix(ui): fixes property access error
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Labels: bug

#5606 fix(ui): show error in UI if signal filter name already exists
  src/dispatch/signal/views.py
  src/dispatch/static/dispatch/src/signal/engagement/store.js
  src/dispatch/static/dispatch/src/signal/filter/store.js
Labels: bug

#5616 feat(ui): allow project to have a display name separate from its key
  src/dispatch/case/models.py
  src/dispatch/database/revisions/tenant/versions/2024-12-12_2d9e4d392ea4.py
  src/dispatch/incident/models.py
  src/dispatch/incident/priority/models.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/project/models.py
  src/dispatch/static/dispatch/src/case/CaseSummaryTable.vue
  src/dispatch/static/dispatch/src/case/ReportReceiptCard.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/priority/CasePriorityCombobox.vue
  src/dispatch/static/dispatch/src/case/severity/CaseSeverityCombobox.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeCombobox.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentDrillDownTable.vue
  src/dispatch/static/dispatch/src/data/query/QuerySummaryTable.vue
  src/dispatch/static/dispatch/src/data/query/Table.vue
  src/dispatch/static/dispatch/src/data/source/SourceSummaryTable.vue
  src/dispatch/static/dispatch/src/data/source/Table.vue
  src/dispatch/static/dispatch/src/document/DocumentSummaryTable.vue
  src/dispatch/static/dispatch/src/feedback/incident/Table.vue
  src/dispatch/static/dispatch/src/feedback/service/Table.vue
  src/dispatch/static/dispatch/src/forms/table/Table.vue
  src/dispatch/static/dispatch/src/incident/IncidentSummaryTable.vue
  src/dispatch/static/dispatch/src/incident/ReportReceiptCard.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPriorityCombobox.vue
  src/dispatch/static/dispatch/src/incident/severity/IncidentSeverityCombobox.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeCombobox.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
  src/dispatch/static/dispatch/src/project/NewEditSheet.vue
  src/dispatch/static/dispatch/src/project/ProjectCombobox.vue
  src/dispatch/static/dispatch/src/project/ProjectSelect.vue
  src/dispatch/static/dispatch/src/project/Table.vue
  src/dispatch/static/dispatch/src/signal/Table.vue
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
  src/dispatch/static/dispatch/src/tag/TagFilterAutoComplete.vue
  src/dispatch/static/dispatch/src/tag/TagSummaryTable.vue
  src/dispatch/static/dispatch/src/tag_type/TagTypeFilterCombobox.vue
  src/dispatch/static/dispatch/src/task/Table.vue
  src/dispatch/static/dispatch/src/task/TaskSummaryTable.vue
Labels: enhancement

#5618 fix(case): close escalated case when associated incident is closed
  src/dispatch/incident/flows.py
Labels: enhancement

#5619 fix(models): reducing information for duplicates or associated incidents and cases
  src/dispatch/case/models.py
  src/dispatch/feedback/incident/models.py
  src/dispatch/incident/models.py
  src/dispatch/incident/views.py
  src/dispatch/task/models.py
Labels: bug, security

#5613 Allow export of incident/case tags
  src/dispatch/static/dispatch/src/case/TableExportDialog.vue
  src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
Labels: enhancement

#5453 tests(incident): Increase test coverage for report flows and incident severity service.
  src/dispatch/incident/severity/service.py
  tests/conftest.py
  tests/incident_severity/test_incident_severity_service.py
  tests/report/test_report_flows.py
Labels: enhancement

#5447 fix(docker-image): downgrade Python base image and remove pkg_resources
  docker/Dockerfile
  requirements-base.in
  requirements-base.txt
  src/dispatch/common/utils/cli.py
Labels: bug

#5623 fix(cli): use new entry point method
  src/dispatch/common/utils/cli.py
Labels: bug

#5588 chore(ci): test docker build on pull request
  .github/workflows/publish-image-test.yml
Labels: enhancement, docker

#5625 fix(db): make migration statement conditional
  src/dispatch/database/revisions/tenant/versions/2024-11-04_928b725d64f6.py
Labels: bug

#5529 refactor(case): Refactor case cost model.
  src/dispatch/case/type/service.py
  src/dispatch/case_cost/models.py
  src/dispatch/case_cost/scheduled.py
  src/dispatch/case_cost/service.py
  src/dispatch/participant_activity/service.py
  src/dispatch/static/dispatch/src/case/CostsTab.vue
  tests/case_cost/test_case_cost_service.py
Labels: techdebt

#5626 fix(ui): default incident project should be null
  src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
Labels: bug

#5632 End polling for case details after conversation has been created.
  src/dispatch/static/dispatch/src/case/store.js
Labels: bug

#5637 fix(ui): remove html from summary before display
  src/dispatch/static/dispatch/src/incident/TimelineReportTab.vue
Labels: bug

#5639 Adds additional permissions and switches to minimal
  src/dispatch/workflow/models.py
  src/dispatch/workflow/views.py
Labels: bug, security

#5638 fix(slack): email not in profile dict
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#5640 fix(slack): fixing regression in update incident modal
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#5645 fix: updating main branch name
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-docs-test.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/python.yml
  README.md
  docker/Dockerfile
  docs/docs/administration/installation.mdx
  docs/docs/administration/settings/messaging.mdx
  docs/docs/support.mdx
  docs/docusaurus.config.js
Labels: enhancement
