Repository Netflix/dispatch, pull requests merged in 2024-08, with the labels that each got.

#5032 Add logging for case status transitions
  src/dispatch/case/flows.py
Labels: feature

#5034 Adding structured data
  src/dispatch/case/flows.py
Labels: enhancement

#5037 Adds detection lifecyle to signal model
  src/dispatch/conversation/flows.py
  src/dispatch/database/revisions/tenant/versions/2024-08-05_71cd7ed999c4.py
  src/dispatch/signal/models.py
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
  src/dispatch/static/dispatch/src/signal/Table.vue
  src/dispatch/static/dispatch/src/signal/store.js
Labels: enhancement

#5039 Makes lifecycle v-text field readonly
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
Labels: enhancement

#5046 Moving Slack button update to after case escalation flow
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#5047 bugfix(case/slack): added_by reason none check on participant.added_by
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#5003 Enable users to view and update existing search filter expressions
  src/dispatch/static/dispatch/src/search/EditDialog.vue
Labels: enhancement

#5065 Organize case select by oncall team
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
Labels: enhancement

#5066 Removes requirement for lifecycle field
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
Labels: bug

#5075 Disables tabs in incident edit until populated
  src/dispatch/static/dispatch/src/incident/EditSheet.vue
Labels: bug

#5092 Allow scribes to create a timeline event
  src/dispatch/auth/permissions.py
  src/dispatch/incident/views.py
Labels: bug

#5105 Removes subqueries to ensure pagination works
  src/dispatch/case/models.py
  src/dispatch/incident/models.py
Labels: bug

#5093 Truncate the case resolution reason text due to Slack limit
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/config.py
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#5115 Modifying max limit
  src/dispatch/plugins/dispatch_slack/config.py
Labels: bug

#5113 Adding some better error handling to sqs consume
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: bug

#5114 Refact(signals)/create instance
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
Labels: enhancement

#5118 enhancement(cli/consume): improve thread exception handling in cli consumer
  src/dispatch/cli.py
  src/dispatch/plugin/service.py
  src/dispatch/project/service.py
Labels: enhancement

#5117 refactor(plugins/aws): error handling, logging, types, and early returns
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: enhancement

#5129 Adding project setting to allow visibility selection of incident command
  src/dispatch/database/revisions/tenant/versions/2024-08-26_d6b3853be8e4.py
  src/dispatch/project/models.py
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/project/NewEditSheet.vue
  src/dispatch/static/dispatch/src/project/store.js
Labels: enhancement

#4900 Enable backend functionality of calculating case costs.
  src/dispatch/__init__.py
  src/dispatch/case/models.py
  src/dispatch/case/scheduled.py
  src/dispatch/case/service.py
  src/dispatch/case/type/service.py
  src/dispatch/case_cost/scheduled.py
  src/dispatch/case_cost/service.py
  src/dispatch/case_cost_type/config.py
  src/dispatch/case_cost_type/service.py
  src/dispatch/cli.py
  src/dispatch/incident_cost/service.py
  src/dispatch/participant_activity/service.py
  src/dispatch/plugins/base/v1.py
  src/dispatch/plugins/dispatch_test/conversation.py
  src/dispatch/project/flows.py
  tests/case/test_case_messaging.py
  tests/case/test_case_service.py
  tests/case_cost/test_case_cost_service.py
  tests/case_cost_type/test_case_cost_type_service.py
  tests/case_type/test_case_type_service.py
  tests/conftest.py
  tests/incident_cost/test_incident_cost_service.py
Labels: enhancement

#5131 fix(plugins): aws consume plugin transaction management
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: bug

#5132 Asks user to type database hostname and name before asking for confirmation to drop database
  src/dispatch/cli.py
Labels: enhancement

#5133 fix(plugin/aws): catch integrity error and log warning
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: bug

#5138 Delete unused code and fix logging.
  src/dispatch/case_cost/service.py
  src/dispatch/participant_activity/service.py
Labels: techdebt

#5139 Fixes plugin instance call to fetch events.
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#5144 refactor(plugin/aws): single threaded consume, call rollback
  src/dispatch/cli.py
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: bug
