Repository Netflix/dispatch, pull requests merged in 2024-04, with the labels that each got.

#4552 Updates classic cost model to append new response costs instead of overwriting them.
  src/dispatch/incident/flows.py
  src/dispatch/incident_cost/service.py
  tests/factories.py
  tests/incident_cost/test_incident_cost_service.py
Labels: enhancement

#4555 Validating uuid before storing
  src/dispatch/signal/service.py
Labels: bug

#4579 Fixes calls to renamed incident cost functions
  src/dispatch/incident_cost/scheduled.py
Labels: bug

#4580 [Bug] Adding the message template in SlackAPIError when channel is archived
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#4581 [Bug] moved participant lookup
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#4582 [Bugs] Check incident status before re-adding IC
  src/dispatch/incident/flows.py
Labels: bug

#4587 Fixing date in date picker from modelValue
  src/dispatch/static/dispatch/src/components/DateWindowInput.vue
Labels: bug

#4586 Send ephemeral message when participant is added to an incident due to an assigned task
  src/dispatch/database/service.py
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/strings.py
  src/dispatch/static/dispatch/src/task/Table.vue
  src/dispatch/task/service.py
Labels: enhancement

#4572 Adds enabled to project to hide disabled projects from new incidents and cases
  src/dispatch/database/revisions/tenant/versions/2024-04-02_71cb25c06fa0.py
  src/dispatch/project/models.py
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/project/NewEditSheet.vue
  src/dispatch/static/dispatch/src/project/ProjectSelect.vue
  src/dispatch/static/dispatch/src/project/Table.vue
  src/dispatch/static/dispatch/src/project/store.js
Labels: enhancement

#4596 DISDEV-221 Fix get_by_primary_or_external_id by testing for uuid
  src/dispatch/signal/service.py
Labels: bug

#4597 Handle slack rate limit for does_user_exist
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#4611 Adding exception handling around message send
  src/dispatch/incident/messaging.py
Labels: bug

#4551 [Enhancement] - Cases, but they can be Slack channels
  src/dispatch/case/flows.py
  src/dispatch/case/models.py
  src/dispatch/case/service.py
  src/dispatch/conversation/flows.py
  src/dispatch/conversation/service.py
  src/dispatch/database/revisions/tenant/versions/2024-04-09_3a33bc153e7e.py
  src/dispatch/enums.py
  src/dispatch/group/flows.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/messaging.py
  src/dispatch/incident/service.py
  src/dispatch/plugins/dispatch_slack/ack.py
  src/dispatch/plugins/dispatch_slack/bolt.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/config.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/messages.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/models.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/static/dispatch/src/case/CaseResolutionSearchPopover.vue
  src/dispatch/static/dispatch/src/case/CaseTabs.vue
  src/dispatch/static/dispatch/src/case/PageHeader.vue
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
  src/dispatch/types.py
Labels: enhancement, help wanted

#4617 pass signal.id on delete
  src/dispatch/signal/views.py
Labels: bug

#4631 [Copy] - Set the correct modal message depending on escalation source for Cases
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4634 Fixes incident naming and incident resource creation during active incident creation.
  src/dispatch/incident/flows.py
Labels: bug

#4645 bug: pagerduty_plugin - Updates method for accessing current on-call email
  src/dispatch/plugins/dispatch_pagerduty/service.py
Labels: bug

#4646 Cases should be created with a conversation target
  src/dispatch/case/service.py
  src/dispatch/case/views.py
  src/dispatch/static/dispatch/src/components/NotificationSnackbarsWrapper.vue
  tests/case/test_case_service.py
  tests/factories.py
Labels: bug

#4640 Clicking escalate in the status group brings up escalation dialog
  src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionForm.vue
Labels: bug

#4651 Fixing Report Case card to ensure case type reflows on project change
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Labels: bug

#4661 Don't send a conversation update if no thread
  src/dispatch/case/flows.py
Labels: bug

#4635 bug: Updates is_bot to support bots defined in apps.event.authorizations.list
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug

#4655 bug: Accurately captures severity level at time of incident report
  src/dispatch/incident/service.py
Labels: bug

#4663 Fix == True ruff check
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug
