Repository Netflix/dispatch, pull requests merged in 2024-05, with the labels that each got.

#4647 Move cost models from incident to incident types
  docs/docs/administration/settings/cost_model.mdx
  docs/docs/administration/settings/incident/incident-type.mdx
  src/dispatch/database/revisions/tenant/versions/2024-04-22_50e99c66e72f.py
  src/dispatch/incident/models.py
  src/dispatch/incident/service.py
  src/dispatch/incident/type/models.py
  src/dispatch/incident/type/service.py
  src/dispatch/incident_cost/service.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionForm.vue
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/static/dispatch/src/incident/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident/type/store.js
  tests/factories.py
  tests/incident_cost/test_incident_cost_service.py
  tests/incident_type/test_incident_type_service.py
Labels: enhancement

#4685 Incident costs are only updated for non-closed incidents.
  tests/incident_type/test_incident_type_service.py
Labels: bug

#4686 Cases with dedicated channels do not require conversation targets.
  src/dispatch/case/service.py
  tests/case/test_case_service.py
Labels: bug

#4684 [Refactor] - Default dedicated case channel, no tags on report form
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/case/store.js
Labels: enhancement

#4662 Archive channel when closing dedicated case channel
  src/dispatch/case/flows.py
  src/dispatch/conversation/flows.py
  src/dispatch/event/service.py
  src/dispatch/incident/flows.py
Labels: bug

#4687 Revert "Bump sentry-sdk from 1.45.0 to 2.1.1"
  requirements-base.txt
Labels: bug

#4699 Validate IncidentUpdate's incident_type field against the retrieved incident type.
  src/dispatch/incident/service.py
Labels: bug

#4700 Add welcome ephemeral message to dedicated channel cases
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#4698 [Bugfix] - We rename case -> incident channel twice
  src/dispatch/case/flows.py
Labels: bug

#4701 Changing to subject in add_conversation_bookmark
  src/dispatch/incident/flows.py
Labels: bug

#4706 bug: Fixes tags not showing up during incident report / update
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#4708 [Enhancement] - Case participant slack functions, ephemeral message, and escalate bug fix
  src/dispatch/case/flows.py
  src/dispatch/event/service.py
  src/dispatch/participant/flows.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
Labels: bug, enhancement

#4724 Initial assignee not populated for case update command modal
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug, enhancement

#4725 [Case] - Improves case ephemeral welcome message to include additional details
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#4726 Change topic in case channel on update
  src/dispatch/case/flows.py
  src/dispatch/conversation/flows.py
Labels: enhancement

#4707 Adding ability to filter cases by participant and assignee
  src/dispatch/database/service.py
  src/dispatch/static/dispatch/src/case/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/router/utils.js
  src/dispatch/static/dispatch/src/search/utils.js
Labels: enhancement

#4727 [Case] - Remove convo target from case type select since we default to dedicated channels
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
Labels: bug, UI/UX

#4728 [Bugfix] - Remove debug print in case Slack interactive
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4729 [Escalate] - Do not override user selected inc type with case type mapping
  src/dispatch/case/flows.py
Labels: bug

#4737 bugfix: Reporter can be None in resources flows
  src/dispatch/case/flows.py
Labels: bug

#4739 Changing extend to append
  src/dispatch/case/flows.py
Labels: bug

#4740 bugfix: Redundant participant add in case resource creation flow
  src/dispatch/case/flows.py
Labels: bug

#4743 Respect restricted case visibility
  src/dispatch/database/service.py
Labels: bug

#4603 Only show enabled projects in Slack project select
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#4610 Updating Slack close reminder to use Dispatch UI weblink
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/strings.py
Labels: bug

#4649 Adds optional attorney form to attorney review
  src/dispatch/database/revisions/tenant/versions/2024-05-17_b07bb852fd67.py
  src/dispatch/forms/models.py
  src/dispatch/forms/type/models.py
  src/dispatch/static/dispatch/src/forms/store.js
  src/dispatch/static/dispatch/src/forms/table/AttorneyEditForm.vue
  src/dispatch/static/dispatch/src/forms/table/store.js
  src/dispatch/static/dispatch/src/forms/types/NewEditSheet.vue
  src/dispatch/static/dispatch/src/forms/types/store.js
Labels: enhancement

#4745 Adds test cases for the case views
  src/dispatch/case/flows.py
  src/dispatch/case/models.py
  tests/case/test_case_views.py
Labels: enhancement

#4648 Increases code coverage requirement.
  .github/workflows/python.yml
Labels: enhancement

#4752 bugfix: Bolt event subscriptions get hijacked by one of the funcs registered
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#4754 bugfix: make document flows in use by both case and incident generalized
  src/dispatch/document/flows.py
Labels: bug

#4756 Replace Slack user_ids in messages with names
  src/dispatch/plugins/dispatch_slack/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#4770 bugfix: use ilike instead of like in participant search
  src/dispatch/static/dispatch/src/participant/ParticipantSearchPopover.vue
Labels: bug

#4675 Adding new project-level setting to enable/disable self join
  src/dispatch/case/flows.py
  src/dispatch/database/revisions/tenant/versions/2024-05-29_a836d4850a75.py
  src/dispatch/incident/models.py
  src/dispatch/project/models.py
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/status/IncidentStatus.vue
  src/dispatch/static/dispatch/src/project/NewEditSheet.vue
  src/dispatch/static/dispatch/src/project/store.js
Labels: enhancement
