Repository Netflix/dispatch, pull requests merged in 2024-01, with the labels that each got.

#4151 Adds custom incident forms
  src/dispatch/__init__.py
  src/dispatch/api.py
  src/dispatch/database/revisions/tenant/versions/2023-12-09_99d317cbc848.py
  src/dispatch/forms/enums.py
  src/dispatch/forms/models.py
  src/dispatch/forms/service.py
  src/dispatch/forms/type/models.py
  src/dispatch/forms/type/service.py
  src/dispatch/forms/type/views.py
  src/dispatch/forms/views.py
  src/dispatch/static/dispatch/.npmrc
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/preinstall.js
  src/dispatch/static/dispatch/src/forms/DeleteDialog.vue
  src/dispatch/static/dispatch/src/forms/EditForm.vue
  src/dispatch/static/dispatch/src/forms/api.js
  src/dispatch/static/dispatch/src/forms/store.js
  src/dispatch/static/dispatch/src/forms/table/AttorneyEditForm.vue
  src/dispatch/static/dispatch/src/forms/table/Table.vue
  src/dispatch/static/dispatch/src/forms/table/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/forms/table/store.js
  src/dispatch/static/dispatch/src/forms/types/DeleteDialog.vue
  src/dispatch/static/dispatch/src/forms/types/NewEditSheet.vue
  src/dispatch/static/dispatch/src/forms/types/Table.vue
  src/dispatch/static/dispatch/src/forms/types/api.js
  src/dispatch/static/dispatch/src/forms/types/store.js
  src/dispatch/static/dispatch/src/incident/EditSheet.vue
  src/dispatch/static/dispatch/src/incident/FormsTab.vue
  src/dispatch/static/dispatch/src/main.js
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/store.js
Labels: enhancement

#4181 Adds new Entity Type Creation dialog on case page and minor page polish
  src/dispatch/entity/service.py
  src/dispatch/entity_type/flows.py
  src/dispatch/entity_type/views.py
  src/dispatch/signal/service.py
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/case/CaseAttributesDrawer.vue
  src/dispatch/static/dispatch/src/case/CaseResolutionSearchPopover.vue
  src/dispatch/static/dispatch/src/case/CaseSignalInstanceTab.vue
  src/dispatch/static/dispatch/src/case/CaseTabs.vue
  src/dispatch/static/dispatch/src/case/Page.vue
  src/dispatch/static/dispatch/src/case/PageHeader.vue
  src/dispatch/static/dispatch/src/case/TimelineTab.vue
  src/dispatch/static/dispatch/src/components/RichEditor.vue
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialogV2.vue
  src/dispatch/static/dispatch/src/entity_type/api.js
  src/dispatch/static/dispatch/src/signal/NewRawSignalViewer.vue
  src/dispatch/static/dispatch/src/tests/extractKeyValue.spec.ts
  src/dispatch/static/dispatch/src/tests/findPath.spec.ts
  src/dispatch/static/dispatch/src/util/jpath.ts
  tests/entity/test_entity_service.py
Labels: enhancement

#4185 Fix sort by and descending on Case table
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/search/utils.js
Labels: bug

#4186 Add top level awaitable target environment
  src/dispatch/static/dispatch/vite.config.js
Labels: bug

#4187 Revert awaitable target environment build config
  src/dispatch/static/dispatch/vite.config.js
Labels: bug

#4188 Adds library to allow vite to parse top-level await
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/vite.config.js
Labels: bug

#4189 Hides search bar in signals table
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
Labels: bug

#4190 Temporarily disable await imports and other formkit pro code in main.js
  src/dispatch/static/dispatch/src/main.js
Labels: bug

#4202 Adds watcher back to query variable on Case table
  src/dispatch/static/dispatch/src/case/Table.vue
Labels: bug

#4203 Fix default project filter on case table
  src/dispatch/static/dispatch/src/case/Table.vue
Labels: bug

#4212 Updated find_schedule_and_send to check for Null current on call
  src/dispatch/feedback/service/scheduled.py
Labels: bug

#4216 Fix bug where you can't go to the next page on Case table
  src/dispatch/static/dispatch/src/case/Table.vue
Labels: bug

#4217 Update slack plugin.py to check if user exists before send direct
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#4218 Check for case assignee before trying to send reminder
  src/dispatch/case/messaging.py
Labels: bug

#4229 Add doc page for forms
  docs/docs/user-guide/incidents/forms.mdx
Labels: documentation

#4240 Fixed sorting during timeline export
  src/dispatch/event/service.py
Labels: bug

#4205 Logs exception when trying to add non-existing user to a case
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4242 Ensure that next oncall observer is added to all workflows
  src/dispatch/incident/flows.py
Labels: bug

#4243 New tag selector component
  src/dispatch/database/revisions/tenant/versions/2023-12-18_6c1a250b1e4b.py
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/static/dispatch/src/assets/icons/index.js
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/case/TableExportDialog.vue
  src/dispatch/static/dispatch/src/case/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/components/ColorPickerInput.vue
  src/dispatch/static/dispatch/src/components/IconPickerInput.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentDialogFilter.vue
  src/dispatch/static/dispatch/src/data/query/EditBasicInfoTab.vue
  src/dispatch/static/dispatch/src/data/query/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/data/source/EditBasicInfoTab.vue
  src/dispatch/static/dispatch/src/data/source/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionForm.vue
  src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident_role/PolicyRoleBuilder.vue
  src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
  src/dispatch/static/dispatch/src/styles/tagpicker.scss
  src/dispatch/static/dispatch/src/tag/TagPicker.vue
  src/dispatch/static/dispatch/src/tag_type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/tag_type/Table.vue
  src/dispatch/static/dispatch/src/tag_type/store.js
  src/dispatch/tag_type/models.py
  tests/static/e2e/pages/report-incident-page.ts
Labels: enhancement

#4255 Perform None check for group in update_group
  src/dispatch/group/flows.py
Labels: bug

#4158 Moves deleted documents to trash instead of immediately deleting them
  src/dispatch/plugins/dispatch_google/drive/drive.py
Labels: enhancement

#4258 Fixing next oncall type
  src/dispatch/incident/flows.py
Labels: bug

#4259 Moving next oncall block and preventing exception
  src/dispatch/incident/flows.py
  src/dispatch/participant/service.py
Labels: bug

#4260 Enhancement/activity based cost model
  docs/docs/administration/settings/cost_model.mdx
  src/dispatch/static/dispatch/src/cost_model/CostModelCombobox.vue
  src/dispatch/static/dispatch/src/cost_model/Table.vue
  src/dispatch/static/dispatch/src/cost_model/api.js
Labels: documentation

#4275 No need to add commander as observer for next oncall feature
  src/dispatch/incident/service.py
Labels: bug

#4264 Send email to oncall when form is completed
  src/dispatch/database/revisions/tenant/versions/2023-11-29a_bdaeabba3e53.py
  src/dispatch/database/revisions/tenant/versions/2023-11-29b_580a18ec4c39.py
  src/dispatch/database/revisions/tenant/versions/2024-01-17_d4bbb234d0bc.py
  src/dispatch/forms/type/models.py
  src/dispatch/forms/type/service.py
  src/dispatch/forms/views.py
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/email/utils.py
  src/dispatch/messaging/strings.py
  src/dispatch/static/dispatch/src/forms/api.js
  src/dispatch/static/dispatch/src/forms/store.js
  src/dispatch/static/dispatch/src/forms/table/AttorneyEditForm.vue
  src/dispatch/static/dispatch/src/forms/table/Table.vue
  src/dispatch/static/dispatch/src/forms/types/NewEditSheet.vue
  src/dispatch/static/dispatch/src/forms/types/Table.vue
  src/dispatch/static/dispatch/src/forms/types/store.js
  src/dispatch/static/dispatch/src/router/config.js
Labels: enhancement

#4288 Fixes slack cost model select.
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#4287 Ensuring that the tag picker reloads on project selection
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/TableExportDialog.vue
  src/dispatch/static/dispatch/src/case/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentDialogFilter.vue
  src/dispatch/static/dispatch/src/data/query/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/data/source/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
  src/dispatch/static/dispatch/src/tag/TagPicker.vue
Labels: bug

#4299 Add reporter to individual_participants list
  src/dispatch/case/flows.py
Labels: bug

#4301 Bugfix/do not overwrite stable at
  src/dispatch/incident_cost/service.py
Labels: bug

#4304 Bugfix/do not overwrite stable at
  src/dispatch/incident_cost/service.py
Labels: bug

#4305 Reduce logging noise for incident cost calculation.
  src/dispatch/incident_cost/service.py
Labels: enhancement, improvement

#4314 Adding missing enum
  src/dispatch/plugins/dispatch_slack/enums.py
Labels: bug

#4324 Only populate the tacticall report actions field if there are current actions.
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug
