Repository Netflix/dispatch, pull requests merged in 2024-09, with the labels that each got.

#5156 Case cost model is an experimental feature.
  src/dispatch/static/dispatch/src/case/EditSheet.vue
  src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
Labels: bug

#5157 Fixing participant role type in mapping function
  src/dispatch/case/flows.py
Labels: bug

#5158 Hide cost column from Case table if experimental features are disabled.
  src/dispatch/static/dispatch/src/case/Table.vue
Labels: bug

#5159 Fixing role formatting for timeline event
  src/dispatch/participant/flows.py
Labels: bug

#5166 Fixes selection ordering and includes project when filtering
  src/dispatch/static/dispatch/src/case/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/case/priority/CasePriorityCombobox.vue
  src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue
  src/dispatch/static/dispatch/src/case/severity/CaseSeverityCombobox.vue
  src/dispatch/static/dispatch/src/case/severity/CaseSeveritySelect.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeCombobox.vue
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPriorityCombobox.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue
  src/dispatch/static/dispatch/src/incident/severity/IncidentSeverityCombobox.vue
  src/dispatch/static/dispatch/src/incident/severity/IncidentSeveritySelect.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeCombobox.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeMultiSelect.vue
  src/dispatch/static/dispatch/src/search/utils.js
  src/dispatch/static/dispatch/src/service/NewEditSheet.vue
  src/dispatch/static/dispatch/src/workflow/WorkflowSelect.vue
Labels: bug

#5174 feat(plugins/aws): check for dupe instance id
  src/dispatch/plugins/dispatch_aws/plugin.py
Labels: enhancement

#5175 feat(mfa/plugin): add dispatch mfa plugin
  setup.py
  src/dispatch/auth/models.py
  src/dispatch/auth/views.py
  src/dispatch/database/revisions/tenant/versions/2024-09-06_51eacaf1f62c.py
  src/dispatch/plugins/bases/auth_mfa.py
  src/dispatch/plugins/dispatch_core/exceptions.py
  src/dispatch/plugins/dispatch_core/plugin.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/static/dispatch/src/auth/Mfa.vue
  src/dispatch/static/dispatch/src/auth/api.js
  src/dispatch/static/dispatch/src/router/config.js
Labels: enhancement

#5179 Run the incident cost calculation every hour to reduce rounding error.
  src/dispatch/incident_cost/scheduled.py
Labels: bug

#5169 Sort priorities and severities by view_order
  src/dispatch/static/dispatch/src/case/priority/CasePriorityCombobox.vue
  src/dispatch/static/dispatch/src/case/severity/CaseSeverityCombobox.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPriorityCombobox.vue
  src/dispatch/static/dispatch/src/incident/severity/IncidentSeverityCombobox.vue
Labels: bug

#5183 Adds project to comboboxes in dashboard filters
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentDialogFilter.vue
Labels: enhancement

#5185 Restrict select incident severities to active incidents only
  src/dispatch/database/revisions/tenant/versions/2024-09-10_0a6702319f6a.py
  src/dispatch/incident/severity/models.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/static/dispatch/src/case/priority/NewEditSheet.vue
  src/dispatch/static/dispatch/src/case/severity/NewEditSheet.vue
  src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/priority/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident/severity/IncidentSeveritySelect.vue
  src/dispatch/static/dispatch/src/incident/severity/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident/severity/Table.vue
  src/dispatch/static/dispatch/src/incident/type/NewEditSheet.vue
Labels: enhancement

#5186 fix(case): link case to incident immediately in common_escalate_flow
  src/dispatch/case/flows.py
Labels: bug

#5160 Add new joiners as observers and promote to participant on activity in channel
  src/dispatch/case/flows.py
  src/dispatch/incident/flows.py
  src/dispatch/participant/flows.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: enhancement

#5074 Create AI-generated weekly summary
  src/dispatch/database/revisions/tenant/versions/2024-09-14_f729d61738b0.py
  src/dispatch/incident/scheduled.py
  src/dispatch/messaging/strings.py
  src/dispatch/project/models.py
  src/dispatch/static/dispatch/src/notification/Table.vue
  src/dispatch/static/dispatch/src/notification/store.js
Labels: enhancement

#5197 ux(slack): improve case report modal type to assignee and oncall resolution
  src/dispatch/plugins/dispatch_pagerduty/plugin.py
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: enhancement

#5211 Correcting import for Session
  src/dispatch/incident/scheduled.py
Labels: bug

#5204 Adding additional oncall metrics
  src/dispatch/case/service.py
  src/dispatch/database/revisions/tenant/versions/2024-09-16_47d616802f56.py
  src/dispatch/feedback/service/messaging.py
  src/dispatch/feedback/service/models.py
  src/dispatch/feedback/service/reminder/models.py
  src/dispatch/feedback/service/scheduled.py
  src/dispatch/incident/service.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_pagerduty/service.py
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
  src/dispatch/static/dispatch/src/feedback/service/Table.vue
Labels: enhancement

#5219 Do not overwrite the title, incident priority, and incident type fields during case escalation.
  src/dispatch/case/flows.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#5220 Fixes calls to get incident participants.
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#5227 Updates AI plugin
  src/dispatch/plugins/bases/artificial_intelligence.py
  src/dispatch/plugins/dispatch_openai/config.py
  src/dispatch/plugins/dispatch_openai/plugin.py
Labels: enhancement

#5229 Adds genai fields to signal definition model
  src/dispatch/database/revisions/tenant/versions/2024-09-19_19c10c121a22.py
  src/dispatch/signal/models.py
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
  src/dispatch/static/dispatch/src/signal/store.js
Labels: enhancement

#5207 Enable users to migrate a Case thread to a Case dedicated channel.
  src/dispatch/case/flows.py
  src/dispatch/case/models.py
  src/dispatch/case/views.py
  src/dispatch/conversation/flows.py
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/static/dispatch/src/case/ResourcesTab.vue
  src/dispatch/static/dispatch/src/case/api.js
  src/dispatch/static/dispatch/src/case/store.js
Labels: enhancement

#5232 Adds a new genai field to signal definition model to store the prompt
  src/dispatch/database/revisions/tenant/versions/2024-09-20_1f4dc687945d.py
  src/dispatch/signal/models.py
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
  src/dispatch/static/dispatch/src/signal/store.js
Labels: enhancement

#5238 fix(scheduler): corrects endpoint for weekly summary
  src/dispatch/incident/scheduled.py
Labels: bug

#5239 enhancement(slack): update assignee if case type changes
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: enhancement

#5194 Fix a condition where default was execting when it shouldn't
  src/dispatch/signal/service.py
Labels: bug

#5237 feat(genai): add llm case summary and historical summary to slack plugin
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/signal/service.py
Labels: enhancement

#5242 ux/fix(slack): move snooze mfa to new mfa, add emoji to case message,…
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
Labels: bug, enhancement

#5244 Fixes access to local variable 'thread_conversation_weblink'
  src/dispatch/conversation/flows.py
Labels: bug

#5245 fix(scheduler): use correct metadata indexing
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
Labels: bug

#5246 fix(ui): ensure empty details doesn't throw error
  src/dispatch/static/dispatch/src/feedback/service/Table.vue
Labels: bug

#5261 fix(scheduler): correcting import for datetime
  src/dispatch/feedback/service/scheduled.py
Labels: bug

#5266 update(ci): version bumps
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-docs-test.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/javascript.yml
  .github/workflows/playwright.yml
  .github/workflows/publish-image.yml
  .github/workflows/python.yml
  .github/workflows/stale.yml
Labels: enhancement

#5268 fix(scheduler): adapting weekly summary to new ai parameters
  src/dispatch/incident/scheduled.py
Labels: bug
