Repository Netflix/dispatch, pull requests merged in 2024-03, with the labels that each got.

#4474 Add alert data to JSON file in Case thread, remove Raw Data button
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/enums.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: enhancement

#4469 Ensuring filter counter includes tag-all
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
Labels: bug

#4475 Do not process handle_case_after_hours_message outside of a thread context
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4482 Moving incident combobox to fixed incident filter combobox
  src/dispatch/static/dispatch/src/feedback/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/IncidentCombobox.vue
  src/dispatch/static/dispatch/src/task/TableExportDialog.vue
  src/dispatch/static/dispatch/src/task/TableFilterDialog.vue
Labels: bug

#4484 Log a warning if the exception in case add thread flow is users not found
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
Labels: bug

#4489 Adds code coverage recommendations in GitHub workflow.
  .coveragerc
  .github/workflows/python.yml
Labels: enhancement

#4500 [Bugfix] - Timezone and expression construction for snooze created via Slack
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4483 Adding incident resources to export
  src/dispatch/incident/models.py
  src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
  src/dispatch/static/dispatch/src/util/index.js
Labels: bug

#4503 Python packages update
  requirements-base.txt
  requirements-dev.txt
Labels: dependencies

#4498 Allows for custom email templates
  src/dispatch/__init__.py
  src/dispatch/api.py
  src/dispatch/database/revisions/tenant/versions/2024-03-11_91bd05855ad1.py
  src/dispatch/email_templates/enums.py
  src/dispatch/email_templates/models.py
  src/dispatch/email_templates/service.py
  src/dispatch/email_templates/views.py
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/strings.py
  src/dispatch/static/dispatch/src/email_templates/DeleteDialog.vue
  src/dispatch/static/dispatch/src/email_templates/NewEditSheet.vue
  src/dispatch/static/dispatch/src/email_templates/Table.vue
  src/dispatch/static/dispatch/src/email_templates/api.js
  src/dispatch/static/dispatch/src/email_templates/store.js
  src/dispatch/static/dispatch/src/router/config.js
  src/dispatch/static/dispatch/src/store.js
Labels: enhancement

#4542 Run transition flow to move to triage state
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4540 Adding new form type that allows new values
  src/dispatch/static/dispatch/src/forms/store.js
Labels: enhancement

#4543 Do not extract new entities from updated instances
  src/dispatch/signal/flows.py
  src/dispatch/signal/views.py
Labels: bug

#4550 [Bugfix] - Call commit after we associate an incident to a case
  src/dispatch/case/flows.py
Labels: bug

#4559 Adding back case transition when participant is added
  src/dispatch/participant/flows.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4560 Enforces minimum code coverage.
  .github/workflows/python.yml
Labels: enhancement, improvement
