Repository Netflix/dispatch, pull requests merged in 2024-02, with the labels that each got.

#4326 Adding copy button to tag picker
  src/dispatch/static/dispatch/src/styles/tagpicker.scss
  src/dispatch/static/dispatch/src/tag/TagPicker.vue
Labels: enhancement

#4341 Fixes participant role time calculation by defaulting the participant role end time to now.
  src/dispatch/incident_cost/service.py
Labels: bug

#4340 Adds http url validation to all weblinks
  data/dispatch-sample-data.dump
  src/dispatch/case/type/models.py
  src/dispatch/data/source/models.py
  src/dispatch/incident/models.py
  src/dispatch/incident/type/models.py
  src/dispatch/individual/models.py
  src/dispatch/models.py
  src/dispatch/plugins/dispatch_slack/models.py
Labels: bug

#4346 Do not allow user password changes via API
  src/dispatch/auth/views.py
Labels: bug

#4290 Fixing one_or_none error when conversation has multiple rows
  src/dispatch/conversation/service.py
Labels: bug

#4347 Revert linter changes
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#4358 Only show copy button in tag picker if prop is set
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
  src/dispatch/static/dispatch/src/tag/TagPicker.vue
Labels: enhancement

#4360 Changing HttpUrl to AnyHttpUrl
  src/dispatch/case/type/models.py
  src/dispatch/data/source/models.py
  src/dispatch/incident/models.py
  src/dispatch/incident/type/models.py
  src/dispatch/individual/models.py
  src/dispatch/models.py
  src/dispatch/plugins/dispatch_atlassian_confluence/config.py
  src/dispatch/plugins/dispatch_jira/plugin.py
  src/dispatch/plugins/dispatch_slack/models.py
  src/dispatch/plugins/generic_workflow/plugin.py
Labels: enhancement

#4370 Fixes case escalate button/modal generation
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#4374 Change new button on incident and case pages to point to report form
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
Labels: enhancement

#4336 Validate project-specific fields in UI
  src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue
  src/dispatch/static/dispatch/src/case/severity/CaseSeveritySelect.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue
  src/dispatch/static/dispatch/src/incident/severity/IncidentSeveritySelect.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
  src/dispatch/static/dispatch/src/tag/TagPicker.vue
Labels: enhancement

#4371 Fixes case escalate modal submission
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4359 Adds the Slack API endpoint for conversation replies.
  src/dispatch/plugins/dispatch_slack/enums.py
Labels: bug

#4386 Fixes error from accessing a None type object.
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#4387 Updates the resource deletion call.
  src/dispatch/plugins/dispatch_google/drive/drive.py
Labels: bug

#4388 updated delete to trashed
  src/dispatch/plugins/dispatch_google/drive/drive.py
Labels: bug

#4376 Adds routing to an incident's forms tab.
  src/dispatch/static/dispatch/src/incident/EditSheet.vue
  src/dispatch/static/dispatch/src/incident/FormsTab.vue
  src/dispatch/static/dispatch/src/router/config.js
Labels: enhancement

#4385 Typo fix
  docs/src/components/HomepageFeatures/index.js
Labels: documentation

#4375 Replaces hyperlinks in a specified Google Doc.
  src/dispatch/plugins/dispatch_google/common.py
  src/dispatch/plugins/dispatch_google/docs/plugin.py
  src/dispatch/plugins/dispatch_test/document.py
  tests/dispatch_google_docs/test_dispatch_google_docs.py
Labels: enhancement

#4392 Checks for incident before attempting to remove participant from it
  src/dispatch/incident/flows.py
Labels: bug

#4395 Fix source link modeling
  src/dispatch/data/source/models.py
Labels: bug

#4400 Removes redundant report incident button
  src/dispatch/static/dispatch/src/components/AppDrawer.vue
Labels: bug

#4396 Changes signals ingestion from opt in to opt out approach
  src/dispatch/database/revisions/tenant/versions/2024-02-13_0283f2bbe9dd.py
  src/dispatch/signal/models.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
  src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
  src/dispatch/static/dispatch/src/signal/NewEditDialog.vue
Labels: enhancement

#4399 Force cases resolved via user enagement to follow case flows
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4428 handle network timeouts in slack make_call
  src/dispatch/plugins/dispatch_slack/service.py
Labels: enhancement

#4432 Fixing triage button transition
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#4429 Adding back new button for Admin and above and sets default project on report forms
  src/dispatch/auth/views.py
  src/dispatch/static/dispatch/src/auth/api.js
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/store.js
  tests/static/e2e/pages/report-incident-page.ts
Labels: enhancement

#4448 Add a Required column to the TagType table
  src/dispatch/static/dispatch/src/tag_type/Table.vue
Labels: enhancement, UI/UX

#4457 Only run member join or remove for incident channels
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/middleware.py
  src/dispatch/plugins/dispatch_slack/models.py
Labels: bug

#4462 Allow filtering of incidents that have all of a selected set of tags
  src/dispatch/database/service.py
  src/dispatch/static/dispatch/src/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/incident/store.js
Labels: enhancement
