Repository Netflix/dispatch, pull requests merged in 2024-10, with the labels that each got.

#5240 Enable users to create tasks from Slack
  docs/docs/administration/settings/plugins/configuring-slack.mdx
  docs/docs/user-guide/incidents/commander.mdx
  docs/static/img/slack-conversation-create-task.png
  src/dispatch/database/revisions/tenant/versions/2024-09-23_32652e0360dd.py
  src/dispatch/plugins/dispatch_slack/config.py
  src/dispatch/plugins/dispatch_slack/incident/enums.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/models.py
Labels: enhancement

#5275 fix(scheduler): use ast instead of json library to load string data
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
Labels: bug

#5276 Creates the modal immediately after invocation. Update the modal with the task fields after.
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#5267 Enhances Slack Case Handling and Messaging for Improved Clarity and User Interaction
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: enhancement

#5278 Adds pyrightconfig.json to gitignore
  .gitignore
Labels: enhancement

#5279 Undoes changes made by typos pre-commit hook
  src/dispatch/incident/metrics.py
  src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js
Labels: bug

#5282 Improves the messaging and error handling in the Dispatch Slack plugin
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: enhancement

#5283 Uses a representative sample of related cases for the GenAI analysis
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/signal/service.py
Labels: enhancement

#5284 Improves messaging in case threaded alert message
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#5285 Adds a command to perform signals testing to the CLI
  src/dispatch/cli.py
Labels: enhancement

#5287 Show GenAI signal analysis errors in Slack message.
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#5288 Improves error handling, logging, and messaging in Slack plugin
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: enhancement

#5290 Updates case.signal_thread_ts after creating the alerts section
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#5291 fix(slack): don't use snooze ack, refactor engagement ack to generalized mfa ack
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#5292 Fixes get_signal_engagement_by_name call in signals create module and several type annotations
  src/dispatch/data/alert/service.py
  src/dispatch/organization/service.py
  src/dispatch/project/service.py
  src/dispatch/service/service.py
  src/dispatch/signal/service.py
  src/dispatch/tag/service.py
  src/dispatch/tag_type/service.py
  src/dispatch/workflow/service.py
Labels: bug

#5293 Allows to update a signal engagement
  src/dispatch/signal/models.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
Labels: enhancement

#5296 feat(GenAI): only include Slack user messages in historical context
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/dispatch_slack/service.py
  src/dispatch/signal/flows.py
Labels: enhancement

#5299 Does not execute jpath if it is not sanitized.
  src/dispatch/entity_type/service.py
  src/dispatch/static/dispatch/src/entity_type/utils.js
  tests/entity_type/test_entity_type_service.py
Labels: bug

#5302 Use the incident priority colors.
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPriority.vue
Labels: bug

#5314 Improves warning text when there are no users to engage
  .pre-commit-config.yaml
  src/dispatch/signal/flows.py
Labels: enhancement

#5301 Display GenAI analysis in the case page in the Web UI
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/static/dispatch/package-lock.json
  src/dispatch/static/dispatch/package.json
  src/dispatch/static/dispatch/src/case/Page.vue
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/components/GenaiAnalysisDisplay.vue
Labels: enhancement

#5303 fix(ui/ux): use the custom incident severity color and the custom priority and severity colors for cases
  src/dispatch/static/dispatch/src/case/CaseSummaryTable.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/TableExportDialog.vue
  src/dispatch/static/dispatch/src/case/priority/CasePriority.vue
  src/dispatch/static/dispatch/src/case/severity/CaseSeverity.vue
  src/dispatch/static/dispatch/src/incident/IncidentSummaryTable.vue
  src/dispatch/static/dispatch/src/incident/ReportReceiptResources.vue
  src/dispatch/static/dispatch/src/incident/Table.vue
  src/dispatch/static/dispatch/src/incident/TableExportDialog.vue
  src/dispatch/static/dispatch/src/incident/severity/IncidentSeverity.vue
  src/dispatch/static/dispatch/src/search/SearchFilterCreateDialog.vue
  src/dispatch/static/dispatch/src/task/TableExportDialog.vue
  src/dispatch/static/dispatch/src/task/TaskSummaryTable.vue
Labels: bug

#5317 fix(scheduler): weekly reports should run weekly
  src/dispatch/incident/scheduled.py
  src/dispatch/messaging/strings.py
Labels: bug

#5295 feat(slack): Expose create case slash command
  docs/docs/administration/settings/plugins/configuring-slack.mdx
  docs/docs/user-guide/incidents/commander.mdx
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/config.py
  src/dispatch/plugins/dispatch_slack/messaging.py
Labels: enhancement

#5324 Adds comments to docker-compose.yml file to change default passwords
  docker/docker-compose.yml
Labels: documentation, docker

#5323 Fixing case and incident form fill from url
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Labels: bug

#5330 Update support.mdx
  docs/docs/support.mdx
Labels: documentation

#5332 Fixing case/incident report selects.
  src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Labels: bug

#5338 Fixes warning
  src/dispatch/static/dispatch/src/tag/TagPicker.vue
Labels: bug

#5260 feat(ui/ux): adds a task edit dialog with create ticket action
  src/dispatch/database/revisions/tenant/versions/2024-10-09_b8c1a8a4d957.py
  src/dispatch/incident/models.py
  src/dispatch/incident/type/models.py
  src/dispatch/plugins/dispatch_core/plugin.py
  src/dispatch/plugins/dispatch_jira/plugin.py
  src/dispatch/static/dispatch/src/incident/TaskEditDialog.vue
  src/dispatch/static/dispatch/src/incident/TasksTab.vue
  src/dispatch/static/dispatch/src/incident/store.js
  src/dispatch/static/dispatch/src/incident/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/plugin/PluginInstanceCombobox.vue
  src/dispatch/static/dispatch/src/task/NewEditSheet.vue
  src/dispatch/static/dispatch/src/task/Table.vue
  src/dispatch/static/dispatch/src/task/api.js
  src/dispatch/task/models.py
  src/dispatch/task/service.py
  src/dispatch/task/views.py
  src/dispatch/ticket/flows.py
  src/dispatch/ticket/models.py
Labels: enhancement

#5180 Do not round up incident cost
  src/dispatch/incident_cost/service.py
  tests/incident_cost/test_incident_cost_service.py
Labels: bug

#5348 fix(utils): adding docker type to github utils
  utils/github_utils.py
Labels: bug

#5350 fix(plugin): allow list of strings in plugin metadata
  src/dispatch/plugin/models.py
Labels: bug

#5351 fix(search): only collect participant emails if individual exists
  src/dispatch/search/views.py
Labels: bug

#5352 feat(jira): add Dispatch link in Jira ticket
  src/dispatch/plugins/dispatch_core/plugin.py
  src/dispatch/plugins/dispatch_jira/plugin.py
  src/dispatch/plugins/dispatch_jira/templates.py
  src/dispatch/ticket/flows.py
Labels: enhancement

#5357 Checks if the message is a dict before saving it to the genai analysis field in the case model
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#5359 Handles JSONDecodeError exception when parsing GenAI JSON string
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: enhancement

#5360 fix(ui): fixing linting errors
  src/dispatch/static/dispatch/src/components/GenaiAnalysisDisplay.vue
Labels: bug

#5356 feat(case): adding case feedback
  src/dispatch/case/flows.py
  src/dispatch/case/messaging.py
  src/dispatch/case/models.py
  src/dispatch/conversation/enums.py
  src/dispatch/database/revisions/tenant/versions/2024-10-16_3c49f62d7914.py
  src/dispatch/database/service.py
  src/dispatch/feedback/incident/models.py
  src/dispatch/feedback/incident/service.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/feedback/enums.py
  src/dispatch/plugins/dispatch_slack/feedback/interactive.py
  src/dispatch/static/dispatch/src/feedback/incident/Table.vue
  src/dispatch/static/dispatch/src/feedback/incident/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/feedback/incident/store.js
  src/dispatch/static/dispatch/src/router/config.js
Labels: enhancement

#5366 fix(plugin): allow dictionary in plugin metadata
  src/dispatch/plugin/models.py
Labels: bug

#5368 fix(test): adding rounding method to quantize
  tests/incident_cost/test_incident_cost_service.py
Labels: bug

#5373 fix(test): use correct rounding strategy
  tests/incident_cost/test_incident_cost_service.py
Labels: bug, tests

#5377 bug(core-ticket): Add dispatch_weblink field to core ticket plugin
  src/dispatch/plugins/dispatch_core/plugin.py
Labels: bug

#5379 bug(docker): Revert python version bump
  docker/Dockerfile
Labels: bug

#5376 (fix) get_signal_filter arg name is signal_filter_id
  src/dispatch/signal/views.py
Labels: bug

#5375 bug(slack/api): Make slack /event respond to challenge
  src/dispatch/plugins/dispatch_slack/endpoints.py
Labels: bug

#5372 fix(groups): propagate errors back to remove_member
  src/dispatch/plugins/dispatch_google/groups/plugin.py
Labels: bug, techdebt

#5380 Fixing selects when not yet loaded
  src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Labels: bug

#5384 Speeds up case resolution
  .pre-commit-config.yaml
  src/dispatch/case/flows.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: enhancement

#5385 fix(ui): fixes details tab selects
  .github/workflows/python.yml
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/priority/CasePrioritySelect.vue
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/priority/IncidentPrioritySelect.vue
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
Labels: bug

#5389 fix(ui): increasing type selector length
  src/dispatch/static/dispatch/src/incident/type/IncidentTypeSelect.vue
  tests/static/e2e/report-submission.spec.ts
Labels: bug

#5396 fix(case): ensure participant read through individual
  src/dispatch/case/flows.py
Labels: bug

#5386 test(service_feedback): adding tests for oncall service feedback
  tests/conftest.py
  tests/factories.py
  tests/feedback/test_feedback_cases.py
  tests/feedback/test_feedback_oncall.py
Labels: tests

#5395 feat(case): add case feedback daily email
  src/dispatch/feedback/incident/messaging.py
  src/dispatch/feedback/incident/scheduled.py
  src/dispatch/feedback/incident/service.py
  src/dispatch/messaging/email/utils.py
  src/dispatch/messaging/strings.py
Labels: enhancement

#5367 fix(case): ensure case tickets are updated
  src/dispatch/case/flows.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug, techdebt

#5397 feat(ticket): allows incident title in ticket name
  src/dispatch/database/revisions/tenant/versions/2024-10-25_24322617ce9a.py
  src/dispatch/plugins/dispatch_core/config.py
  src/dispatch/plugins/dispatch_core/plugin.py
  src/dispatch/plugins/dispatch_core/service.py
Labels: enhancement

#5407 fix(case): case reporter can be null
  src/dispatch/case/flows.py
Labels: bug

#5374 fix(feedback): store service id rather than schedule id
  src/dispatch/feedback/service/messaging.py
  src/dispatch/feedback/service/scheduled.py
  src/dispatch/static/dispatch/src/feedback/service/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/service/ServiceSelect.vue
Labels: bug

#5409 feat(case type): adds support for auto closing cases
  src/dispatch/case/flows.py
  src/dispatch/case/type/models.py
  src/dispatch/database/revisions/tenant/versions/2024-10-29_3edb0476365a.py
  src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/case/type/Table.vue
  src/dispatch/static/dispatch/src/case/type/store.js
  src/dispatch/static/dispatch/src/service/ServiceSelect.vue
Labels: enhancement

#5410 fix(ui): only disable project if editing existing case or incident
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/incident/DetailsTab.vue
Labels: bug

#5412 feat(case): update conversation on case auto close
  src/dispatch/case/flows.py
Labels: enhancement

#5394 chore(node): Upgrade to node lts
  .nvmrc
  docker/Dockerfile
Labels: enhancement, docker
