Repository Netflix/dispatch, pull requests merged in 2025-04, with the labels that each got.

#5867 fix(signal): fixing nonetype object reference
  src/dispatch/signal/service.py
Labels: bug

#5881 fix(case): report case types not loading more
  src/dispatch/static/dispatch/src/case/type/CaseTypeSelect.vue
Labels: bug

#5882 feat(feedback): allow selectable feedback shift types
  src/dispatch/database/revisions/tenant/versions/2025-04-09_4aa819afb065.py
  src/dispatch/feedback/service/scheduled.py
  src/dispatch/service/models.py
  src/dispatch/static/dispatch/src/service/NewEditSheet.vue
Labels: enhancement

#5883 fix(case): don't put resolution in restricted case ticket
  src/dispatch/ticket/flows.py
Labels: bug

#5892 fix(jira): fallback to case ticket resource name
  src/dispatch/plugins/dispatch_jira/plugin.py
Labels: bug

#5898 feat(int): adding internal scheduler placeholder
  .github/workflows/playwright.yml
  src/dispatch/case/scheduled_internal.py
  src/dispatch/cli.py
Labels: enhancement

#5873 bug(signal filter): handles when filter fields are none more gracefully
  src/dispatch/signal/service.py
Labels: bug

#5904 feat(security events): Add event reporting form
  src/dispatch/case/flows.py
  src/dispatch/case/messaging.py
  src/dispatch/case/models.py
  src/dispatch/case/service.py
  src/dispatch/database/revisions/tenant/versions/2025-04-17_8f324b0f365a.py
  src/dispatch/static/dispatch/src/case/store.js
  src/dispatch/static/dispatch/src/events/ReportForm.vue
  src/dispatch/static/dispatch/src/events/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/router/config.js
Labels: enhancement

#5906 Add oncall display name when sending option to page the oncall
  src/dispatch/case/flows.py
  src/dispatch/case/messaging.py
Labels: enhancement

#5907 fix(cases): Report Another Issue functionality
  src/dispatch/static/dispatch/src/case/store.js
Labels: bug

#5909 fix(slack): Case engage oncall language
  src/dispatch/case/messaging.py
Labels: enhancement

#5911 ui/ux(case): fix hotkey layout, add tag selector, disable graph tab
  src/dispatch/static/dispatch/src/case/CaseAttributesDrawer.vue
  src/dispatch/static/dispatch/src/case/CaseTabs.vue
  src/dispatch/static/dispatch/src/components/DTooltip.vue
  src/dispatch/static/dispatch/src/tag/TagSearchPopover.vue
Labels: enhancement, javascript

#5915 enhancement(case): improve minimal model for faster table loads
  src/dispatch/case/models.py
  src/dispatch/case_cost/models.py
Labels: enhancement

#5913 enhancement(ux): implement partial pre-fetch on case row hover
  src/dispatch/static/dispatch/src/case/Page.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/api.js
  src/dispatch/static/dispatch/src/main.js
  src/dispatch/static/dispatch/src/query.js
Labels: enhancement, javascript

#5914 meta: update vscode settings & rec extensions for eslint/prettier
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: enhancement

#5917 Revert "ui/ux(case): fix hotkey layout, add tag selector, disable graph tab"
  src/dispatch/static/dispatch/src/case/CaseAttributesDrawer.vue
  src/dispatch/static/dispatch/src/case/CaseTabs.vue
  src/dispatch/static/dispatch/src/components/DTooltip.vue
  src/dispatch/static/dispatch/src/tag/TagSearchPopover.vue
Labels: bug

#5918 Revert "enhancement(ux): implement partial pre-fetch on case row hover"
  src/dispatch/static/dispatch/src/case/Page.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/api.js
  src/dispatch/static/dispatch/src/main.js
  src/dispatch/static/dispatch/src/query.js
Labels: bug

#5921 Nit: equal spacing on both button sides.
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/events/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
Labels: bug, javascript

#5920 feat(user engagement): only add participants to case threads that originate from signals in production
  src/dispatch/conversation/flows.py
Labels: enhancement

#5927 Resolves Python Package Version Conflicts
  requirements-base.in
  requirements-base.txt
  requirements-dev.in
  requirements-dev.txt
Labels: enhancement, chore

#5901 feat(snooze): limit entities in snooze to only those in case
  src/dispatch/entity/service.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/fields.py
  tests/entity/test_entity_service.py
Labels: enhancement

#5908 feat(entity): when a new entity_type is created, find new entities
  src/dispatch/entity_type/service.py
  src/dispatch/entity_type/views.py
  src/dispatch/static/dispatch/src/entity_type/EntityTypeCreateDialogV2.vue
  src/dispatch/static/dispatch/src/entity_type/api.js
  src/dispatch/static/dispatch/src/signal/NewRawSignalViewer.vue
  src/dispatch/static/dispatch/src/util/jpath.ts
Labels: enhancement

#5925 enhancement(case): improve minimal model for faster table loads
  src/dispatch/case/models.py
  src/dispatch/case_cost/models.py
Labels: enhancement

#5912 feat(entity): send notification to channel thread when entities are recalculated
  src/dispatch/case/messaging.py
  src/dispatch/entity_type/flows.py
  src/dispatch/messaging/strings.py
Labels: enhancement

#5930 fix(conference): only tactical participants are included in conferenc…
  src/dispatch/incident/flows.py
Labels: bug

#5926 ui/ux(case): fix hotkey layout, add tag selector, disable graph tab
  src/dispatch/static/dispatch/src/case/CaseAttributesDrawer.vue
  src/dispatch/static/dispatch/src/case/CaseTabs.vue
  src/dispatch/static/dispatch/src/components/DTooltip.vue
  src/dispatch/static/dispatch/src/tag/TagSearchPopover.vue
Labels: enhancement, javascript

#5931 feat(slack): adds add entity button in snooze modal
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: enhancement

#5933 bugfix(tags): tag exclusivity validator drops non-exclusive tags
  src/dispatch/case/models.py
Labels: bug

#5934 bugfix(ui/tags): remove tags on chip delete for tag search popover
  src/dispatch/static/dispatch/src/tag/TagSearchPopover.vue
Labels: bug

#5935 fix: allow GET on incidents/cases to include participants & other fields
  src/dispatch/case/views.py
  src/dispatch/incident/views.py
Labels: bug

#5939 feat(ui): adds ability to filter out selected case types
  src/dispatch/database/service.py
  src/dispatch/static/dispatch/src/case/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/case_cost/CaseCostCard.vue
Labels: enhancement
