Repository Netflix/dispatch, pull requests merged in 2025-08, with the labels that each got.

#6167 Revert "Migrates from pip to uv and adds dynamic versioning"
  .devcontainer/postCreateCommand.sh
  .github/CODEOWNERS
  .github/workflows/playwright.yml
  .github/workflows/publish-image-test.yml
  .github/workflows/publish-image.yml
  .github/workflows/python.yml
  .gitignore
  .pre-commit-config.yaml
  docker/Dockerfile
  docs/docs/administration/contributing/environment.mdx
  docs/docs/administration/contributing/plugins/index.mdx
  docs/docs/administration/upgrading.mdx
  package-lock.json
  package.json
  playwright.config.ts
  pyproject.toml
  requirements-base.in
  requirements-base.txt
  requirements-dev.in
  requirements-dev.txt
  scripts/verify-uv-setup.sh
  setup.cfg
  setup.py
  src/dispatch/__init__.py
Labels: enhancement

#6168 feat: Migrates to uv for python dependency management and adds dynamic versioning
  .devcontainer/postCreateCommand.sh
  .github/CODEOWNERS
  .github/workflows/playwright.yml
  .github/workflows/publish-image-test.yml
  .github/workflows/publish-image.yml
  .github/workflows/python.yml
  .gitignore
  .pre-commit-config.yaml
  docker/Dockerfile
  docs/docs/administration/contributing/environment.mdx
  docs/docs/administration/contributing/plugins/index.mdx
  docs/docs/administration/upgrading.mdx
  package-lock.json
  package.json
  playwright.config.ts
  pyproject.toml
  requirements-base.in
  requirements-base.txt
  requirements-dev.in
  requirements-dev.txt
  scripts/verify-uv-setup.sh
  setup.cfg
  setup.py
  src/dispatch/__init__.py
Labels: enhancement

#6162 Add git commit hash and date to development
  docker/Dockerfile
  src/dispatch/cli.py
  src/dispatch/static/dispatch/src/app/store.js
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
Labels: enhancement

#6173 Emojify and simplify change notifications for incidents and cases
  src/dispatch/case/messaging.py
  src/dispatch/incident/messaging.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/messaging.py
Labels: enhancement

#6169 fix(search_filter): adds refresh to search filter when not showing
  src/dispatch/search_filter/views.py
  src/dispatch/static/dispatch/src/search/EditDialog.vue
  src/dispatch/static/dispatch/src/search/store.js
Labels: bug

#6181 Updates pyproject.toml
  pyproject.toml
Labels: enhancement, chore

#6191 fix(incident): submission form formatting changes
  src/dispatch/database/revisions/tenant/versions/2025-08-06_f2bce475e71b.py
  src/dispatch/static/dispatch/src/incident/ReportSubmissionCard.vue
Labels: enhancement

#6196 fix(remove user): handles user removal failures more gracefully
  src/dispatch/case/flows.py
  src/dispatch/incident/flows.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#6193 Add emojis directly and refactor email and Slack messages
  src/dispatch/conversation/flows.py
  src/dispatch/messaging/strings.py
  src/dispatch/plugins/dispatch_slack/messaging.py
  src/dispatch/plugins/dispatch_slack/service.py
  tests/ai/test_ai_service.py
Labels: bug
