Repository Netflix/dispatch, pull requests merged in 2025-01, with the labels that each got.

#5646 fix(utils): adding new labels
  utils/github_utils.py
Labels: enhancement

#5648 Revert changes made to database service's include logic.
  src/dispatch/case/views.py
  src/dispatch/database/service.py
  tests/database/test_service.py
Labels: bug

#5655 Fix typo in workflow service
  src/dispatch/workflow/service.py
Labels: bug

#5670 feat(signal instance): allow instance to specify oncall service and conversation target
  src/dispatch/database/revisions/tenant/versions/2024-12-17_dfc8e213a2c4.py
  src/dispatch/signal/flows.py
  src/dispatch/signal/models.py
  src/dispatch/signal/service.py
  tests/signal/test_signal_flow.py
Labels: enhancement

#5673 fix(ui): oncall select should default to single select
  src/dispatch/static/dispatch/src/feedback/service/TableFilterDialog.vue
  src/dispatch/static/dispatch/src/service/ServiceSelect.vue
Labels: bug

#5693 fix(org): disallow creation of org with same id
  src/dispatch/organization/views.py
  src/dispatch/project/views.py
Labels: bug

#5694 fix(organization): disallow creation of org with existing slug
  src/dispatch/auth/permissions.py
  src/dispatch/organization/views.py
Labels: bug

#5692 fix(signal): log exception instead of warning for bad signal id
  src/dispatch/signal/service.py
Labels: bug

#5704 feat(ai): tune prompt for incident summary
  src/dispatch/incident/service.py
Labels: enhancement

#5709 Sanitize input to ApexChart in Dashboard Card
  src/dispatch/static/dispatch/src/dashboard/DashboardCard.vue
Labels: bug

#5712 fix: vuln, minimal models allows priv incident read
  src/dispatch/forms/models.py
Labels: bug, security

#5711 fix: vulnerability allows users to reset owner passwords
  src/dispatch/auth/models.py
  src/dispatch/auth/views.py
  src/dispatch/cli.py
Labels: bug, security

#5716 Enable filtering by case assignees/participants on the Dashboard page
  src/dispatch/static/dispatch/src/dashboard/case/CaseDialogFilter.vue
Labels: enhancement

#5717 Fixes rendering of case/incident severity and priority bar charts for entries without an assigned color.
  src/dispatch/static/dispatch/src/dashboard/case/CaseSeverityBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentPriorityBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/incident/IncidentSeverityBarChartCard.vue
Labels: bug

#5718 Add case priority bar chart to Case dashboard.
  src/dispatch/static/dispatch/src/dashboard/case/CaseOverview.vue
  src/dispatch/static/dispatch/src/dashboard/case/CasePriorityBarChartCard.vue
Labels: enhancement

#5719 Removes experimental features flag from Case Cost and adds Case Costs to the Dashboard
  src/dispatch/static/dispatch/src/case/EditSheet.vue
  src/dispatch/static/dispatch/src/case/Table.vue
  src/dispatch/static/dispatch/src/case/type/NewEditSheet.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseCostBarChartCard.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseOverview.vue
Labels: enhancement

#5733 fix: user update from CLI threw AttributeError
  src/dispatch/auth/service.py
Labels: bug

#5732 Adds configurable delayed message notification
  src/dispatch/database/revisions/tenant/versions/2025-01-24_753ea20c2680.py
  src/dispatch/incident/priority/models.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/static/dispatch/src/incident/priority/NewEditSheet.vue
  src/dispatch/static/dispatch/src/incident/priority/store.js
Labels: enhancement

#5740 fix(slack): individual may not be defined
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#5739 feat(forms): adds ability to export forms
  src/dispatch/document/service.py
  src/dispatch/enums.py
  src/dispatch/forms/service.py
  src/dispatch/forms/views.py
  src/dispatch/static/dispatch/src/document/template/TemplateTable.vue
  src/dispatch/static/dispatch/src/document/template/store.js
  src/dispatch/static/dispatch/src/forms/api.js
  src/dispatch/static/dispatch/src/forms/table/BulkEditSheet.vue
  src/dispatch/static/dispatch/src/forms/table/DeleteBulkDialog.vue
  src/dispatch/static/dispatch/src/forms/table/ExportFormsDialog.vue
  src/dispatch/static/dispatch/src/forms/table/Table.vue
  src/dispatch/static/dispatch/src/forms/table/store.js
Labels: enhancement

#5742 fix: case type query params get ignored on Report Case form
  src/dispatch/static/dispatch/src/case/ReportSubmissionCard.vue
Labels: bug

#5752 Adds troubleshooting instructions in invalid user email error message
  src/dispatch/signal/flows.py
Labels: enhancement
