Repository Netflix/dispatch, pull requests merged in 2025-02, with the labels that each got.

#5762 Handles user not in Slack workspace error
  src/dispatch/conversation/flows.py
  src/dispatch/participant/flows.py
  src/dispatch/participant/service.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/case/messages.py
  src/dispatch/plugins/dispatch_slack/enums.py
Labels: bug

#5763 Updates Python dependencies
  requirements-base.in
  requirements-base.txt
  requirements-dev.in
  requirements-dev.txt
Labels: dependencies

#5764 Downgrades and pins pytest version
  requirements-base.in
  requirements-base.txt
  requirements-dev.in
  requirements-dev.txt
Labels: tests, dependencies

#5765 Moves generate_incident_summary() to AI service module and refactors code
  src/dispatch/ai/service.py
  src/dispatch/incident/flows.py
  src/dispatch/incident/scheduled.py
  src/dispatch/incident/service.py
  src/dispatch/incident/views.py
Labels: enhancement

#5766 fix: dashboard cards theme should match the app theme
  src/dispatch/static/dispatch/src/dashboard/DashboardCard.vue
Labels: bug

#5769 Fixes typo in case_type_select enum value
  src/dispatch/plugins/dispatch_slack/case/enums.py
Labels: bug

#5770 feat(slack plugin): hardens creation of static select blocks
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: enhancement

#5774 Truncate GenAI prompt if this exceeds 128k tokens
  requirements-base.in
  requirements-base.txt
  src/dispatch/ai/service.py
Labels: enhancement

#5783 fix(ai): don't create an AI summary for a duplicate incident
  src/dispatch/ai/service.py
  src/dispatch/incident/scheduled.py
Labels: bug

#5780 feat(slack/case): allow page command in dedicated case channels
  src/dispatch/case/flows.py
  src/dispatch/plugins/dispatch_pagerduty/plugin.py
  src/dispatch/plugins/dispatch_pagerduty/service.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: enhancement

#5786 Propose additional security check to auth/views.py
  src/dispatch/auth/views.py
Labels: security

#5791 fix: loud integrity errors instead of update, not supported
  src/dispatch/signal/views.py
Labels: bug

#5790 Database Connection, Decorators, and Signal Processing Improvements
  src/dispatch/config.py
  src/dispatch/database/core.py
  src/dispatch/decorators.py
  src/dispatch/signal/flows.py
  tests/case/test_case_views.py
Labels: enhancement
