Repository Netflix/dispatch, pull requests merged in 2025-05, with the labels that each got.

#5949 fix(ui): force wrap on timeline events
  src/dispatch/static/dispatch/src/incident/TimelineTab.vue
  src/dispatch/static/dispatch/src/styles/timeline.css
Labels: bug

#5947 (slack) show case add entities button even if no entities currently
  src/dispatch/plugins/dispatch_slack/case/interactive.py
Labels: bug

#5954 enhancement(ui): avatar atomic, user profile pics in case page
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/static/dispatch/src/atomics/CurrentUserAvatar.vue
  src/dispatch/static/dispatch/src/atomics/UserAvatar.vue
  src/dispatch/static/dispatch/src/case/PageHeader.vue
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
  src/dispatch/static/dispatch/src/participant/ParticipantAvatarGroup.vue
  src/dispatch/static/dispatch/src/participant/ParticipantSearchPopover.vue
Labels: enhancement, javascript

#5957 fix(plugin): handle error when groupkey not found
  src/dispatch/plugins/dispatch_google/groups/plugin.py
Labels: bug

#5966 fix(pydantic): fixes several issues detected by pydantic v2
  src/dispatch/case/views.py
  src/dispatch/document/service.py
  src/dispatch/individual/models.py
  src/dispatch/individual/service.py
  src/dispatch/plugin/models.py
  src/dispatch/plugins/dispatch_core/plugin.py
  src/dispatch/project/models.py
Labels: bug, enhancement

#5964 feat(db): adds user confirmation to database cli commands
  .github/workflows/playwright.yml
  data/dispatch-sample-data.dump
  src/dispatch/cli.py
  src/dispatch/incident/models.py
  src/dispatch/incident/views.py
  src/dispatch/static/dispatch/components.d.ts
  src/dispatch/ticket/models.py
Labels: enhancement

#5973 fix(signal): keep existing filters on signal update
  src/dispatch/auth/models.py
  src/dispatch/cli.py
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
  src/dispatch/static/dispatch/src/signal/api.js
Labels: bug

#5974 fix(models): updating to Pydantic v2 ValidationData
  src/dispatch/conference/models.py
  src/dispatch/document/models.py
Labels: bug

#5976 fix(slack): allow subject.id to be a number
  src/dispatch/plugins/dispatch_slack/models.py
Labels: bug

#5975 fix(signal): set to None to allow missing parameters
  src/dispatch/project/models.py
  src/dispatch/signal/models.py
Labels: bug

#5979 fix(models): adding default None to create objects with optional attributes
  src/dispatch/auth/models.py
  src/dispatch/data/alert/models.py
  src/dispatch/email_templates/models.py
  src/dispatch/entity/models.py
  src/dispatch/entity_type/models.py
  src/dispatch/notification/models.py
  src/dispatch/plugin/models.py
Labels: bug

#5980 fix(slack): PlainOption requires string values
  src/dispatch/plugins/dispatch_slack/fields.py
Labels: bug

#5981 fix(slack): convert ids back from string to int
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#5986 fix(plugin): fixes plugin configuration not loading
  src/dispatch/individual/models.py
  src/dispatch/plugin/models.py
  src/dispatch/static/dispatch/src/plugin/store.js
Labels: bug

#5987 fix(slack): fixing initial value for notification group update
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#5988 fix(oncall service): return correct message if we encounter an integr…
  src/dispatch/service/views.py
Labels: bug

#5991 fix(jira): pass url as str
  src/dispatch/plugins/dispatch_atlassian_confluence/docs/plugin.py
  src/dispatch/plugins/dispatch_atlassian_confluence/plugin.py
  src/dispatch/plugins/dispatch_jira/plugin.py
  src/dispatch/plugins/dispatch_pagerduty/plugin.py
  src/dispatch/plugins/dispatch_slack/plugin.py
  src/dispatch/plugins/generic_workflow/plugin.py
Labels: bug

#5992 fix(auth): adding missing default
  src/dispatch/auth/models.py
Labels: bug

#5990 fix(ui): fixes participant lint error
  src/dispatch/static/dispatch/src/participant/ParticipantSearchPopover.vue
Labels: bug

#5993 fix(slack): change positional to named arguments
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#5994 fix(ai): use subquery instead of from_self
  src/dispatch/ai/service.py
Labels: bug

#5989 feat(cases): list api minimal with extras
  src/dispatch/case/models.py
  src/dispatch/case/views.py
Labels: enhancement

#5995 fix(signal): remove redundant `db_session.commit()` in `create_signal_instance`
  src/dispatch/signal/service.py
Labels: bug

#5998 fix(slack): ThreadActivityEvent.fetch_activity() missing 1 required positional argument: self
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#5999 fix(auth): type error encoding without a string argument
  src/dispatch/auth/models.py
  src/dispatch/auth/service.py
Labels: bug

#6000 fix: slack plugin activity fetch
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: bug

#6001 fix(slack): values must be str type
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
Labels: bug

#6002 fix: make workflow read optional
  src/dispatch/workflow/models.py
Labels: bug

#6003 fix: signal transaction management
  src/dispatch/signal/service.py
  src/dispatch/signal/views.py
Labels: bug

#6006 Fixes NotNullViolation on user creation
  src/dispatch/auth/models.py
Labels: bug

#6007 Do not set password to None before user creation call
  src/dispatch/auth/service.py
Labels: bug

#6008 fix(db): sqlalchemy 2.0 _entities attr
  src/dispatch/database/service.py
  src/dispatch/search/fulltext/__init__.py
Labels: bug

#6009 fix: call commit in create_signal_instance
  src/dispatch/signal/service.py
Labels: bug

#6010 fix: source description is optional
  src/dispatch/data/source/models.py
Labels: bug

#6011 fix(db): fixes joined model comparison error
  src/dispatch/database/service.py
Labels: bug

#6015 fix(ui): event form ui does not supply necessary data for case creation
  src/dispatch/static/dispatch/src/events/ReportSubmissionCard.vue
  src/dispatch/static/dispatch/src/util/project.js
Labels: bug

#6016 fix: default restricted visibility on report form
  src/dispatch/static/dispatch/src/events/ReportSubmissionCard.vue
Labels: bug, chore

#6020 tests(ui): test security event form submission
  data/dispatch-sample-data.dump
  tests/static/e2e/fixtures/dispatch-fixtures.ts
  tests/static/e2e/pages/report-event-page.ts
  tests/static/e2e/report-event.spec.ts
  tests/static/e2e/routes.ts
Labels: tests

#6022 fix(cases): use separate email template for cases
  src/dispatch/case/flows.py
  src/dispatch/email_templates/enums.py
  src/dispatch/incident/messaging.py
  src/dispatch/static/dispatch/src/email_templates/NewEditSheet.vue
  tests/factories.py
Labels: bug

#6026 fix(signal): don't dedup on canary signals
  src/dispatch/signal/service.py
  tests/signal/test_signal_service.py
Labels: bug

#6025 (refactor) signal triggers page with entity information
  src/dispatch/static/dispatch/src/signal/InstanceEntityPopover.vue
  src/dispatch/static/dispatch/src/signal/TableInstance.vue
Labels: enhancement
