Repository Netflix/dispatch, pull requests merged in 2025-06, with the labels that each got.

#6032 enhancement(events): prompt assignee for triage in Slack
  src/dispatch/case/flows.py
  src/dispatch/case/messaging.py
  src/dispatch/conversation/enums.py
  src/dispatch/plugins/dispatch_slack/case/enums.py
  src/dispatch/plugins/dispatch_slack/case/interactive.py
  src/dispatch/plugins/dispatch_slack/fields.py
  src/dispatch/plugins/dispatch_slack/plugin.py
Labels: enhancement

#6040 fix(events): Update prompt should only be for events
  src/dispatch/case/flows.py
Labels: bug

#6049 fix(slack): ensures we don't exceed 3000 limit
  .pre-commit-config.yaml
  src/dispatch/plugins/dispatch_slack/case/messages.py
Labels: bug

#6050 fix(slack): log warning instead of throwing exception when user posts to main triage channel thread
  src/dispatch/conversation/service.py
  tests/conversation/test_conversation_service.py
Labels: bug

#6059 fix(case): fixing case filtering
  src/dispatch/database/service.py
Labels: bug

#6067 feat(case): adds ability to create and edit custom timeline events for cases
  src/dispatch/auth/permissions.py
  src/dispatch/case/service.py
  src/dispatch/case/views.py
  src/dispatch/document/service.py
  src/dispatch/event/flows.py
  src/dispatch/event/models.py
  src/dispatch/event/service.py
  src/dispatch/plugins/dispatch_slack/incident/interactive.py
  src/dispatch/static/dispatch/src/case/CaseTimelineTabV1.vue
  src/dispatch/static/dispatch/src/case/DeleteEventDialog.vue
  src/dispatch/static/dispatch/src/case/EditEventDialog.vue
  src/dispatch/static/dispatch/src/case/TimelineExportDialog.vue
  src/dispatch/static/dispatch/src/case/TimelineFilterDialog.vue
  src/dispatch/static/dispatch/src/case/api.js
  src/dispatch/static/dispatch/src/case/store.js
  tests/case/test_case_event_views.py
  tests/case/test_case_service.py
Labels: enhancement

#6074 feat(case): adds stable status to cases
  docs/scripts/openapi.yaml
  src/dispatch/case/enums.py
  src/dispatch/case/flows.py
  src/dispatch/case/models.py
  src/dispatch/case/scheduled.py
  src/dispatch/case/service.py
  src/dispatch/case/views.py
  src/dispatch/case_cost/scheduled.py
  src/dispatch/case_cost/service.py
  src/dispatch/database/revisions/tenant/versions/2025-06-20_5ed5defd1a55.py
  src/dispatch/messaging/strings.py
  src/dispatch/static/dispatch/src/case/CaseStatus.vue
  src/dispatch/static/dispatch/src/case/CaseStatusSelectGroup.vue
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
  src/dispatch/static/dispatch/src/case/Page.vue
  src/dispatch/static/dispatch/src/case/TableExportDialog.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseDialogFilter.vue
  src/dispatch/static/dispatch/src/dashboard/case/CaseOverview.vue
  tests/case/test_case_messaging.py
  tests/case_cost/test_case_cost_service.py
  tests/factories.py
Labels: enhancement

#6081 enhancement/fix: incident bridge auto-join configurable, no 6 week default
  src/dispatch/auth/models.py
  src/dispatch/auth/service.py
  src/dispatch/auth/views.py
  src/dispatch/database/revisions/core/versions/2025-06-23_903183fd9aee.py
  src/dispatch/incident/flows.py
  src/dispatch/individual/models.py
  src/dispatch/individual/service.py
  src/dispatch/individual/views.py
  src/dispatch/plugins/dispatch_google/calendar/plugin.py
  src/dispatch/plugins/dispatch_google/config.py
  src/dispatch/plugins/dispatch_zoom/config.py
  src/dispatch/plugins/dispatch_zoom/plugin.py
  src/dispatch/static/dispatch/src/auth/api.js
  src/dispatch/static/dispatch/src/auth/store.js
  src/dispatch/static/dispatch/src/auth/userSettings.js
  src/dispatch/static/dispatch/src/components/AppToolbar.vue
Labels: bug, enhancement

#6086 feat(cases): add case visibility notificaiton
  src/dispatch/case/messaging.py
  src/dispatch/messaging/strings.py
Labels: enhancement

#6088 fix(tags): disallow tag recommendations for restricted incidents
  src/dispatch/ai/service.py
Labels: bug

#6089 fix(email_templates): disallow creation for non admins
  requirements-base.txt
  src/dispatch/email_templates/views.py
Labels: bug

#6090 fix(ui): tooltip props get unique name
  src/dispatch/static/dispatch/src/case/ClosedDialog.vue
  src/dispatch/static/dispatch/src/case/DetailsTab.vue
Labels: bug
